-- ============================================================================
-- Duke College — question bank: The Learning Gate, Reading Skill (LG-R-RS-4a)
-- 12 worksheets / 142 questions. Run AFTER setup.sql. Adds questions only.
-- correct_index is 0-based. Answers were generated for you; please spot-check.
-- ============================================================================

-- ---- 4a1  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a1 - Context Clue','G4', $p$Choose the best word for blank (1): A flea market is a place where people can sell things they no (1)___ need. There are long tables at some flea markets. Traders can (2)___ a whole table or part of a table. (3)___ at a flea market do not cost much money. Used clothes are often sold at flea markets. The (4)___ may have (5)___ them, or they may just be tired of them. But the clothes will fit someone else.$p$, $c$["more","longer","shortly","quick"]$c$::jsonb, 1, 1),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (2): A flea market is a place where people can sell things they no (1)___ need. There are long tables at some flea markets. Traders can (2)___ a whole table or part of a table. (3)___ at a flea market do not cost much money. Used clothes are often sold at flea markets. The (4)___ may have (5)___ them, or they may just be tired of them. But the clothes will fit someone else.$p$, $c$["place","manufacture","rent","conquer"]$c$::jsonb, 2, 2),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (3): A flea market is a place where people can sell things they no (1)___ need. There are long tables at some flea markets. Traders can (2)___ a whole table or part of a table. (3)___ at a flea market do not cost much money. Used clothes are often sold at flea markets. The (4)___ may have (5)___ them, or they may just be tired of them. But the clothes will fit someone else.$p$, $c$["Coats","Items","Shoes","Ducks"]$c$::jsonb, 1, 3),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (4): A flea market is a place where people can sell things they no (1)___ need. There are long tables at some flea markets. Traders can (2)___ a whole table or part of a table. (3)___ at a flea market do not cost much money. Used clothes are often sold at flea markets. The (4)___ may have (5)___ them, or they may just be tired of them. But the clothes will fit someone else.$p$, $c$["owners","presidents","gardeners","factories"]$c$::jsonb, 0, 4),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (5): A flea market is a place where people can sell things they no (1)___ need. There are long tables at some flea markets. Traders can (2)___ a whole table or part of a table. (3)___ at a flea market do not cost much money. Used clothes are often sold at flea markets. The (4)___ may have (5)___ them, or they may just be tired of them. But the clothes will fit someone else.$p$, $c$["outraged","overlapped","lengthened","outgrown"]$c$::jsonb, 3, 5),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (6): Benjamin Franklin was one of the greatest men who ever lived. He knew so (6)___ about many things. He taught himself to read when he was (7)___ an eight-year-old boy. At 12, he went to work for his brother, a printer. Soon, Franklin (8)___ his own printing house in Philadelphia. His book, Poor Richard's Almanac, is filled with funny and (9)___ sayings. He (10)___ the American colonies to become free from England.$p$, $c$["little","much","tiny","variously"]$c$::jsonb, 1, 6),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (7): Benjamin Franklin was one of the greatest men who ever lived. He knew so (6)___ about many things. He taught himself to read when he was (7)___ an eight-year-old boy. At 12, he went to work for his brother, a printer. Soon, Franklin (8)___ his own printing house in Philadelphia. His book, Poor Richard's Almanac, is filled with funny and (9)___ sayings. He (10)___ the American colonies to become free from England.$p$, $c$["over","also","merely","about"]$c$::jsonb, 2, 7),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (8): Benjamin Franklin was one of the greatest men who ever lived. He knew so (6)___ about many things. He taught himself to read when he was (7)___ an eight-year-old boy. At 12, he went to work for his brother, a printer. Soon, Franklin (8)___ his own printing house in Philadelphia. His book, Poor Richard's Almanac, is filled with funny and (9)___ sayings. He (10)___ the American colonies to become free from England.$p$, $c$["constructed","posted","began","plastered"]$c$::jsonb, 2, 8),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (9): Benjamin Franklin was one of the greatest men who ever lived. He knew so (6)___ about many things. He taught himself to read when he was (7)___ an eight-year-old boy. At 12, he went to work for his brother, a printer. Soon, Franklin (8)___ his own printing house in Philadelphia. His book, Poor Richard's Almanac, is filled with funny and (9)___ sayings. He (10)___ the American colonies to become free from England.$p$, $c$["convincing","believable","clever","plural"]$c$::jsonb, 2, 9),
('4a1 - Context Clue','G4', $p$Choose the best word for blank (10): Benjamin Franklin was one of the greatest men who ever lived. He knew so (6)___ about many things. He taught himself to read when he was (7)___ an eight-year-old boy. At 12, he went to work for his brother, a printer. Soon, Franklin (8)___ his own printing house in Philadelphia. His book, Poor Richard's Almanac, is filled with funny and (9)___ sayings. He (10)___ the American colonies to become free from England.$p$, $c$["assumed","assisted","assembled","accustomed"]$c$::jsonb, 1, 10),
('4a1 - Context Clue','G4', $p$Aesop's fables have many ______ animals in them as well as foolish ones.$p$, $c$["clever","much","mere","crouch"]$c$::jsonb, 0, 11),
('4a1 - Context Clue','G4', $p$On Halloween, we ______ frightening horror movies.$p$, $c$["own","lengthen","outgrow","rent"]$c$::jsonb, 3, 12),
('4a1 - Context Clue','G4', $p$Long ago, people did not care for kids' opinions because they were ______ children.$p$, $c$["almost","merely","much","clever"]$c$::jsonb, 1, 13),
('4a1 - Context Clue','G4', $p$Anyone who damages property must repay the ______ of the property.$p$, $c$["renters","doctors","committees","owners"]$c$::jsonb, 3, 14),
('4a1 - Context Clue','G4', $p$I need new sneakers because I have ______ my old ones.$p$, $c$["rented","owned","claimed","outgrown"]$c$::jsonb, 3, 15),
('4a1 - Context Clue','G4', $p$______ to his surprise, his brother tricked him.$p$, $c$["Beginning","Much","Merely","Lots"]$c$::jsonb, 1, 16),
('4a1 - Context Clue','G4', $p$A toothbrush, a pair of pajamas, and some clothes were just a few of the ______ I brought to camp.$p$, $c$["times","items","owners","machines"]$c$::jsonb, 1, 17),
('4a1 - Context Clue','G4', $p$I ______ to study too late, and I couldn't finish studying the material before the exam.$p$, $c$["much","assisted","clubbed","began"]$c$::jsonb, 3, 18),
('4a1 - Context Clue','G4', $p$The ______ I waited for the interview, the more nervous I grew.$p$, $c$["longer","rent","owner","item"]$c$::jsonb, 0, 19),
('4a1 - Context Clue','G4', $p$The nurse ______ the doctor when he was examining a patient.$p$, $c$["began","moved","assisted","clobbered"]$c$::jsonb, 2, 20);

-- ---- 4a2  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a2 - Context Clue','G4', $p$Choose the best word for blank (1): Many of the most widely read fairy tales were (1)___ by Hans Christian Andersen. He was born in Denmark in 1805. Although his stories were meant for children, (2)___ enjoy them (3)___. Most of Andersen's fairy tales (4)___ a moral which tries to show people how to lead better lives. Both "The Ugly Duckling" and "The Emperor's New Clothes" try to (5)___ people that looks should not be so important.$p$, $c$["read","manufactured","written","discovered"]$c$::jsonb, 2, 1),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (2): Many of the most widely read fairy tales were (1)___ by Hans Christian Andersen. He was born in Denmark in 1805. Although his stories were meant for children, (2)___ enjoy them (3)___. Most of Andersen's fairy tales (4)___ a moral which tries to show people how to lead better lives. Both "The Ugly Duckling" and "The Emperor's New Clothes" try to (5)___ people that looks should not be so important.$p$, $c$["boys","girls","others","adults"]$c$::jsonb, 3, 2),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (3): Many of the most widely read fairy tales were (1)___ by Hans Christian Andersen. He was born in Denmark in 1805. Although his stories were meant for children, (2)___ enjoy them (3)___. Most of Andersen's fairy tales (4)___ a moral which tries to show people how to lead better lives. Both "The Ugly Duckling" and "The Emperor's New Clothes" try to (5)___ people that looks should not be so important.$p$, $c$["as fast","as much","as long","as well"]$c$::jsonb, 3, 3),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (4): Many of the most widely read fairy tales were (1)___ by Hans Christian Andersen. He was born in Denmark in 1805. Although his stories were meant for children, (2)___ enjoy them (3)___. Most of Andersen's fairy tales (4)___ a moral which tries to show people how to lead better lives. Both "The Ugly Duckling" and "The Emperor's New Clothes" try to (5)___ people that looks should not be so important.$p$, $c$["pray","contain","demand","sell"]$c$::jsonb, 1, 4),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (5): Many of the most widely read fairy tales were (1)___ by Hans Christian Andersen. He was born in Denmark in 1805. Although his stories were meant for children, (2)___ enjoy them (3)___. Most of Andersen's fairy tales (4)___ a moral which tries to show people how to lead better lives. Both "The Ugly Duckling" and "The Emperor's New Clothes" try to (5)___ people that looks should not be so important.$p$, $c$["explain","convince","describe","control"]$c$::jsonb, 1, 5),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (6): Whenever you see something new, you (6)___ it to things you (7)___ know. When you first saw a rocket, you (8)___ have said, "It is like an airplane, but it has no wings. It is long and shiny and is (9)___ like a bullet." This is the quickest and surest way to learn about new things. It is (10)___ a good way to learn new words.$p$, $c$["stick","agree","confuse","compare"]$c$::jsonb, 3, 6),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (7): Whenever you see something new, you (6)___ it to things you (7)___ know. When you first saw a rocket, you (8)___ have said, "It is like an airplane, but it has no wings. It is long and shiny and is (9)___ like a bullet." This is the quickest and surest way to learn about new things. It is (10)___ a good way to learn new words.$p$, $c$["already","never","before","equally"]$c$::jsonb, 0, 7),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (8): Whenever you see something new, you (6)___ it to things you (7)___ know. When you first saw a rocket, you (8)___ have said, "It is like an airplane, but it has no wings. It is long and shiny and is (9)___ like a bullet." This is the quickest and surest way to learn about new things. It is (10)___ a good way to learn new words.$p$, $c$["instantly","purposely","privately","might"]$c$::jsonb, 3, 8),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (9): Whenever you see something new, you (6)___ it to things you (7)___ know. When you first saw a rocket, you (8)___ have said, "It is like an airplane, but it has no wings. It is long and shiny and is (9)___ like a bullet." This is the quickest and surest way to learn about new things. It is (10)___ a good way to learn new words.$p$, $c$["slippery","covered","shaped","sound"]$c$::jsonb, 2, 9),
('4a2 - Context Clue','G4', $p$Choose the best word for blank (10): Whenever you see something new, you (6)___ it to things you (7)___ know. When you first saw a rocket, you (8)___ have said, "It is like an airplane, but it has no wings. It is long and shiny and is (9)___ like a bullet." This is the quickest and surest way to learn about new things. It is (10)___ a good way to learn new words.$p$, $c$["personally","quickly","popularly","certainly"]$c$::jsonb, 3, 10),
('4a2 - Context Clue','G4', $p$Orange slices are ______ like half moons.$p$, $c$["compared","shaped","boxed","combed"]$c$::jsonb, 1, 11),
('4a2 - Context Clue','G4', $p$______ are independent, but they have many responsibilities.$p$, $c$["Containers","Adults","Commercials","Animals"]$c$::jsonb, 1, 12),
('4a2 - Context Clue','G4', $p$I could play the piano ______ my sister after practicing hard.$p$, $c$["convincing","containing","like","as well as"]$c$::jsonb, 3, 13),
('4a2 - Context Clue','G4', $p$The teacher told us to ______ answers with one another.$p$, $c$["shape","plot","compare","crowd"]$c$::jsonb, 2, 14),
('4a2 - Context Clue','G4', $p$The prosecutor tries to ______ the jury that the accused is guilty.$p$, $c$["contain","write","convince","complain"]$c$::jsonb, 2, 15),
('4a2 - Context Clue','G4', $p$The computer ______ programs and information.$p$, $c$["convinces","controls","contains","connects"]$c$::jsonb, 2, 16),
('4a2 - Context Clue','G4', $p$My brother ______ had the chicken pox, so he won't get it anymore.$p$, $c$["might","slowly","already","happily"]$c$::jsonb, 2, 17),
('4a2 - Context Clue','G4', $p$My mother ______ forget my birthday party, so I am going to write a note to help her remember.$p$, $c$["might","only","never","must"]$c$::jsonb, 0, 18),
('4a2 - Context Clue','G4', $p$The Koran was ______ in the Arabic language.$p$, $c$["contained","written","compromised","promised"]$c$::jsonb, 1, 19),
('4a2 - Context Clue','G4', $p$Columbus ______ knew that the world was round because there were already documents by people who had gone around the world.$p$, $c$["might","never","certainly","over"]$c$::jsonb, 2, 20);

-- ---- 4a3  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a3 - Context Clue','G4', $p$Choose the best word for blank (1): The world's largest living thing is the General Sherman Tree. This (1)___ tree grows in the Sequoia National Park in California. It (2)___ over 272 feet tall. If you wanted to tie a rope around its (3)___, you would need a rope that is over 70 feet (4)___. In some places, the bark of this tree is 2 feet (5)___. Scientists believe that this tree began to grow over 3,000 years ago.$p$, $c$["giant","green","poor","young"]$c$::jsonb, 0, 1),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (2): The world's largest living thing is the General Sherman Tree. This (1)___ tree grows in the Sequoia National Park in California. It (2)___ over 272 feet tall. If you wanted to tie a rope around its (3)___, you would need a rope that is over 70 feet (4)___. In some places, the bark of this tree is 2 feet (5)___. Scientists believe that this tree began to grow over 3,000 years ago.$p$, $c$["swings","stands","makes","hangs"]$c$::jsonb, 1, 2),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (3): The world's largest living thing is the General Sherman Tree. This (1)___ tree grows in the Sequoia National Park in California. It (2)___ over 272 feet tall. If you wanted to tie a rope around its (3)___, you would need a rope that is over 70 feet (4)___. In some places, the bark of this tree is 2 feet (5)___. Scientists believe that this tree began to grow over 3,000 years ago.$p$, $c$["trunk","leaves","roots","seeds"]$c$::jsonb, 0, 3),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (4): The world's largest living thing is the General Sherman Tree. This (1)___ tree grows in the Sequoia National Park in California. It (2)___ over 272 feet tall. If you wanted to tie a rope around its (3)___, you would need a rope that is over 70 feet (4)___. In some places, the bark of this tree is 2 feet (5)___. Scientists believe that this tree began to grow over 3,000 years ago.$p$, $c$["tall","high","thick","long"]$c$::jsonb, 3, 4),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (5): The world's largest living thing is the General Sherman Tree. This (1)___ tree grows in the Sequoia National Park in California. It (2)___ over 272 feet tall. If you wanted to tie a rope around its (3)___, you would need a rope that is over 70 feet (4)___. In some places, the bark of this tree is 2 feet (5)___. Scientists believe that this tree began to grow over 3,000 years ago.$p$, $c$["above","thick","apart","away"]$c$::jsonb, 1, 5),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (6): Today fresh fruits and vegetables are (6)___ to many places in (7)___ cars and trucks, which keep them from spoiling. They are also kept from (8)___ by canning, (9)___, and dehydration. Dehydration means taking the water out. When water is added later, the vegetables and fruits taste (10)___ as if they had just been picked.$p$, $c$["crippled","plunged","shipped","chosen"]$c$::jsonb, 2, 6),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (7): Today fresh fruits and vegetables are (6)___ to many places in (7)___ cars and trucks, which keep them from spoiling. They are also kept from (8)___ by canning, (9)___, and dehydration. Dehydration means taking the water out. When water is added later, the vegetables and fruits taste (10)___ as if they had just been picked.$p$, $c$["dried","elegant","refrigerated","business"]$c$::jsonb, 2, 7),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (8): Today fresh fruits and vegetables are (6)___ to many places in (7)___ cars and trucks, which keep them from spoiling. They are also kept from (8)___ by canning, (9)___, and dehydration. Dehydration means taking the water out. When water is added later, the vegetables and fruits taste (10)___ as if they had just been picked.$p$, $c$["drooping","bursting","spoiling","drying"]$c$::jsonb, 2, 8),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (9): Today fresh fruits and vegetables are (6)___ to many places in (7)___ cars and trucks, which keep them from spoiling. They are also kept from (8)___ by canning, (9)___, and dehydration. Dehydration means taking the water out. When water is added later, the vegetables and fruits taste (10)___ as if they had just been picked.$p$, $c$["starving","freezing","refreshing","panting"]$c$::jsonb, 1, 9),
('4a3 - Context Clue','G4', $p$Choose the best word for blank (10): Today fresh fruits and vegetables are (6)___ to many places in (7)___ cars and trucks, which keep them from spoiling. They are also kept from (8)___ by canning, (9)___, and dehydration. Dehydration means taking the water out. When water is added later, the vegetables and fruits taste (10)___ as if they had just been picked.$p$, $c$["almost","over","never","enough"]$c$::jsonb, 0, 10),
('4a3 - Context Clue','G4', $p$Slaves were ______ from Africa to America.$p$, $c$["refrigerated","spoiled","remembered","shipped"]$c$::jsonb, 3, 11),
('4a3 - Context Clue','G4', $p$The Empire State Building ______ in Manhattan, New York.$p$, $c$["thickens","stands","falls","grinds"]$c$::jsonb, 1, 12),
('4a3 - Context Clue','G4', $p$Foods are ______ so that they will not rot.$p$, $c$["shipped","refrigerated","shattered","spread"]$c$::jsonb, 1, 13),
('4a3 - Context Clue','G4', $p$The string was two feet ______.$p$, $c$["long","thick","tall","deep"]$c$::jsonb, 0, 14),
('4a3 - Context Clue','G4', $p$The book is so ______ because it is two thousand pages long.$p$, $c$["thick","promising","annual","shallow"]$c$::jsonb, 0, 15),
('4a3 - Context Clue','G4', $p$The ______ buildings in Manhattan are among the highest in the world.$p$, $c$["thick","protected","secure","giant"]$c$::jsonb, 3, 16),
('4a3 - Context Clue','G4', $p$A protester chained himself to the ______ of the tree.$p$, $c$["leaves","trunk","bottom","lash"]$c$::jsonb, 1, 17),
('4a3 - Context Clue','G4', $p$Some parents are ______ their children by giving them everything they want.$p$, $c$["freezing","blaming","shipping","spoiling"]$c$::jsonb, 3, 18),
('4a3 - Context Clue','G4', $p$Furs help keep animals from ______ during the winter.$p$, $c$["refrigerating","freezing","shipping","spoiling"]$c$::jsonb, 1, 19),
('4a3 - Context Clue','G4', $p$I ______ forgot to bring lunch, but my mom remembered and gave it to me.$p$, $c$["never","almost","should","likely"]$c$::jsonb, 1, 20);

-- ---- 4a4  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a4 - Context Clue','G4', $p$Choose the best word for blank (1): The state's historic sites and (1)___ views (2)___ many tourists. Many lakes, (3)___, and rivers offer swimming, boating, and other water (4)___. The Abraham Lincoln Birthplace Memorial, near Hodgenville, houses the log cabin in which Abe Lincoln is said to have been born. It is a national (5)___ site.$p$, $c$["scenic","important","bright","rough"]$c$::jsonb, 0, 1),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (2): The state's historic sites and (1)___ views (2)___ many tourists. Many lakes, (3)___, and rivers offer swimming, boating, and other water (4)___. The Abraham Lincoln Birthplace Memorial, near Hodgenville, houses the log cabin in which Abe Lincoln is said to have been born. It is a national (5)___ site.$p$, $c$["praise","amounts","dismay","attract"]$c$::jsonb, 3, 2),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (3): The state's historic sites and (1)___ views (2)___ many tourists. Many lakes, (3)___, and rivers offer swimming, boating, and other water (4)___. The Abraham Lincoln Birthplace Memorial, near Hodgenville, houses the log cabin in which Abe Lincoln is said to have been born. It is a national (5)___ site.$p$, $c$["hills","streams","prairies","showers"]$c$::jsonb, 1, 3),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (4): The state's historic sites and (1)___ views (2)___ many tourists. Many lakes, (3)___, and rivers offer swimming, boating, and other water (4)___. The Abraham Lincoln Birthplace Memorial, near Hodgenville, houses the log cabin in which Abe Lincoln is said to have been born. It is a national (5)___ site.$p$, $c$["items","sports","drinks","arts"]$c$::jsonb, 1, 4),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (5): The state's historic sites and (1)___ views (2)___ many tourists. Many lakes, (3)___, and rivers offer swimming, boating, and other water (4)___. The Abraham Lincoln Birthplace Memorial, near Hodgenville, houses the log cabin in which Abe Lincoln is said to have been born. It is a national (5)___ site.$p$, $c$["scientific","discovery","playground","historic"]$c$::jsonb, 3, 5),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (6): The octopus has eight arms, and the squid has ten. Both the octopus and the (6)___ depend for protection not on a heavy shell, but on their (7)___ to swim away quickly from the place of (8)___. They can also squirt a black (9)___, which forms a dark cloud and helps them to (10)___ from danger.$p$, $c$["squid","shark","clams","starfish"]$c$::jsonb, 0, 6),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (7): The octopus has eight arms, and the squid has ten. Both the octopus and the (6)___ depend for protection not on a heavy shell, but on their (7)___ to swim away quickly from the place of (8)___. They can also squirt a black (9)___, which forms a dark cloud and helps them to (10)___ from danger.$p$, $c$["plan","strength","struggle","ability"]$c$::jsonb, 3, 7),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (8): The octopus has eight arms, and the squid has ten. Both the octopus and the (6)___ depend for protection not on a heavy shell, but on their (7)___ to swim away quickly from the place of (8)___. They can also squirt a black (9)___, which forms a dark cloud and helps them to (10)___ from danger.$p$, $c$["protection","oasis","danger","wound"]$c$::jsonb, 2, 8),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (9): The octopus has eight arms, and the squid has ten. Both the octopus and the (6)___ depend for protection not on a heavy shell, but on their (7)___ to swim away quickly from the place of (8)___. They can also squirt a black (9)___, which forms a dark cloud and helps them to (10)___ from danger.$p$, $c$["particles","water","quill","fluid"]$c$::jsonb, 3, 9),
('4a4 - Context Clue','G4', $p$Choose the best word for blank (10): The octopus has eight arms, and the squid has ten. Both the octopus and the (6)___ depend for protection not on a heavy shell, but on their (7)___ to swim away quickly from the place of (8)___. They can also squirt a black (9)___, which forms a dark cloud and helps them to (10)___ from danger.$p$, $c$["creep","escape","glide","bruise"]$c$::jsonb, 1, 10),
('4a4 - Context Clue','G4', $p$Beautiful hills and a beach provided ______ views to the hotel customers.$p$, $c$["historic","scenic","sinful","streaming"]$c$::jsonb, 1, 11),
('4a4 - Context Clue','G4', $p$Scents of flowers ______ the bees and butterflies, who help pollinate the flowers.$p$, $c$["streams","sport","sneaks","attract"]$c$::jsonb, 3, 12),
('4a4 - Context Clue','G4', $p$Before the ______ were polluted, people swam in them.$p$, $c$["sports","history","streams","scenes"]$c$::jsonb, 2, 13),
('4a4 - Context Clue','G4', $p$Baseball is America's favorite ______.$p$, $c$["scene","stream","sport","stage"]$c$::jsonb, 2, 14),
('4a4 - Context Clue','G4', $p$The Battle of Saratoga was ______ because it was the turning point of the Revolutionary War when the French were persuaded to join the American patriots.$p$, $c$["scenic","attractive","historic","marketable"]$c$::jsonb, 2, 15),
('4a4 - Context Clue','G4', $p$______ have ten arms and a slimy body.$p$, $c$["Fluids","Dolphins","Squids","Slugs"]$c$::jsonb, 2, 16),
('4a4 - Context Clue','G4', $p$Artists must have the ______ to draw good pictures.$p$, $c$["danger","fluid","computer","ability"]$c$::jsonb, 3, 17),
('4a4 - Context Clue','G4', $p$The sign on the door says ______ because there are dangerous chemicals in there.$p$, $c$["'fluid'","'danger'","'escape'","'Restroom'"]$c$::jsonb, 1, 18),
('4a4 - Context Clue','G4', $p$Water is a clear colorless ______.$p$, $c$["ability","solid","fluid","earth"]$c$::jsonb, 2, 19),
('4a4 - Context Clue','G4', $p$Thieves tried to ______ from the crime scene.$p$, $c$["enclose","explain","execute","escape"]$c$::jsonb, 3, 20);

-- ---- 4a5  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a5 - Main Idea','G4', $p$Jellyfish come in different sizes and colors, just as people do. Some are tiny and some are as large as a few feet wide. Some are clear, some are orange, some are red, and some even glow in the dark.  This story mainly tells:$p$, $c$["how jellyfish sting","how jellyfish are different from one another","how to deal with a jellyfish sting","that most jellyfish are clear"]$c$::jsonb, 1, 1),
('4a5 - Main Idea','G4', $p$The common mole has a difficult life. It is extremely sensitive to noise. For example, a car door slamming will be enough to kill the mole. Also, the mole has to eat every four hours or it will die.  This story mainly tells:$p$, $c$["what moles do in winter when there is little food","where moles live","how difficult it is to be a mole","what moles eat"]$c$::jsonb, 2, 2),
('4a5 - Main Idea','G4', $p$A long time ago, in the country of India, 300 feet of rain fell in one year. That is enough rain to cover a nine-story building. It was the worst flood ever recorded in India.  This story mainly tells:$p$, $c$["what happened when the rain fell","how rain damaged a 300 foot building","the worst flood in India","when rain fell in India"]$c$::jsonb, 2, 3),
('4a5 - Main Idea','G4', $p$Did you know that the position of a horse's ears indicate what it is about to do? If the horse's ears are forward, then everything is okay. If the horse's ears are back, be careful; it is about to kick or run away.  This story mainly tells:$p$, $c$["how to ride a horse","why horses run away","what you can tell from a horse's ears","how to pet a horse"]$c$::jsonb, 2, 4),
('4a5 - Main Idea','G4', $p$The school day in Holland might make you want to move there. There, the school day ends at 4:00 PM, but they have a two-hour lunch from noon to 2:00 PM. The Hollanders have school on Saturday morning, but on Wednesdays school lasts just half a day.  This story mainly tells:$p$, $c$["what school hours are like in Holland","why you should go to school","what the children in Holland learn in their schools","what days the school is open"]$c$::jsonb, 0, 5),
('4a5 - Main Idea','G4', $p$Houseplants should be watered at the beginning or at the end of each day. Don't water your plants while the sun is shining, or else you might risk burning them. The drops of water act like lenses. The water traps the sunlight and heat, burning the leaves.  This story mainly tells:$p$, $c$["how plants grow","when to water your plants","how plants make their own food","how much water to give a plant"]$c$::jsonb, 1, 6),
('4a5 - Main Idea','G4', $p$Can you believe a giant snake only eats once a year? It can eat up to 400 times as much as it needs. The giant snake can swallow an entire cow. After a meal like that, the snake doesn't need any more food for a long time.  This story mainly tells:$p$, $c$["the eating habits of giant snakes","how big a giant snake is","where giant snakes come from","what snakes like to eat"]$c$::jsonb, 0, 7),
('4a5 - Main Idea','G4', $p$There is a plant in America that is called the Indian Pipe. The plant is so-called because it looks like the white clay pipes Indians use. The stem is white and each stem has a white flower. It doesn't have any green leaves at all.  This story mainly tells:$p$, $c$["what the Indian Pipe plant looks like","where the Indian Pipe plant can be found","who discovered the plant","what Indians do with the Indian Pipe"]$c$::jsonb, 0, 8),
('4a5 - Main Idea','G4', $p$The state of Ohio got its name from a river. Native Americans named the river "Oheo." This means beautiful. Settlers called it the Ohio River. When the land north of the river was to become a state, the government decided to name it after the beautiful river.  This story mainly tells:$p$, $c$["how the river runs","what fish are in the river","how Ohio got its name","why settlers went to Ohio"]$c$::jsonb, 2, 9),
('4a5 - Main Idea','G4', $p$Can you believe that a long time ago spices were so expensive that only rich people could buy them? Cinnamon used to be more expensive than gold. These spices were more often used as medicines and perfumes than they were used for cooking.  This story mainly tells:$p$, $c$["how to cook with spices","why spices make good perfume","how spices were valued years ago","which spices were sold"]$c$::jsonb, 2, 10);

-- ---- 4a6  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a6 - Main Idea','G4', $p$Thousands of years ago, a species of huge dinosaur roamed the earth. Its body weighed more than a few tons and it was over 20 feet long. Its brain, however, weighed about as much as three pencils. This dinosaur wasn't very smart.  This story mainly tells:$p$, $c$["what kind of dinosaur it was","what the dinosaur ate","what the dinosaur did","why one type of dinosaur was not that smart"]$c$::jsonb, 3, 1),
('4a6 - Main Idea','G4', $p$Termite queens lay 30,000 eggs a day. Luckily, most of those eggs don't hatch. If all the eggs hatched, then the queen termite would have a half billion children in her 50-year lifetime.  This story mainly tells:$p$, $c$["where the termite queen lays her eggs","how many eggs a termite queen lays","how termite babies survive","what baby termites eat"]$c$::jsonb, 1, 2),
('4a6 - Main Idea','G4', $p$In every land, people tell stories about magical beasts. The strangest beasts of all lived in Ireland. They were called the Formorians, and they were strange because each one was different from the other. One might have the body of a fish, while another might look like a kangaroo.  This story mainly tells:$p$, $c$["that people used to tell magical stories","about the strangest magical beast","that Formorians lived in Ireland","why the Formorians lived in Ireland"]$c$::jsonb, 1, 3),
('4a6 - Main Idea','G4', $p$At the age of three, Louis Braille lost his sight. When he was ten, he went to a school for blind children. There, books were written in raised letters. The letters "A" and "H" confused him because they felt almost the same. At 15 he made up a new way of writing. He used the idea of raised dots, as once used by soldiers, but he made up his own alphabet. Today, millions of books are read and written in Braille.  This story mainly tells:$p$, $c$["how Louis Braille lost his sight","that, at first, Louis' teachers did not want to use his new way of writing","how long it took Louis to invent his alphabet","how Braille writing began"]$c$::jsonb, 3, 4),
('4a6 - Main Idea','G4', $p$Birds can see better than other animals. Eagles can see better than other birds. This helps them with their main job of hunting. While an eagle is gliding high in the air, it can see a fish in a stream far below.  This story mainly tells:$p$, $c$["why eagles are great hunters","why birds see better than other animals","how high eagles can fly","what eagles look for"]$c$::jsonb, 0, 5),
('4a6 - Main Idea','G4', $p$Did you know that the largest and heaviest animal in the world is the blue whale? Records show one blue whale was 110 feet long and weighed 199 tons. The fastest animal is the Peregrin falcon (a sort of hawk). They can travel 230-240 miles per hour. The longest-living animal is the turtle. The oldest turtle discovered so far was accidentally killed when it was 152 years old.  This story mainly tells:$p$, $c$["information on the blue whale","some interesting facts about animals","how the oldest turtle died","which are the slowest animals alive"]$c$::jsonb, 1, 6),
('4a6 - Main Idea','G4', $p$Many years ago, people learned how to tell the difference between planets and stars. Looking up at the sky through a telescope, they saw that planets changed position from time to time. Planets looked like plates with a steady, shining light. Stars did not move; they looked like points of light that twinkled.  This story mainly tells:$p$, $c$["what planets look like","how far away the stars are from earth","the differences between stars and planets","why people look up at planets and stars"]$c$::jsonb, 2, 7),
('4a6 - Main Idea','G4', $p$Some students ride their bikes to school. Others walk with their friends. Many take the buses or are dropped off by their parents. There are many ways to get to school.  This story mainly tells:$p$, $c$["why family and friends are important","how kids get to school","the fastest way to get to school","why kids take the bus"]$c$::jsonb, 1, 8),
('4a6 - Main Idea','G4', $p$Jogging keeps your muscles toned and your heart in top condition. Jogging gives you the amount of exercise you need to keep your body healthy. Some people even believe that jogging each day helps you live longer.  This story mainly tells:$p$, $c$["why jogging is good for you","that, nowadays, everyone is jogging","that people live longer if they exercise","how jogging began"]$c$::jsonb, 0, 9),
('4a6 - Main Idea','G4', $p$Bread might be the first food ever made. People pounded nuts and seeds between two rocks to make a kind of flour. This early bread was flat, heavy, and dry. It probably didn't taste very good, but it was an important food. Today, bread comes in many shapes, sizes, colors, and tastes.  This story mainly tells:$p$, $c$["why bread is important","who invented bread","how long it took to bake bread","how bread was first made"]$c$::jsonb, 3, 10);

-- ---- 4a7  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a7 - Main Idea','G4', $p$Long ago, very few machines existed. Most things were made with simple tools. Everything took a very long time to build. Roads, for example, were built using garden tools. The workers used shovels to dig dirt and move it. Unfortunately, only a few pounds of dirt could be moved at a time.  This story mainly tells:$p$, $c$["what was needed to build a road","why people used garden tools","how difficult it was to build in the past with few machines","how many tools were used"]$c$::jsonb, 2, 1),
('4a7 - Main Idea','G4', $p$The Egyptians made statues of sphinxes to honor kings and queens. A sphinx has the head of a human and the body of a lion. The oldest and largest sphinx is the Great Sphinx, built in the desert near Giza, Egypt, thousands of years ago. It is 240 feet long and 66 feet high. Even so, it has sometimes been buried by sand.  This story mainly tells:$p$, $c$["how the Great Sphinx was covered by sand","how long ago the Great Sphinx was built","about the Great Sphinx","how many sphinxes exist"]$c$::jsonb, 2, 2),
('4a7 - Main Idea','G4', $p$Mary Ann Evans was born in England in 1819. She loved to read and learned many languages. In 1851, she wrote articles about books, history, and other subjects that interested her. Then, in 1859, she wrote her first book. Even though her books were very popular, in the 1800's people did not think it was proper for a woman to be a writer. So, Mary Ann Evans' readers knew her as George Eliot.  This story mainly tells:$p$, $c$["about women writers of the 1800's","why she used another name","about the life of Mary Ann Evans","how many books were written by Mary Ann Evans"]$c$::jsonb, 2, 3),
('4a7 - Main Idea','G4', $p$A bird's range refers to how far a bird can fly. Some birds are able to fly great distances, and range over almost the whole world. Other birds have a very small range. They travel over areas smaller than one hundred miles.  This story mainly tells:$p$, $c$["how birds' ranges differ","how to find a bird range","why birds like to travel","how long birds can fly without stopping"]$c$::jsonb, 0, 4),
('4a7 - Main Idea','G4', $p$When does a safety signal turn out to be a signal of death? The red, green, and yellow traffic light is a safety signal. Yet some drivers don't see it. Some drivers don't obey it. People cross the street without looking at it. Often, the traffic light turns out to be a signal of death.  This story mainly tells:$p$, $c$["why all people obey traffic lights","how a safety signal turns out to be a signal of death","why all people disobey traffic lights","the color that means stop"]$c$::jsonb, 1, 5),
('4a7 - Main Idea','G4', $p$Glassmakers say that glass will be used in many new ways in the years to come. They say that houses, airplanes, and cars will be made of glass and glass plastics. Roads will be made from glass. Already some of our clothes are made of glass!  This story mainly tells:$p$, $c$["why things are made of glass","how roads will be made","how glass may be used in the future","why glass will be used in the future"]$c$::jsonb, 2, 6),
('4a7 - Main Idea','G4', $p$While a lion's roar might be frightening, it is his forelegs that are dangerous. His large forelegs measure over a foot around. The lion's large paws have sharp claws. With just one blow of his powerful leg, he can break the neck of a small animal.  This story mainly tells:$p$, $c$["why a lion's roar is frightening","why lions have sharp claws","how lions treat small animals","how powerful lions' forelegs are"]$c$::jsonb, 3, 7),
('4a7 - Main Idea','G4', $p$Diamonds are often worth a lot of money. Just how much money a diamond is worth depends on many things. It doesn't depend only on its size. It also depends on its color, hardness, brilliance, the family from which it comes, and how well it was cut.  This story mainly tells:$p$, $c$["why diamonds should be cut well","why color is important","why people buy diamonds","factors that make diamonds valuable"]$c$::jsonb, 3, 8),
('4a7 - Main Idea','G4', $p$When we think of salt water, we think of the world's oceans and seas. When we think of fresh water, we think of ponds, lakes, rivers, and streams. Yet, a large amount of fresh water is often found at certain places in the sea.  This story mainly tells:$p$, $c$["why fresh water is found in rivers","where fresh water and salt water are found","how much salt water there is in the world","how salt water became salty"]$c$::jsonb, 1, 9),
('4a7 - Main Idea','G4', $p$The bald eagle is known to make very large nests. One nest found in Ohio was twelve feet deep. It was over eight feet across. The nest weighed as much as an automobile. A bald eagle's nest that was found in Florida was even larger than the one in Ohio.  This story mainly tells:$p$, $c$["what bald eagles use to make their nests","what a nest is like","how big bald eagles' nests are","why bald eagles make nests"]$c$::jsonb, 2, 10);

-- ---- 4a8  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a8 - Main Idea','G4', $p$The next time you are at the seashore, look for turtlegrass. In turtlegrass you are likely to find the great conches, giant starfish, sea horses, and green spider crabs. You may even see a young octopus or a sea turtle.  This story mainly tells:$p$, $c$["what is found in turtlegrass","how to grow turtlegrass","where turtlegrass is found","why we have turtlegrass"]$c$::jsonb, 0, 1),
('4a8 - Main Idea','G4', $p$Without water in the air, we couldn't stand the heat of the sun during the day. The water in the air also helps the earth keep some of the sun's warmth for the night. Without water in the air, our days would be too hot and our nights too cold.  This story mainly tells:$p$, $c$["why nights grow cold","where water is found","where water comes from","how water in the air helps us"]$c$::jsonb, 3, 2),
('4a8 - Main Idea','G4', $p$If something happens "once in a blue moon," it doesn't happen very often. Usually, we don't see too many blue moons - only after a volcanic explosion or some unusual change in the air. So, "once in a blue moon" means not happening very often.  This story mainly tells:$p$, $c$["why the moon is sometimes blue","what \"once in a blue moon\" means","where to find a blue moon","what it means when the moon is blue"]$c$::jsonb, 1, 3),
('4a8 - Main Idea','G4', $p$Crocodiles have many enemies. Lizards eat them. So do hippopotamuses. People hunt crocodiles for their valuable skin. Little crocodiles need to be aware of grown-up crocodiles too, especially male crocodiles. A hungry male may even eat its own young.  This story mainly tells:$p$, $c$["why crocodiles have enemies","why male crocodiles are dangerous","how crocodiles survive","what the different enemies of crocodiles are"]$c$::jsonb, 3, 4),
('4a8 - Main Idea','G4', $p$The word hippopotamus means horse river. It comes from two Greek words. In Greek the word for horse is hippos. Potamos is a Greek word for river. While the hippo might not look much like a horse, it does spend a lot of time in rivers.  This story mainly tells:$p$, $c$["why a hippo looks like a horse","what hippopotamus means","where the hippo lives","why hippopotamuses spend time in the river"]$c$::jsonb, 1, 5),
('4a8 - Main Idea','G4', $p$Some spiders go fishing when they get hungry. The fisher spider climbs down plant stems into the water. The spider injects its powerful poison into the fish and drags it up on land, where it then eats the fish.  This story mainly tells:$p$, $c$["how fisher spiders catch fish","how fisher spiders climb down plants","how fisher spiders use their legs","why fisher spiders have poison"]$c$::jsonb, 0, 6),
('4a8 - Main Idea','G4', $p$Oil has had a long history - and not just as fuel! One American, Samuel Kier, put oil in bottles. He sold his "Kier's Rock Oil" as a cure for many kinds of sicknesses. People drank it to get rid of stomachaches!  This story mainly tells:$p$, $c$["why Samuel Kier became rich","how oil was once used","how much fuel is used every year","where oil was first found"]$c$::jsonb, 1, 7),
('4a8 - Main Idea','G4', $p$Even Indians were afraid of some things. Some tribes were afraid of the dead. Other tribes were afraid of killing snakes. Owls were believed to have the power of witches. Long ago, Indians believed that spirits lived all around them: in the trees, in the water, in the animals, and in everything.  This story mainly tells:$p$, $c$["what power owls have","what Indians feared and believed","why some Indians feared the dead","why spirits lived in everything"]$c$::jsonb, 1, 8),
('4a8 - Main Idea','G4', $p$Indians sometimes used fire to help kill buffalo. When buffalo were sighted in grassy fields, the Indians would circle around them and set the grass on fire. The frightened buffalo were trapped inside the ring of flames. They ran in circles until Indian arrows killed them.  This story mainly tells:$p$, $c$["why Indians killed buffalo","how buffalo burned to death","what buffalo do","how Indians trapped and killed buffalo"]$c$::jsonb, 3, 9),
('4a8 - Main Idea','G4', $p$Tigers eat wild pigs. They also eat deer, cattle, and young buffalo. Some tigers eat men. Man-eating tigers are usually old tigers that find it easier to kill people than to kill cattle. Most of the time, tigers go out hunting for food at night.  This story mainly tells:$p$, $c$["when tigers hunt for food","why tigers eat deer","what tigers eat","when tigers eat"]$c$::jsonb, 2, 10);

-- ---- 4a9  Sequence ------------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a9 - Sequence','G4', $p$Choose the best order. A. Glass manufacturers have come up with an answer to this problem. B. The use of this glass in automobiles is expected to save many lives. C. Shattered glass has caused many injuries and deaths. D. They have developed windshields that do not cut even when shattered.$p$, $c$["C-B-D-A","C-A-B-D","C-A-D-B","B-A-C-D"]$c$::jsonb, 2, 1),
('4a9 - Sequence','G4', $p$Choose the best order. A. You don't need oil either. Bicycles can be driven on very narrow paths. B. That isn't true of automobiles. C. It is also easier to maintain. You don't need to buy gasoline for a bicycle. D. A bicycle costs much less than an automobile.$p$, $c$["D-B-C-A","C-A-B-D","D-C-A-B","D-A-B-C"]$c$::jsonb, 2, 2),
('4a9 - Sequence','G4', $p$Choose the best order. A. This piece of land on which a house is built is called a lot. B. If a person wants to build a house, he must choose a place to build it. C. The plans show the number of rooms and the size of the rooms. D. Then, he must talk to an architect. An architect draws plans for houses.$p$, $c$["C-A-D-B","C-B-A-D","B-C-D-A","B-A-D-C"]$c$::jsonb, 3, 3),
('4a9 - Sequence','G4', $p$Choose the best order. A. You read the letters on the chart with only one eye at a time. B. Have you ever used the Snellen Chart to test your eyes? C. If you can read the letters on the eighth line down from the top, standing twenty feet from the chart, you are said to have 20/20 vision. D. You can see at twenty feet what most people can see at the same distance.$p$, $c$["B-D-A-C","B-A-C-D","C-D-B-A","C-A-B-D"]$c$::jsonb, 1, 4),
('4a9 - Sequence','G4', $p$Choose the best order. A. Near the end of the Civil War, more soldiers were needed by the Union Army. B. They were called "three-hundred-dollar men." C. Therefore, some men were given three hundred dollars to enlist. D. This name was given to them by other soldiers who had enlisted at the beginning of the Civil War without getting extra money.$p$, $c$["A-B-C-D","C-A-B-D","A-C-B-D","D-B-A-C"]$c$::jsonb, 2, 5),
('4a9 - Sequence','G4', $p$Choose the best order. A. Postage had to be paid by the person who received the letter. B. People didn't like to pay for letters that they didn't want. Sometimes, they wouldn't accept the letter. C. Long ago, people who sent letters didn't have to pay postage. D. Thus, it happened that the sender had to pay the postage.$p$, $c$["B-A-D-C","A-C-B-D","C-A-B-D","C-B-A-D"]$c$::jsonb, 2, 6);

-- ---- 4a10  Sequence -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a10 - Sequence','G4', $p$Choose the best order. A. The "pillow of air" is much softer than the window or dashboard. B. An air bag pops out and pins the driver and passengers to their seats. C. Something new has been invented to save the lives of people in automobile accidents. D. The system is completely automatic. The air bag inflates almost immediately upon impact and then deflates a few seconds later.$p$, $c$["C-B-D-A","B-D-C-A","A-B-D-C","B-D-A-C"]$c$::jsonb, 0, 1),
('4a10 - Sequence','G4', $p$Choose the best order. A. The last Indian in the line had to wipe out the prints. B. Then, there was no record of the number of people who had passed by. C. To walk Indian file means to walk behind the other in a line. D. When Indians walked in this manner, they stepped carefully into the footprints of the person in front.$p$, $c$["D-B-A-C","C-A-B-D","C-D-A-B","D-A-C-B"]$c$::jsonb, 2, 2),
('4a10 - Sequence','G4', $p$Choose the best order. A. When eating, Tuareg men hold the veil out with one hand and pass the food up under it with the other. B. No Tuareg man is supposed to show any part of his face except his eyes. C. It is the men, not the women, of this desert tribe who wear veils over their faces. D. Deep in the Sahara Desert live the strange Tuaregs.$p$, $c$["D-C-B-A","A-B-D-C","D-A-C-B","A-C-D-B"]$c$::jsonb, 0, 3),
('4a10 - Sequence','G4', $p$Choose the best order. A. He thinks carefully and writes two thoughtful letters. He mails them. B. Jim is very worried about the world. He doesn't know why the people in charge can't stop arguing over this country or that country. C. "I hope they listen," he thinks as the envelopes disappear into the big blue mailbox. D. He decides to write letters to the President of the United States and the leader in Russia.$p$, $c$["C-B-D-A","B-D-A-C","A-C-D-B","B-A-D-C"]$c$::jsonb, 1, 4),
('4a10 - Sequence','G4', $p$Choose the best order. A. First, anger became angry, with the e dropped. B. For example, angrily started out as anger. C. Then, -ly was added, and the y in angry changed to i. D. In some words, you can see that two changes have taken place.$p$, $c$["D-B-A-C","A-B-C-D","D-B-C-A","D-A-C-B"]$c$::jsonb, 0, 5),
('4a10 - Sequence','G4', $p$Choose the best order. A. All the rivers on one side of the ridge flow to the east. B. The peaks of the Rocky Mountains form a dividing line on the North American continent. C. This ridge is called the Continental Divide. D. On the other side of the ridge, the rivers flow to the west.$p$, $c$["B-C-A-D","A-C-B-D","A-B-D-C","B-A-D-C"]$c$::jsonb, 0, 6);

-- ---- 4a11  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a11 - Inference','G4', $p$Jacob follows his routine. He always does the same thing in the same way every day. For example, when Jacob gets the newspaper, everyone can hear him laughing within five minutes. Which is probably true?$p$, $c$["The delivery person told Jacob jokes.","Jacob was happy that the newspaper arrived.","Jacob always reads the comics first.","Jacob teased everyone."]$c$::jsonb, 2, 1),
('4a11 - Inference','G4', $p$Angela got a big cut on her finger. She had been playing with an old tin can. She ran into the house to get her mother. Which is probably true?$p$, $c$["Angela wanted her mom to take care of the cut.","Angela's mom would get really angry.","Angela was making something with the old tin can.","Angela tripped and fell on the old tin can."]$c$::jsonb, 0, 2),
('4a11 - Inference','G4', $p$Steve tiptoed past his dad. His dad was on the sofa with his eyes closed. Later, Steve's mom asked his dad, "Where is Steve?" His dad said, "Oh, he went out." Which is probably true?$p$, $c$["Steve's mom was calling Steve for dinner.","Steve feared his dad.","Steve's dad wasn't asleep.","Steve's dad loved to watch football on television."]$c$::jsonb, 2, 3),
('4a11 - Inference','G4', $p$Paul found an envelope with a lot of money in it. He took it to the police station. Several days later, Paul met Mr. Simms, who gave him a reward. Which is probably true?$p$, $c$["Mr. Simms gave Paul fifty dollars.","Paul was aware of the reward.","The money in the envelope belonged to Mr. Simms.","Mr. Simms was at the police station."]$c$::jsonb, 2, 4),
('4a11 - Inference','G4', $p$William woke up and remembered fighting dragons and hunting for gold the night before. He put on his robe and went downstairs for some cereal. Which is probably true?$p$, $c$["William went out to locate the gold.","William was late for school.","William just woke up from a dream.","William was the warrior."]$c$::jsonb, 2, 5);

-- ---- 4a12  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('4a12 - Inference','G4', $p$Rebecca asked, "Do you still want to play basketball against Adam?" James replied, "Yes." Rebecca asked, "Did you see that slam dunk Adam did yesterday?" "Yes," James said, "I would still like to play even if we don't win." Which is probably true?$p$, $c$["Adam is in the same team with Rebecca and James.","Adam is six feet tall.","Adam always beats Rebecca and James at basketball.","Adam only wants to win."]$c$::jsonb, 2, 1),
('4a12 - Inference','G4', $p$Some birds had been eating the berries in Ms. Smith's garden. Ms. Smith set up a scarecrow in the garden. The birds didn't come back. Which is probably true?$p$, $c$["The birds devoured all of her berries.","Ms. Smith wanted the birds to eat her berries.","Ms. Smith lured the birds and trapped them.","The scarecrow kept the birds away."]$c$::jsonb, 3, 2),
('4a12 - Inference','G4', $p$Three boys were taking a shortcut through Mr. Rivera's farm. The boys suddenly saw a horse coming right at them! Pat ran and jumped over the fence. It took a while for the others to catch up with him. They were all safe once they were on the other side of the fence. Which is probably true?$p$, $c$["The horse jumped over the fence.","The fence was made of wood.","Pat dashed away faster than the rest of the boys.","Mr. Rivera became furious because of the boys."]$c$::jsonb, 2, 3),
('4a12 - Inference','G4', $p$Jennifer was angry today. Last night's weather report said that it would rain today. So Jennifer had canceled her plans to go to the beach with her friends. Which is probably true?$p$, $c$["Jennifer's friends dumped her.","The weatherman was incorrect.","Jennifer did not want to go to the beach with her friends.","Jennifer scorned the sun."]$c$::jsonb, 1, 4),
('4a12 - Inference','G4', $p$The invitation said that the play would begin at 3:00 P.M. The third grade class was eager to start the play. Ms. Jones, their teacher, said, "Get ready kids. You go on in fifteen minutes." Which is probably true?$p$, $c$["The third grade class is watching the play.","It was about 2:45 P.M.","The parents were not there yet.","Ms. Jones demanded the children memorize their lines right before the play began."]$c$::jsonb, 1, 5);
