-- ============================================================================
-- Duke College — question bank: The Learning Gate, Reading Skill (LG-R-RS-6a)
-- 12 worksheets / 140 questions. Run AFTER setup.sql. Adds questions only.
-- correct_index is 0-based. Answers were generated for you; please spot-check.
-- ============================================================================

-- ---- 6a1  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a1 - Context Clue','G6', $p$Choose the best word for blank (1): Chinatown is high on the sightseeing list of (1)___ in San Francisco and New York. The word brings to mind strange, (2)___ Chinese foods, such as shark's fin soup. It also (3)___ tiny shops crowded with expensive (4)___ treasures and cheap souvenirs. In the last part of the 19th century there were Chinese communities in small cities all along the West coast. Today, Chinatowns have (5)___ from all except our largest cities.$p$, $c$["mayors","tourists","residents","employees"]$c$::jsonb, 1, 1),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (2): Chinatown is high on the sightseeing list of (1)___ in San Francisco and New York. The word brings to mind strange, (2)___ Chinese foods, such as shark's fin soup. It also (3)___ tiny shops crowded with expensive (4)___ treasures and cheap souvenirs. In the last part of the 19th century there were Chinese communities in small cities all along the West coast. Today, Chinatowns have (5)___ from all except our largest cities.$p$, $c$["acceptable","decimal","exotic","numerous"]$c$::jsonb, 2, 2),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (3): Chinatown is high on the sightseeing list of (1)___ in San Francisco and New York. The word brings to mind strange, (2)___ Chinese foods, such as shark's fin soup. It also (3)___ tiny shops crowded with expensive (4)___ treasures and cheap souvenirs. In the last part of the 19th century there were Chinese communities in small cities all along the West coast. Today, Chinatowns have (5)___ from all except our largest cities.$p$, $c$["communicates","suggests","estimates","governs"]$c$::jsonb, 1, 3),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (4): Chinatown is high on the sightseeing list of (1)___ in San Francisco and New York. The word brings to mind strange, (2)___ Chinese foods, such as shark's fin soup. It also (3)___ tiny shops crowded with expensive (4)___ treasures and cheap souvenirs. In the last part of the 19th century there were Chinese communities in small cities all along the West coast. Today, Chinatowns have (5)___ from all except our largest cities.$p$, $c$["oriental","original","useful","ordinary"]$c$::jsonb, 0, 4),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (5): Chinatown is high on the sightseeing list of (1)___ in San Francisco and New York. The word brings to mind strange, (2)___ Chinese foods, such as shark's fin soup. It also (3)___ tiny shops crowded with expensive (4)___ treasures and cheap souvenirs. In the last part of the 19th century there were Chinese communities in small cities all along the West coast. Today, Chinatowns have (5)___ from all except our largest cities.$p$, $c$["erected","matured","opposed","disappeared"]$c$::jsonb, 3, 5),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (6): 1846 was a terrible year for Ireland. An unknown disease had destroyed the country's chief crop, the potato. Without potatoes, the people could not live. Hundreds of thousands of them (6)___ to death, while millions of others were (7)___ to leave farms that were now (8)___. A typhus epidemic struck the next year. This dreaded disease (9)___ to kill off those who had managed to survive the potato (10)___.$p$, $c$["swelled","starved","celebrated","feared"]$c$::jsonb, 1, 6),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (7): 1846 was a terrible year for Ireland. An unknown disease had destroyed the country's chief crop, the potato. Without potatoes, the people could not live. Hundreds of thousands of them (6)___ to death, while millions of others were (7)___ to leave farms that were now (8)___. A typhus epidemic struck the next year. This dreaded disease (9)___ to kill off those who had managed to survive the potato (10)___.$p$, $c$["forbidden","authorized","forced","imitated"]$c$::jsonb, 2, 7),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (8): 1846 was a terrible year for Ireland. An unknown disease had destroyed the country's chief crop, the potato. Without potatoes, the people could not live. Hundreds of thousands of them (6)___ to death, while millions of others were (7)___ to leave farms that were now (8)___. A typhus epidemic struck the next year. This dreaded disease (9)___ to kill off those who had managed to survive the potato (10)___.$p$, $c$["abundant","expanding","useless","cities"]$c$::jsonb, 2, 8),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (9): 1846 was a terrible year for Ireland. An unknown disease had destroyed the country's chief crop, the potato. Without potatoes, the people could not live. Hundreds of thousands of them (6)___ to death, while millions of others were (7)___ to leave farms that were now (8)___. A typhus epidemic struck the next year. This dreaded disease (9)___ to kill off those who had managed to survive the potato (10)___.$p$, $c$["communicated","promised","threatened","decided"]$c$::jsonb, 2, 9),
('6a1 - Context Clue','G6', $p$Choose the best word for blank (10): 1846 was a terrible year for Ireland. An unknown disease had destroyed the country's chief crop, the potato. Without potatoes, the people could not live. Hundreds of thousands of them (6)___ to death, while millions of others were (7)___ to leave farms that were now (8)___. A typhus epidemic struck the next year. This dreaded disease (9)___ to kill off those who had managed to survive the potato (10)___.$p$, $c$["pollution","famine","persecution","factory"]$c$::jsonb, 1, 10),
('6a1 - Context Clue','G6', $p$The streets of Manhattan are crowded with sightseeing ______.$p$, $c$["tourists","suggestions","disappearances","buildings"]$c$::jsonb, 0, 11),
('6a1 - Context Clue','G6', $p$______ foods originate from countries in Asia.$p$, $c$["Eating","Suggested","Tourist","Oriental"]$c$::jsonb, 3, 12),
('6a1 - Context Clue','G6', $p$The color red ______ warmth.$p$, $c$["disappears","suggests","organizes","orders"]$c$::jsonb, 1, 13),
('6a1 - Context Clue','G6', $p$Many strange and ______ animals live in Africa.$p$, $c$["oriental","slow","disappeared","exotic"]$c$::jsonb, 3, 14),
('6a1 - Context Clue','G6', $p$The convicts' effort to escape proved to be ______ because they were recaptured.$p$, $c$["forced","starved","threatened","useless"]$c$::jsonb, 3, 15),
('6a1 - Context Clue','G6', $p$Children in Somalia were ______ because of the famine and the civil war.$p$, $c$["useless","starved","threatened","forced"]$c$::jsonb, 1, 16),
('6a1 - Context Clue','G6', $p$The animals were ______ to do unnatural tricks.$p$, $c$["useless","forced","famine","followed"]$c$::jsonb, 1, 17),
('6a1 - Context Clue','G6', $p$The small child ______ in the large crowd.$p$, $c$["suggested","smelled","overcome","disappeared"]$c$::jsonb, 3, 18),
('6a1 - Context Clue','G6', $p$The guerillas ______ to overthrow the government.$p$, $c$["threatened","starved","useless","decked"]$c$::jsonb, 0, 19),
('6a1 - Context Clue','G6', $p$______ wiped out the crops and dried up the lands.$p$, $c$["Threats","Starvation","Famine","Forms"]$c$::jsonb, 2, 20);

-- ---- 6a2  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a2 - Context Clue','G6', $p$Choose the best word for blank (1): Ancient wars fought 2,000 years ago were just as (1)___ as they are today. Ancient soldiers had no guns or (2)___. However, they had other kinds of (3)___. Roman war machines were able to throw a 50-lb. stone a quarter of a mile. This huge stone was fired over a town's wall and (4)___ any man, woman, or child that it hit. The Roman army was well trained, and succeeded in (5)___ much of the world.$p$, $c$["political","quaint","deadly","mechanical"]$c$::jsonb, 2, 1),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (2): Ancient wars fought 2,000 years ago were just as (1)___ as they are today. Ancient soldiers had no guns or (2)___. However, they had other kinds of (3)___. Roman war machines were able to throw a 50-lb. stone a quarter of a mile. This huge stone was fired over a town's wall and (4)___ any man, woman, or child that it hit. The Roman army was well trained, and succeeded in (5)___ much of the world.$p$, $c$["incomes","occupations","physicians","explosives"]$c$::jsonb, 3, 2),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (3): Ancient wars fought 2,000 years ago were just as (1)___ as they are today. Ancient soldiers had no guns or (2)___. However, they had other kinds of (3)___. Roman war machines were able to throw a 50-lb. stone a quarter of a mile. This huge stone was fired over a town's wall and (4)___ any man, woman, or child that it hit. The Roman army was well trained, and succeeded in (5)___ much of the world.$p$, $c$["documents","radars","knives","weapons"]$c$::jsonb, 3, 3),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (4): Ancient wars fought 2,000 years ago were just as (1)___ as they are today. Ancient soldiers had no guns or (2)___. However, they had other kinds of (3)___. Roman war machines were able to throw a 50-lb. stone a quarter of a mile. This huge stone was fired over a town's wall and (4)___ any man, woman, or child that it hit. The Roman army was well trained, and succeeded in (5)___ much of the world.$p$, $c$["assisted","crushed","decayed","stabbed"]$c$::jsonb, 1, 4),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (5): Ancient wars fought 2,000 years ago were just as (1)___ as they are today. Ancient soldiers had no guns or (2)___. However, they had other kinds of (3)___. Roman war machines were able to throw a 50-lb. stone a quarter of a mile. This huge stone was fired over a town's wall and (4)___ any man, woman, or child that it hit. The Roman army was well trained, and succeeded in (5)___ much of the world.$p$, $c$["convincing","conquering","convicting","contaminating"]$c$::jsonb, 1, 5),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (6): The temperature in Colorado (6)___ greatly from one part to another. This is because of Colorado's varying (7)___ and its inland location. Colorado has a very high percentage of dry, clear, sunny days. One can count on low (8)___ and a visible sun for about 295 days a year. Since there is little rain, Colorado depends on the melting snow from the mountains to (9)___ the streams and rivers that feed the (10)___ ditches.$p$, $c$["stimulates","travels","flocks","varies"]$c$::jsonb, 3, 6),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (7): The temperature in Colorado (6)___ greatly from one part to another. This is because of Colorado's varying (7)___ and its inland location. Colorado has a very high percentage of dry, clear, sunny days. One can count on low (8)___ and a visible sun for about 295 days a year. Since there is little rain, Colorado depends on the melting snow from the mountains to (9)___ the streams and rivers that feed the (10)___ ditches.$p$, $c$["altitudes","forests","streams","oceans"]$c$::jsonb, 0, 7),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (8): The temperature in Colorado (6)___ greatly from one part to another. This is because of Colorado's varying (7)___ and its inland location. Colorado has a very high percentage of dry, clear, sunny days. One can count on low (8)___ and a visible sun for about 295 days a year. Since there is little rain, Colorado depends on the melting snow from the mountains to (9)___ the streams and rivers that feed the (10)___ ditches.$p$, $c$["hail","tornadoes","meteors","humidity"]$c$::jsonb, 3, 8),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (9): The temperature in Colorado (6)___ greatly from one part to another. This is because of Colorado's varying (7)___ and its inland location. Colorado has a very high percentage of dry, clear, sunny days. One can count on low (8)___ and a visible sun for about 295 days a year. Since there is little rain, Colorado depends on the melting snow from the mountains to (9)___ the streams and rivers that feed the (10)___ ditches.$p$, $c$["drain","poison","provide","construct"]$c$::jsonb, 2, 9),
('6a2 - Context Clue','G6', $p$Choose the best word for blank (10): The temperature in Colorado (6)___ greatly from one part to another. This is because of Colorado's varying (7)___ and its inland location. Colorado has a very high percentage of dry, clear, sunny days. One can count on low (8)___ and a visible sun for about 295 days a year. Since there is little rain, Colorado depends on the melting snow from the mountains to (9)___ the streams and rivers that feed the (10)___ ditches.$p$, $c$["flood","apple","highway","irrigation"]$c$::jsonb, 3, 10),
('6a2 - Context Clue','G6', $p$Parents ______ protection and necessities for their children.$p$, $c$["irrigate","provide","vary","hunger"]$c$::jsonb, 1, 11),
('6a2 - Context Clue','G6', $p$The construction workers used ______ to demolish the building.$p$, $c$["weapons","explosives","conquering","concretes"]$c$::jsonb, 1, 12),
('6a2 - Context Clue','G6', $p$The soldiers used different types of ______ during the war.$p$, $c$["deaths","minerals","fuels","weapons"]$c$::jsonb, 3, 13),
('6a2 - Context Clue','G6', $p$The extreme ______ of the Himalayas are famous.$p$, $c$["humidity","airs","altitudes","irrigation"]$c$::jsonb, 2, 14),
('6a2 - Context Clue','G6', $p$After ______ the small army, the general and his soldiers claimed victory.$p$, $c$["examining","detaching","conquering","delivering"]$c$::jsonb, 2, 15),
('6a2 - Context Clue','G6', $p$Cultures ______ from one country to another.$p$, $c$["provide","irrigate","vary","humiliate"]$c$::jsonb, 2, 16),
('6a2 - Context Clue','G6', $p$I ______ the shell of the walnut with my nutcracker.$p$, $c$["conquered","exploded","crushed","killed"]$c$::jsonb, 2, 17),
('6a2 - Context Clue','G6', $p$The ______ in the air made us feel very sticky.$p$, $c$["humidity","altitudes","irrigation","variations"]$c$::jsonb, 0, 18),
('6a2 - Context Clue','G6', $p$A snake's venom can be quite ______.$p$, $c$["explosive","deadly","crushing","weak"]$c$::jsonb, 1, 19),
('6a2 - Context Clue','G6', $p$______ helps water crops.$p$, $c$["Altitudes","Provision","Irrigation","Humidity"]$c$::jsonb, 2, 20);

-- ---- 6a3  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a3 - Context Clue','G6', $p$Choose the best word for blank (1): Esperanto is an artificial (1)___ that was devised by Dr. Ludwig Zamenhof of Poland in 1887. By creating a very simple language that can be easily learned, Dr. Zamenhof hoped to (2)___ antagonism among nations by improving communication. He wanted people throughout the world to be able to (3)___ with each other by (4)___ learning one language in addition to their own. Each word is (5)___ exactly the way it is spelled.$p$, $c$["language","limb","chemical","cyclone"]$c$::jsonb, 0, 1),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (2): Esperanto is an artificial (1)___ that was devised by Dr. Ludwig Zamenhof of Poland in 1887. By creating a very simple language that can be easily learned, Dr. Zamenhof hoped to (2)___ antagonism among nations by improving communication. He wanted people throughout the world to be able to (3)___ with each other by (4)___ learning one language in addition to their own. Each word is (5)___ exactly the way it is spelled.$p$, $c$["dedicate","eliminate","assemble","assist"]$c$::jsonb, 1, 2),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (3): Esperanto is an artificial (1)___ that was devised by Dr. Ludwig Zamenhof of Poland in 1887. By creating a very simple language that can be easily learned, Dr. Zamenhof hoped to (2)___ antagonism among nations by improving communication. He wanted people throughout the world to be able to (3)___ with each other by (4)___ learning one language in addition to their own. Each word is (5)___ exactly the way it is spelled.$p$, $c$["communicate","understand","alert","engage"]$c$::jsonb, 0, 3),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (4): Esperanto is an artificial (1)___ that was devised by Dr. Ludwig Zamenhof of Poland in 1887. By creating a very simple language that can be easily learned, Dr. Zamenhof hoped to (2)___ antagonism among nations by improving communication. He wanted people throughout the world to be able to (3)___ with each other by (4)___ learning one language in addition to their own. Each word is (5)___ exactly the way it is spelled.$p$, $c$["heavily","quickly","secretly","merely"]$c$::jsonb, 3, 4),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (5): Esperanto is an artificial (1)___ that was devised by Dr. Ludwig Zamenhof of Poland in 1887. By creating a very simple language that can be easily learned, Dr. Zamenhof hoped to (2)___ antagonism among nations by improving communication. He wanted people throughout the world to be able to (3)___ with each other by (4)___ learning one language in addition to their own. Each word is (5)___ exactly the way it is spelled.$p$, $c$["performed","pronounced","phrased","pulsed"]$c$::jsonb, 1, 5),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (6): The early development of (6)___ facilities aided the development of agriculture. The opening of the Erie Canal (7)___ the farmer to get his crops to the big eastern (8)___. Later on, the development of the railroad and the roads gave the farmer additional (9)___ in marketing his crops and livestock. Dairying and cattle raising soon developed into the most important sources of farm (10)___.$p$, $c$["restroom","school","transportation","library"]$c$::jsonb, 2, 6),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (7): The early development of (6)___ facilities aided the development of agriculture. The opening of the Erie Canal (7)___ the farmer to get his crops to the big eastern (8)___. Later on, the development of the railroad and the roads gave the farmer additional (9)___ in marketing his crops and livestock. Dairying and cattle raising soon developed into the most important sources of farm (10)___.$p$, $c$["excited","explained","enabled","examined"]$c$::jsonb, 2, 7),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (8): The early development of (6)___ facilities aided the development of agriculture. The opening of the Erie Canal (7)___ the farmer to get his crops to the big eastern (8)___. Later on, the development of the railroad and the roads gave the farmer additional (9)___ in marketing his crops and livestock. Dairying and cattle raising soon developed into the most important sources of farm (10)___.$p$, $c$["sunrise","mythology","markets","mountains"]$c$::jsonb, 2, 8),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (9): The early development of (6)___ facilities aided the development of agriculture. The opening of the Erie Canal (7)___ the farmer to get his crops to the big eastern (8)___. Later on, the development of the railroad and the roads gave the farmer additional (9)___ in marketing his crops and livestock. Dairying and cattle raising soon developed into the most important sources of farm (10)___.$p$, $c$["adventures","advantages","advertisements","advices"]$c$::jsonb, 1, 9),
('6a3 - Context Clue','G6', $p$Choose the best word for blank (10): The early development of (6)___ facilities aided the development of agriculture. The opening of the Erie Canal (7)___ the farmer to get his crops to the big eastern (8)___. Later on, the development of the railroad and the roads gave the farmer additional (9)___ in marketing his crops and livestock. Dairying and cattle raising soon developed into the most important sources of farm (10)___.$p$, $c$["income","animals","instruments","irrigation"]$c$::jsonb, 0, 10),
('6a3 - Context Clue','G6', $p$______ are places where merchandise is sold.$p$, $c$["Advantages","Incomes","Committees","Markets"]$c$::jsonb, 3, 11),
('6a3 - Context Clue','G6', $p$The city is trying to ______ pollution.$p$, $c$["communicate","eliminate","pronounce","memorize"]$c$::jsonb, 1, 12),
('6a3 - Context Clue','G6', $p$Language ______ us to communicate with one another.$p$, $c$["marketed","enables","transported","advertised"]$c$::jsonb, 1, 13),
('6a3 - Context Clue','G6', $p$We will not do well on our exam by ______ memorizing the material; we must study and comprehend it as well.$p$, $c$["merely","eliminating","pronouncing","communicating"]$c$::jsonb, 0, 14),
('6a3 - Context Clue','G6', $p$The foreigner ______ certain words differently.$p$, $c$["pronounced","eliminated","planned","complained"]$c$::jsonb, 0, 15),
('6a3 - Context Clue','G6', $p$The tourists traveled around Manhattan using public ______.$p$, $c$["market","advantage","income","transportation"]$c$::jsonb, 3, 16),
('6a3 - Context Clue','G6', $p$People ______ by speaking or writing.$p$, $c$["pronounce","communicate","eliminate","suspend"]$c$::jsonb, 1, 17),
('6a3 - Context Clue','G6', $p$Spanish is the ______ spoken in Spain.$p$, $c$["pronunciation","elimination","mere","language"]$c$::jsonb, 3, 18),
('6a3 - Context Clue','G6', $p$The ______ of rainfall is that it usually ensures a plentiful crop.$p$, $c$["market","advantage","enable","income"]$c$::jsonb, 1, 19),
('6a3 - Context Clue','G6', $p$People get ______ from working.$p$, $c$["market","income","transportation","enable"]$c$::jsonb, 1, 20);

-- ---- 6a4  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a4 - Context Clue','G6', $p$Choose the best word for blank (1): Few plant foods are as (1)___ as the coconut. Not only does it provide meat and drink, but it also (2)___ oils that are used in cooking. The coconut is also used in (3)___ butter as well as custard pies and coconut sugar. Now modern science has found even more uses for the (4)___ coconut. They can make synthetic rubber and brake fluids for (5)___ from it.$p$, $c$["versatile","professional","elementary","fragrant"]$c$::jsonb, 0, 1),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (2): Few plant foods are as (1)___ as the coconut. Not only does it provide meat and drink, but it also (2)___ oils that are used in cooking. The coconut is also used in (3)___ butter as well as custard pies and coconut sugar. Now modern science has found even more uses for the (4)___ coconut. They can make synthetic rubber and brake fluids for (5)___ from it.$p$, $c$["boosts","hinders","absorbs","contains"]$c$::jsonb, 3, 2),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (3): Few plant foods are as (1)___ as the coconut. Not only does it provide meat and drink, but it also (2)___ oils that are used in cooking. The coconut is also used in (3)___ butter as well as custard pies and coconut sugar. Now modern science has found even more uses for the (4)___ coconut. They can make synthetic rubber and brake fluids for (5)___ from it.$p$, $c$["slippery","synthetic","hazel","mature"]$c$::jsonb, 1, 3),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (4): Few plant foods are as (1)___ as the coconut. Not only does it provide meat and drink, but it also (2)___ oils that are used in cooking. The coconut is also used in (3)___ butter as well as custard pies and coconut sugar. Now modern science has found even more uses for the (4)___ coconut. They can make synthetic rubber and brake fluids for (5)___ from it.$p$, $c$["ideal","amazing","permanent","grizzly"]$c$::jsonb, 1, 4),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (5): Few plant foods are as (1)___ as the coconut. Not only does it provide meat and drink, but it also (2)___ oils that are used in cooking. The coconut is also used in (3)___ butter as well as custard pies and coconut sugar. Now modern science has found even more uses for the (4)___ coconut. They can make synthetic rubber and brake fluids for (5)___ from it.$p$, $c$["carriages","boats","trains","automobiles"]$c$::jsonb, 3, 5),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (6): Metal workers need to know how metals will act when they work with them. They need to know (6)___ they are malleable (capable of being shaped by (7)___), whether they are ductile (capable of being hammered or (8)___ thin without breaking), and whether they will (9)___ tension (pulling) and torsion (twisting). These (10)___ are called physical properties of metal.$p$, $c$["whether","either","neither","never"]$c$::jsonb, 0, 6),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (7): Metal workers need to know how metals will act when they work with them. They need to know (6)___ they are malleable (capable of being shaped by (7)___), whether they are ductile (capable of being hammered or (8)___ thin without breaking), and whether they will (9)___ tension (pulling) and torsion (twisting). These (10)___ are called physical properties of metal.$p$, $c$["picking","cutting","shattering","pounding"]$c$::jsonb, 3, 7),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (8): Metal workers need to know how metals will act when they work with them. They need to know (6)___ they are malleable (capable of being shaped by (7)___), whether they are ductile (capable of being hammered or (8)___ thin without breaking), and whether they will (9)___ tension (pulling) and torsion (twisting). These (10)___ are called physical properties of metal.$p$, $c$["painted","cut","drawn","carved"]$c$::jsonb, 2, 8),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (9): Metal workers need to know how metals will act when they work with them. They need to know (6)___ they are malleable (capable of being shaped by (7)___), whether they are ductile (capable of being hammered or (8)___ thin without breaking), and whether they will (9)___ tension (pulling) and torsion (twisting). These (10)___ are called physical properties of metal.$p$, $c$["control","produce","preserve","withstand"]$c$::jsonb, 3, 9),
('6a4 - Context Clue','G6', $p$Choose the best word for blank (10): Metal workers need to know how metals will act when they work with them. They need to know (6)___ they are malleable (capable of being shaped by (7)___), whether they are ductile (capable of being hammered or (8)___ thin without breaking), and whether they will (9)___ tension (pulling) and torsion (twisting). These (10)___ are called physical properties of metal.$p$, $c$["quantities","qualities","problems","props"]$c$::jsonb, 1, 10),
('6a4 - Context Clue','G6', $p$The ______ athlete was an expert in many sports.$p$, $c$["synthetic","versatile","containing","automatic"]$c$::jsonb, 1, 11),
('6a4 - Context Clue','G6', $p$Candy ______ sugar.$p$, $c$["amazes","devour","synthesize","contains"]$c$::jsonb, 3, 12),
('6a4 - Context Clue','G6', $p$The Egyptian pyramids are an ______ sight.$p$, $c$["versatile","synthetic","amazing","automobile"]$c$::jsonb, 2, 13),
('6a4 - Context Clue','G6', $p$______ gem stones are more affordable than genuine gems.$p$, $c$["Amazing","Versatile","Synthetic","Automobile"]$c$::jsonb, 2, 14),
('6a4 - Context Clue','G6', $p$Cars, trucks, and jeeps are ______.$p$, $c$["synthetic","deliberate","automobiles","verandas"]$c$::jsonb, 2, 15),
('6a4 - Context Clue','G6', $p$We must do our projects in class ______ or not the teacher is present.$p$, $c$["drawn","withstand","whether","claim"]$c$::jsonb, 2, 16),
('6a4 - Context Clue','G6', $p$Hammers were ______ on the metal.$p$, $c$["crafted","withstanding","qualifying","pounding"]$c$::jsonb, 3, 17),
('6a4 - Context Clue','G6', $p$Maple syrup is ______ from Ontario's maple trees.$p$, $c$["pounded","drawn","withstand","qualifying"]$c$::jsonb, 1, 18),
('6a4 - Context Clue','G6', $p$The buildings in San Francisco are designed to ______ earthquakes.$p$, $c$["drawn","eliminate","withstand","whether"]$c$::jsonb, 2, 19),
('6a4 - Context Clue','G6', $p$Mrs. Wilson always shops in stores that carry items of a very high ______.$p$, $c$["drawing","pound","problem","quality"]$c$::jsonb, 3, 20);

-- ---- 6a5  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a5 - Main Idea','G6', $p$Some older people wear bifocal glasses. They are called bifocal glasses because they enable the wearer to see objects both near and far away. If the wearer wishes to read, he uses the lower portion. For a distant object, he glances through the top.  This story mainly tells:$p$, $c$["who wears bifocals","what bifocals are","how to read up close","how to see far away"]$c$::jsonb, 1, 1),
('6a5 - Main Idea','G6', $p$The first thing you should carry with you when you travel outside your country is your passport. It is a form of request to a foreign country, allowing the bearer to travel through or stay within its territory. Governments issue this documentation to citizens who want to travel to foreign countries.  This story mainly tells:$p$, $c$["who issues a passport","why foreign countries require a passport","the use of a passport","how many passports are issued yearly"]$c$::jsonb, 2, 2),
('6a5 - Main Idea','G6', $p$Ergonomics is a new science that specializes in making offices more comfortable. Scientists are studying how furniture, machines, light, and colors affect people. If workers feel tired easily, they might need a more cheerful color of paint on their walls.  This story mainly tells:$p$, $c$["what color office walls should be painted","how Ergonomics came to be used in laboratories","how Ergonomics improves working environments","why our environment affects us"]$c$::jsonb, 2, 3),
('6a5 - Main Idea','G6', $p$Coin collecting is not only a great hobby, but also a great way to learn. Coins from foreign countries encourage the study of geography. Coins honoring famous people teach history. Collectors say that the knowledge and fun gained are of greater value than the actual coins themselves.  This story mainly tells:$p$, $c$["why coins are so popular","how collectors feel about their collections","the values of coin collecting","the value of a rare coin"]$c$::jsonb, 2, 4),
('6a5 - Main Idea','G6', $p$Cool jazz became popular after World War I. Cool jazz is complex, controlled and interesting to listen to. In contrast, hot jazz is more spirited, wild and suitable for dancing.  This story mainly tells:$p$, $c$["about the different types of jazz","why hot jazz is more spirited","why cool jazz became popular","who listens to jazz"]$c$::jsonb, 0, 5),
('6a5 - Main Idea','G6', $p$Jules Verne, one of the first writers of science fiction stories, foretold television a hundred years ago. He also foretold about the skyscrapers we see today. More remarkably, he predicted that the first trip to the moon would be from a launching site near the one actually used.  This story mainly tells:$p$, $c$["what Jules Verne has written","that Jules Verne incredibly foretold of many events","how Jules Verne knew about television","that skyscrapers have been around for hundreds of years"]$c$::jsonb, 1, 6),
('6a5 - Main Idea','G6', $p$A chicken cannon was developed to test the sturdiness of airplane windows. When the fast-moving airplanes fly through flocks of birds, the birds that hit the windows can make the window break and cause the plane to crash. A chicken cannon fires rubber chickens at the glass windshields. If the windshield doesn't break, it is presumed that the glass can withstand the force of a real crash.  This story mainly tells:$p$, $c$["how chicken cannons are used to test airplane windows","who came up with the chicken cannon","why birds damage windows","how many airplanes pass inspection"]$c$::jsonb, 0, 7),
('6a5 - Main Idea','G6', $p$The necktie makes a man look cool. A string worn around the throat was the first necktie. It was looped and drawn up under the chin, leaving the ends to fall free. Trails of silk and tufts of ribbon were also added. However, the modern tie is simpler than when it first appeared.  This story mainly tells:$p$, $c$["how neckties have changed","why neckties are worn","what neckties are made of","where neckties were invented"]$c$::jsonb, 0, 8),
('6a5 - Main Idea','G6', $p$Hot-air balloonists, who plan long distance flights need to know two things about the wind: its direction and velocity. They also should know about storms in their path, which could endanger their balloon.  This story mainly tells:$p$, $c$["why balloonists fly","how direction and velocity help balloonists","what balloonists need to know","why storms can be dangerous"]$c$::jsonb, 2, 9),
('6a5 - Main Idea','G6', $p$Even a pet lover will be surprised to hear how one ancient man treated his pet. Virgil, a poet in ancient Rome, gave his dead pet a fine funeral. The funeral cost about one hundred thousand dollars. He built a fancy tomb, wrote several poems, and asked his friends to mourn with him. His pet was a housefly!  This story mainly tells:$p$, $c$["why people love their pets","how much a pet's funeral could cost","of an elaborate pet funeral","how many people have pet funerals"]$c$::jsonb, 2, 10);

-- ---- 6a6  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a6 - Main Idea','G6', $p$If there are fewer than 1,000 people where you live, then you reside in a village. If there are between 1,000 and 10,000 people where you live, then you live in a town. If there are more than 10,000 people where you live, then you live in a city. Accordingly, the population of an area determines whether you live in a village, town, or city.  This story mainly tells:$p$, $c$["why some people live in cities","that cities are larger than towns","that villages are smaller than towns","the differences among a village, town, and city"]$c$::jsonb, 3, 1),
('6a6 - Main Idea','G6', $p$Speaking English doesn't mean everyone uses the same words. For example, in Australia, some expressions seem unusual to Americans. "Bonza" means that everything is good. "Cobber" means a special friend.  This story mainly tells:$p$, $c$["that \"cobber\" means a special friend","that not all English words are used by English speakers","that \"bonza\" is an expression of joy","that expressions are used all over the world"]$c$::jsonb, 1, 2),
('6a6 - Main Idea','G6', $p$History recorded only a few women in the Revolutionary War. However, Molly Pitcher was a heroine of this war. She risked her life to aid soldiers during the battle of Monmouth, carrying pitchers of water to the thirsty soldiers; thus, she was called "Molly Pitcher."  This story mainly tells:$p$, $c$["why Molly Pitcher was important","how Molly Pitcher got her name","how many women were in the Revolutionary War","what battle took place during the Revolutionary War"]$c$::jsonb, 1, 3),
('6a6 - Main Idea','G6', $p$Without elevators, it would be impossible to construct high buildings. Before elevators came into use, few buildings were more than five stories high. In 1859, the first elevator was installed in a building on Fifth Avenue. By the close of the century, America had its first skyscraper.  This story mainly tells:$p$, $c$["why skyscrapers were built","who invented the elevator","when the first elevator was installed","how elevators aided in the development of buildings"]$c$::jsonb, 3, 4),
('6a6 - Main Idea','G6', $p$In July of 1983, the record low for the United States was 80 degrees below zero in Prospect Creek, Alaska. But, the coldest temperature ever, on Earth, was registered with a record low of 128.6 degrees below zero in Vostok, a Russian Antarctic station.  This story mainly tells:$p$, $c$["about the lowest temperature ever recorded","that in 1983, Alaska had a record low in the month of July","that Earth has had some very low temperatures","what Vostok is"]$c$::jsonb, 2, 5),
('6a6 - Main Idea','G6', $p$Many famous space observation centers are located in Arizona. However, observatories in Arizona are being hindered in their work, because of the state's growing population. To deal with this problem, many methods are being tested to subdue the glow of the lights made by the residents of nearby towns.  This story mainly tells:$p$, $c$["why we have space observatories","what is happening to the space observatories in Arizona","why many observatories are in Arizona","what space observatories have taught us"]$c$::jsonb, 1, 6),
('6a6 - Main Idea','G6', $p$During the Civil War, the Northern soldiers were fearful of the "Rebel Yell" more than any other weapons of the Southern army. As they charged, the Southern soldiers yelled so wildly, that even the bravest of the Northern troops were terrified.  This story mainly tells:$p$, $c$["what the Southern army yelled","when the \"Rebel Yell\" was popular","how the \"Rebel Yell\" affected Northern troops","why the Civil War took place"]$c$::jsonb, 2, 7),
('6a6 - Main Idea','G6', $p$Like kids, even adults like playing with shadows. Shadows provide a popular form of entertainment. With practice, you can cast a variety of amusing shadow figures on a wall. Just make sure you keep your hands between the light and the surface.  This story mainly tells:$p$, $c$["who plays with shadow puppets","of the popularity of shadow puppets, and how to make them","why people play with shadow puppets","how long shadow puppets have existed"]$c$::jsonb, 1, 8),
('6a6 - Main Idea','G6', $p$Aquaculture is ideally suited to Hawaii, where freshwater prawns, saltwater shrimp, oysters, and clams are cultivated. Since the overall size of the islands offered limited land agriculture, the people of Hawaii needed to develop shellfish farming.  This story mainly tells:$p$, $c$["why shellfish farming was developed in Hawaii","that Hawaii does not have much agricultural land","that oysters are cultivated","that Hawaiians love shellfish"]$c$::jsonb, 0, 9),
('6a6 - Main Idea','G6', $p$Like other desert plants, a cactus has a built-in reservoir. Some species can go two years without any rain at all. Due to the thick covering on the stem the water inside the cactus does not evaporate.  This story mainly tells:$p$, $c$["that cacti grow in the desert","that a cactus' stem is thick","that all plants need rainfall","how some plants manage in dry areas"]$c$::jsonb, 3, 10);

-- ---- 6a7  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a7 - Main Idea','G6', $p$Every year the ocean swallows a small part of the U.S. coastline. This means that the U.S. is gradually sinking. Don't panic! Scientists do not expect America to disappear for a few hundred thousand years.  This story mainly tells:$p$, $c$["that our coastline is decreasing","that we should begin to panic","that despite the U.S. sinking, we are not in immediate danger","why we are not at risk"]$c$::jsonb, 2, 1),
('6a7 - Main Idea','G6', $p$Have you ever seen the birth of an iceberg? As a huge mass of ice breaks away from the glaciers, there is a prolonged rumble, like a roll of thunder. Bursting bubbles of compressed air hiss as the new island of ice begins its life-long journey through water.  This story mainly tells:$p$, $c$["when icebergs begin their journey","why icebergs break","how icebergs are formed","what a glacier consists of"]$c$::jsonb, 2, 2),
('6a7 - Main Idea','G6', $p$The "handedness" of most infants is determined by where they turn their head while they are sleeping. If they turn their head to the right, they are most likely to become right-handed. Scientists who have been observing the sleeping positions of 150 newborn babies have come to this conclusion.  This story mainly tells:$p$, $c$["how many babies were tested","why being right-handed or left-handed is important","how to determine whether a baby is right-handed or left-handed","how babies sleep"]$c$::jsonb, 2, 3),
('6a7 - Main Idea','G6', $p$Following the long dry spells, black blizzards roamed through the mid-western states. The topsoil was blown loose from the surface of the parched earth. Great clouds of black dust turned day into night. It was a fearful sight to see.  This story mainly tells:$p$, $c$["why black blizzards were fearsome","when black blizzards occurred","why black blizzards existed","that clouds of dust darkened the sky"]$c$::jsonb, 0, 4),
('6a7 - Main Idea','G6', $p$In 1932, James Herman Banning and Tomas C. Allen became the first African-American pilots. Mr. Banning was originally an auto mechanic. Both of them made a trans-continental flight from Los Angeles to New York City.  This story mainly tells:$p$, $c$["that Mr. Banning was an auto mechanic","about the first African-American pilots","why they flew from Los Angeles to New York City","when Banning and Allen became pilots"]$c$::jsonb, 1, 5),
('6a7 - Main Idea','G6', $p$Even without the aid of a speedometer, you can still determine the speed of ocean waves. As waves roll in onto the beach, count the seconds between the first two arriving crests, and then multiply by 3.5. For example, if ten seconds pass between the first and second wave, they are traveling at 35 miles an hour.  This story mainly tells:$p$, $c$["why ocean waves occur","how quickly waves appear","how to determine manually the speed of waves","how slowly waves disappear"]$c$::jsonb, 2, 6),
('6a7 - Main Idea','G6', $p$During the Roman Empire, the dinners held were great feasts, often attended by many guests. Along with the abundant meals, jugglers, clowns, and dancers entertained the guests. These dinners often lasted eight to ten hours.  This story mainly tells:$p$, $c$["what was served at Empire dinners","that Empire dinners lasted 8 to 10 hours","why Roman Empire dinners were held","how Roman guests were treated"]$c$::jsonb, 3, 7),
('6a7 - Main Idea','G6', $p$Since sugar cane is always available in the supermarket, people today don't seem to appreciate the value of it. During the frontier era, sugar cane was a luxury beyond reach. Instead, maple syrup, maple sugar, and honey were used to sweeten food and drinks.  This story mainly tells:$p$, $c$["that we take sugar for granted","how sugar cane is harvested","that sugar cane was beyond reach","why substitutes were used instead of sugar cane"]$c$::jsonb, 0, 8),
('6a7 - Main Idea','G6', $p$Mayan Indians created one of the most advanced civilizations in the New World. Many scholars feel that the single most remarkable achievement of the Mayans was the discovery and usage of the zero in Mathematics.  This story mainly tells:$p$, $c$["that the Mayans were advanced","how the Mayans contributed to our advancement","why the Mayans used a \"zero\"","how long ago the Mayans existed"]$c$::jsonb, 0, 9),
('6a7 - Main Idea','G6', $p$Israel Putman was in charge of the colonial soldiers in the battle of Bunker Hill. He told his men, "Don't fire until you see the whites of their eyes." His soldiers patiently waited until the British were within twenty-five yards before they fired. Because the redcoats were close enough to be seen, the colonists were able to destroy the enemy. To this day, the colonists are respected for their patience and bravery.  This story mainly tells:$p$, $c$["why the colonists and redcoats were fighting","that it was dangerous to wait so long before firing","that the colonists obeyed their Commander at Bunker Hill","why many soldiers were killed"]$c$::jsonb, 2, 10);

-- ---- 6a8  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a8 - Main Idea','G6', $p$Although no one can say for sure whether Robin Hood was a real man or simply a legend, it is thought that he lived in the 1100's or 1200's. Many stories have been told and written of his adventures. Unfortunately, no historian who was alive during those centuries has ever mentioned Robin Hood. Maybe one day we will discover the truth.  This story mainly tells:$p$, $c$["how little we really know about Robin Hood","what historians have written about this adventurer","during which century Robin Hood was said to have lived","that many stories have been told about this legend"]$c$::jsonb, 0, 1),
('6a8 - Main Idea','G6', $p$In St. Louis, Missouri, stands the sixteen-ton, steel arch that is the tallest American monument. It was erected as a symbol of the city's role as the gateway to the West. The Gateway Arch is twice the height of the Statue of Liberty and is strong enough to withstand winds of 150 miles per hour. The top of the arch is used as an observatory of America's heartland.  This story mainly tells:$p$, $c$["that the Arch is twice as tall as the Statue of Liberty","what can be seen from the top of the Arch","when the Arch was constructed","of the tallest American monument and what it symbolizes"]$c$::jsonb, 3, 2),
('6a8 - Main Idea','G6', $p$The expression "as mad as a hatter" existed even before the "Mad Hatter" was a recognizable fairytale character. Years ago, hatters, people who made hats, were thought to be mad. In the process of making their hats, hatters used a chemical called mercury. This chemical contained a poison that caused the hatters' muscles to twitch. Because people could not know the source of the twitching, they thought that the hatters had gone "mad". The expression "as mad as a hatter" was based on this reasoning.  This story mainly tells:$p$, $c$["what chemical was used by hatters","how an expression came about","that \"mad\" can mean either crazy or angry","what happened to the muscles of hatters long ago"]$c$::jsonb, 1, 3),
('6a8 - Main Idea','G6', $p$Longevin, a French scientist, developed a way to protect Allied ships from the attack of German submarines during WWI. Sonar, sound beams sent through water, helped identify whether or not a submarine was nearby. When the sound beam was sent out and had no obstacles, it would eventually fade. If, however, something was in the way, the sound would echo back. The sonar system could determine where a submarine was located, depending upon the direction of the echo and how quickly it returned.  This story mainly tells:$p$, $c$["who invented the sonar system","why Allied ships were attacked by the Germans","how submarines were used in WWI","how the sonar system detects submarines"]$c$::jsonb, 3, 4),
('6a8 - Main Idea','G6', $p$Arrowheads are usually separate pieces attached to the ends of arrows. Since their creation in North Africa, over 15,000 years ago, they have come in many different shapes and sizes. Even the materials with which they are made have varied from stone, to bone, to wood, to metal. Additionally, flaming arrows have been used to set towns on fire, and whistling arrows have been used to signal warning. Early hunters used poisoned arrows for hunting and fishing.  This story mainly tells:$p$, $c$["where arrowheads were first created","the varieties and uses of arrowheads","how long ago arrowheads were created","why arrowheads are all different"]$c$::jsonb, 1, 5),
('6a8 - Main Idea','G6', $p$In the time of George Washington, delegates needed a city in which to hold their meetings. The northern states wanted the meetings to be held in the North, whereas the southern states wanted the meetings to be held in the South. In an attempt to be fair, Washington decided that the nation's capitol would be in a separate district that was neither North nor South. He called this area the District of Columbia. For that reason, the District of Columbia is not a state.  This story mainly tells:$p$, $c$["why Washington, D.C. is not part of a state","of a meeting held by George Washington","where the states wanted to hold their meetings","why the nation needed a capitol"]$c$::jsonb, 0, 6),
('6a8 - Main Idea','G6', $p$The full effects of the sun cannot be seen until hours after they are sustained. For this reason, it is suggested that special care be taken in order to avoid painful circumstances. A person over-exposed to the rays of the sun can suffer severe sunburn that will require medical treatment. To be safe, sun worshipers should come in out of the sun before their skin begins to turn pink.  This story mainly tells:$p$, $c$["why medical attention is sometimes required during the summer","how to be watchful of the sun's powerful rays","how long it takes before the sun's effects are noted","what to do if your skin turns pink"]$c$::jsonb, 1, 7),
('6a8 - Main Idea','G6', $p$In 1905, Frederick Wells, a mine manager, saw a large crystal imbedded in the ceiling of a mineshaft. At first, he thought that someone had tried to play a joke on him with a piece of glass. Upon careful examination, he found that it was not a joke, but rather a real diamond. It weighed more than 1.5 pounds. To date, the "Cullinan" is the largest diamond ever discovered.  This story mainly tells:$p$, $c$["who found the Cullinan","how the largest diamond ever was found","why Wells thought that someone was trying to play a joke on him","where a precious diamond was found"]$c$::jsonb, 1, 8),
('6a8 - Main Idea','G6', $p$Potatoes were first grown by South American Indians and then taken to Europe by the Spanish in the 1500's. It was the early settlers in the United States who brought them back across the Atlantic. However, when potatoes were first introduced to Europe, people thought that they were poisonous and were afraid to eat them. Luckily, the potato found a home with the Irish, who were willing to take their chances. When Irish settlers came to the United States, they brought the potato with them.  This story mainly tells:$p$, $c$["what people first thought of potatoes","where potatoes were first grown","why there are potatoes in Ireland","that the potato has traveled and flourished"]$c$::jsonb, 3, 9),
('6a8 - Main Idea','G6', $p$Have you ever heard of a kite pulling a carriage? In England, in the 1800's, a carriage called the Charvolant was built. Instead of horses, huge kites were used to pull it. The driver would pull on the kite lines in order to control the carriage's direction. Additionally, a lever attached to a metal stake was pushed into the earth to bring the carriage to a halt. This "flying carriage" was graceful and lightweight, and could carry passengers across the countryside at a speed of up to twenty miles an hour.  This story mainly tells:$p$, $c$["how fast the Charvolant could travel","why it was referred to as the \"flying carriage\"","about a carriage driven by kites","who invented the Charvolant"]$c$::jsonb, 2, 10);

-- ---- 6a9  Sequence ------------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a9 - Sequence','G6', $p$Choose the best order. A. In the small villages, a great number of the old ideas remain. B. Treating people differently because of their caste was forbidden in India in 1947. C. But, although the law passed, not everyone is obeying it today. D. The new government adopted a Constitution that said that everyone was equal. E. This was the year in which India acquired its independence.$p$, $c$["A-B-D-C-E","B-A-D-C-E","B-E-D-C-A","B-E-D-A-C"]$c$::jsonb, 2, 1),
('6a9 - Sequence','G6', $p$Choose the best order. A. You can use woodland, jungle, or desert plants, although the first two are easier to maintain. B. A warm room is best for a jungle terrarium and a cool room for a woodland terrarium. A desert terrarium requires strong sunlight. C. Your second step is to choose a container. D. Your first step in making a terrarium is to decide what kind of plants you would like. E. A rectangular aquarium is the most popular since its large opening permits the free use of both hands.$p$, $c$["D-C-B-E-A","E-D-A-B-C","D-A-B-C-E","E-B-A-D-C"]$c$::jsonb, 2, 2),
('6a9 - Sequence','G6', $p$Choose the best order. A. It was Wopanaak. No one had written or spoken the language in nearly 150 years. B. Fermino, who has a master's degree in linguistics, couldn't understand what they were saying. C. In it, her Wampanoag Indian ancestors were speaking. D. But she could identify the language. E. Seven years ago, Jessie Little Doe Fermino had a dream.$p$, $c$["A-B-D-C-E","E-C-D-B-A","A-B-C-E-D","E-C-B-D-A"]$c$::jsonb, 3, 3),
('6a9 - Sequence','G6', $p$Choose the best order. A. Alpine championship events were added to world competition in 1931 and to the Olympics in 1936. B. From 1924 to 1931, only Nordic competition was involved. C. Except for Olympic years, the Nordic and Alpine championships are held separately and at different locations. D. Although most of the events had been contested at the regional level since the mid-19th century, the first internationally organized skiing championships did not take place until 1924. E. Events include cross-country races, ski jumping, biathlon, and relay races (Nordic) and downhill and slalom skiing (Alpine).$p$, $c$["D-A-E-C-B","D-B-A-C-E","E-A-D-B-C","A-B-C-E-D"]$c$::jsonb, 1, 4),
('6a9 - Sequence','G6', $p$Choose the best order. A. Not all of the early carriages were drawn by horses. B. Graceful in design and light in weight, the Charvolant carried passengers across the countryside at speeds up to twenty miles per hour. C. To direct the "buoyant sails" and to avoid church steeples and tall trees, the driver pulled on guide ropes or kite lines. D. The Charvolant, built in England in the 1800's, was pulled by huge kites. E. In truth, few wanted to slow down or stop when aboard the "flying carriage." F. To stop the carriage, the driver had only to press down on a lever, which pushed a metal stake into the earth.$p$, $c$["A-B-C-D-F-E","D-A-B-E-C-F","A-D-B-C-F-E","D-E-B-C-D-F"]$c$::jsonb, 2, 5);

-- ---- 6a10  Sequence -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a10 - Sequence','G6', $p$Choose the best order. A. If we can do that, the whole story or selection will seem clear. B. There are too many little statements, or details. C. But luckily, we don't have to carry all the details in our minds. D. None of us can remember all the things we read. E. We must remember only the important things in our reading.$p$, $c$["D-B-C-E-A","E-A-D-B-C","E-C-B-D-A","D-E-A-B-C"]$c$::jsonb, 0, 1),
('6a10 - Sequence','G6', $p$Choose the best order. A. You might startle your friends some day by saying adufan instead of above. B. You can see the prefix a- which here means "on." C. The second part of above comes from the old word bufan meaning "high." D. The word above has an interesting history. E. Then, you can explain that above really means "on high."$p$, $c$["D-C-B-E-A","C-B-D-E-A","D-B-C-A-E","B-A-E-C-D"]$c$::jsonb, 0, 2),
('6a10 - Sequence','G6', $p$Choose the best order. A. Later, they were conquered by Romans, but really, the Romans were conquered by the arts and learning of the Greeks. B. For hundreds of years, Roman children were taught by Greek teachers. C. More than 2000 years ago, the Greeks created one of the greatest civilizations of all time. D. Today, this language is called Latin. E. As you might guess, many Greek words were taken over by the Romans and made a part of their language.$p$, $c$["C-A-B-E-D","C-A-E-D-B","D-B-E-A-C","D-A-B-E-C"]$c$::jsonb, 0, 3),
('6a10 - Sequence','G6', $p$Choose the best order. A. However, if the word is important in the sentence, you may then lose the meaning of the whole sentence. B. When you come across a new word in your reading, you may, of course, skip right past it. C. But what if there are no context clues and no help from word parts? D. Then you have to go to the dictionary. E. Knowing what you now know about word parts and context clues, you can try to work out a meaning for the word.$p$, $c$["E-A-C-D-B","B-A-E-C-D","B-E-C-A-D","E-C-D-A-B"]$c$::jsonb, 1, 4),
('6a10 - Sequence','G6', $p$Choose the best order. A. Unlike Britain, the United States secured a guarantee of freedom for the press and the right of (peaceable) assembly. B. These first 10 amendments, ratified in 1791, adopted into the Constitution the basic English common-law rights that Americans had fought for. C. The Bill of Rights, steered through the first Congress by Madison's diplomacy, mollified much of the latent opposition. D. But they did more. E. Also unlike Britain, church and state were formally separated in a clause that seemed to set equal value on non-establishment of religion and its free exercise.$p$, $c$["C-B-D-A-E","C-A-E-D-B","A-E-B-C-D","B-D-A-E-C"]$c$::jsonb, 0, 5);

-- ---- 6a11  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a11 - Inference','G6', $p$Timothy considered starting a diary. He asked his best friend Wilma about how to maintain the diary. Wilma advised him to record both good and bad events in it. Wilma described her experiences writing in her diary to Timothy, and he became more eager. Which is probably true?$p$, $c$["Timothy received a diary from Wilma.","Wilma told Timothy everything in her diary.","Wilma has experience in writing diaries.","Wilma's writing skills discouraged Timothy."]$c$::jsonb, 2, 1),
('6a11 - Inference','G6', $p$The Hawaiian Islands consist of old, inactive volcanoes. Large tourist groups seek and check out these volcanoes in hopes of witnessing some action. Large parking lots sit on top of these volcanoes. Which is probably true?$p$, $c$["The tourists love the sensation of adventure from exploring the volcanoes.","The tourists have never seen volcanoes.","The tourists are foolish and negligent.","The tourists are destroying the environment by stepping on the volcanoes."]$c$::jsonb, 0, 2),
('6a11 - Inference','G6', $p$Rebecca was gloomy. She didn't have any friends, and she didn't like the uniform she had to wear at her new school. Rebecca's dad told her about his experience of moving to Boston and how he overcame being the outsider. He said, "Rebecca, since you've been in Chicago for only a week, see what happens." Which is probably true?$p$, $c$["Boston fascinated Rebecca.","Rebecca's dad did not like Chicago.","Rebecca's dad once resided in Massachusetts.","Rebecca and her dad emigrated from England."]$c$::jsonb, 2, 3),
('6a11 - Inference','G6', $p$"I can't wait for summer because this winter is killing me," said Jack. Allen answered, "When it's winter, you want summer, but when it's summer, you want winter." Which is probably true?$p$, $c$["Jack and Allen lived in a place with unbearable weather conditions.","Allen was amused by Jack's pondering.","Jack always complained about the weather.","Jack and Allen are weather researchers."]$c$::jsonb, 2, 4),
('6a11 - Inference','G6', $p$Frank shook his leg nervously while he waited for his turn to present his story to the class. The teacher called his name, and he stood up in front of the class. He noticed only his friends. Frank felt calm after that. Which is probably true?$p$, $c$["Frank's friends gave Frank their thumbs up.","Frank did not finish writing his story, and his presentation was unrehearsed.","Frank feared speaking in front of everyone in the class.","Frank's voice trembled when he read his story to the class."]$c$::jsonb, 2, 5);

-- ---- 6a12  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('6a12 - Inference','G6', $p$It is extremely cold in the Antarctic. The King Penguins protect their babies from the harsh weather. The father penguin rests the egg on his feet and covers it with his belly. The egg is kept warm and safe. Even after the baby penguins hatch, the father penguins do not cease taking care of the chicks. Which is probably true?$p$, $c$["The penguins prefer to live in a place with tropical climate.","The King Penguins are endangered animals.","The baby penguin would not survive without the father penguin.","The King Penguins are the grandest type of penguins."]$c$::jsonb, 2, 1),
('6a12 - Inference','G6', $p$Bill made up a prank to play at the assembly. He scribbled his scheme on a piece of paper that looked exactly like the piece of paper his homework was on. Before Bill had the opportunity to enter the assembly, the principal called him to the office, and asked him about the plan. Which is probably true?$p$, $c$["Bill was indifferent to punishments.","Bill was the worst bully in the entire school.","Bill confessed his scheme in a letter to the principal.","Bill handed the wrong paper to his teacher."]$c$::jsonb, 3, 2),
('6a12 - Inference','G6', $p$"I know that there is a first time for everything, but it looks really crowded down there. Are you sure about this?" asked Joel. Meg answered, "Once you get the skates on, you'll completely forget about the other people." Which is probably true?$p$, $c$["Joel became determined to be the best skater in the world.","Meg challenged Joel to skate.","Joel has never been skating before, but Meg has.","All of the above"]$c$::jsonb, 2, 3),
('6a12 - Inference','G6', $p$Ted and Vera cleaned their rooms. Ted vacuumed the house, while Vera cleaned the kitchen. They discussed what they should do next. They predicted that the whole house would be clean before their mom returned home. Which is probably true?$p$, $c$["Ted and Vera cooperate in everything they do.","The intent of Ted and Vera was to please their mother.","Ted programmed everything.","All of the above"]$c$::jsonb, 1, 4),
('6a12 - Inference','G6', $p$All of his friends and family begged Nelson to get a hearing aid. They complained that it was nearly impossible to communicate with him without shouting. One day, Ricky, Nelson's grandson, visited Nelson and hollered, "How are you?" Nelson grumbled, "Stop the yelling. I can hear you." Which is probably true?$p$, $c$["Nelson's family and friends were the most affectionate people in the world.","Nelson finally got a hearing aid.","A hearing aid brought more trouble to Nelson.","All of the above"]$c$::jsonb, 1, 5);
