-- ============================================================================
-- Duke College — question bank: The Learning Gate, Reading Skill (LG-R-RS-5a)
-- 12 worksheets / 142 questions. Run AFTER setup.sql. Adds questions only.
-- correct_index is 0-based. Answers were generated for you; please spot-check.
-- ============================================================================

-- ---- 5a1  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a1 - Context Clue','G5', $p$Choose the best word for blank (1): It is not (1)___ that the first settlers quickly killed most of the bears. A hungry bear would eat almost anything a farmer could raise or grow. Some bears can run at (2)___ up to thirty miles an hour. Bear meat could be eaten, and the skins were useful. But the most (3)___ part of a bear was the (4)___. Many people liked bear oil better than butter. A large bear, killed when it is fat in the fall, would (5)___ about thirty gallons of bear oil.$p$, $c$["usual","surprising","fair","cruel"]$c$::jsonb, 1, 1),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (2): It is not (1)___ that the first settlers quickly killed most of the bears. A hungry bear would eat almost anything a farmer could raise or grow. Some bears can run at (2)___ up to thirty miles an hour. Bear meat could be eaten, and the skins were useful. But the most (3)___ part of a bear was the (4)___. Many people liked bear oil better than butter. A large bear, killed when it is fat in the fall, would (5)___ about thirty gallons of bear oil.$p$, $c$["lengths","weights","speeds","meters"]$c$::jsonb, 2, 2),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (3): It is not (1)___ that the first settlers quickly killed most of the bears. A hungry bear would eat almost anything a farmer could raise or grow. Some bears can run at (2)___ up to thirty miles an hour. Bear meat could be eaten, and the skins were useful. But the most (3)___ part of a bear was the (4)___. Many people liked bear oil better than butter. A large bear, killed when it is fat in the fall, would (5)___ about thirty gallons of bear oil.$p$, $c$["useless","valuable","despised","covered"]$c$::jsonb, 1, 3),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (4): It is not (1)___ that the first settlers quickly killed most of the bears. A hungry bear would eat almost anything a farmer could raise or grow. Some bears can run at (2)___ up to thirty miles an hour. Bear meat could be eaten, and the skins were useful. But the most (3)___ part of a bear was the (4)___. Many people liked bear oil better than butter. A large bear, killed when it is fat in the fall, would (5)___ about thirty gallons of bear oil.$p$, $c$["fat","skin","meat","liver"]$c$::jsonb, 0, 4),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (5): It is not (1)___ that the first settlers quickly killed most of the bears. A hungry bear would eat almost anything a farmer could raise or grow. Some bears can run at (2)___ up to thirty miles an hour. Bear meat could be eaten, and the skins were useful. But the most (3)___ part of a bear was the (4)___. Many people liked bear oil better than butter. A large bear, killed when it is fat in the fall, would (5)___ about thirty gallons of bear oil.$p$, $c$["drain","plant","prove","yield"]$c$::jsonb, 3, 5),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (6): Landowners along the Nile had a problem. Every year the Nile (6)___, leaving a layer of mud that hid the old (7)___ lines. The wise men of Egypt (8)___ a way to (9)___ the boundary lines every year. They used a (10)___ of measurement involving geometry and triangulation so that everyone knew where his lands lay every year.$p$, $c$["dried","overflowed","polluted","left"]$c$::jsonb, 1, 6),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (7): Landowners along the Nile had a problem. Every year the Nile (6)___, leaving a layer of mud that hid the old (7)___ lines. The wise men of Egypt (8)___ a way to (9)___ the boundary lines every year. They used a (10)___ of measurement involving geometry and triangulation so that everyone knew where his lands lay every year.$p$, $c$["electricity","curved","boundary","zigzag"]$c$::jsonb, 2, 7),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (8): Landowners along the Nile had a problem. Every year the Nile (6)___, leaving a layer of mud that hid the old (7)___ lines. The wise men of Egypt (8)___ a way to (9)___ the boundary lines every year. They used a (10)___ of measurement involving geometry and triangulation so that everyone knew where his lands lay every year.$p$, $c$["protected","denied","discovered","abandoned"]$c$::jsonb, 2, 8),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (9): Landowners along the Nile had a problem. Every year the Nile (6)___, leaving a layer of mud that hid the old (7)___ lines. The wise men of Egypt (8)___ a way to (9)___ the boundary lines every year. They used a (10)___ of measurement involving geometry and triangulation so that everyone knew where his lands lay every year.$p$, $c$["resell","investigate","restore","negotiate"]$c$::jsonb, 2, 9),
('5a1 - Context Clue','G5', $p$Choose the best word for blank (10): Landowners along the Nile had a problem. Every year the Nile (6)___, leaving a layer of mud that hid the old (7)___ lines. The wise men of Egypt (8)___ a way to (9)___ the boundary lines every year. They used a (10)___ of measurement involving geometry and triangulation so that everyone knew where his lands lay every year.$p$, $c$["instrument","system","class","politics"]$c$::jsonb, 1, 10),
('5a1 - Context Clue','G5', $p$The unexpectedly large number of guests at her birthday party was ______ to Anna.$p$, $c$["surprising","yielding","rapid","concluding"]$c$::jsonb, 0, 11),
('5a1 - Context Clue','G5', $p$Because of plenty of rainfall and sunshine, the crop ______ was large.$p$, $c$["fat","speed","continue","yield"]$c$::jsonb, 3, 12),
('5a1 - Context Clue','G5', $p$In the story, The Little Prince, what is substantial or ______ is invisible to the eye.$p$, $c$["well-known","valuable","yielding","quick"]$c$::jsonb, 1, 13),
('5a1 - Context Clue','G5', $p$A fossil of a dinosaur with feathers was ______ recently; it was the first of its kind.$p$, $c$["overflowed","followed","ignored","discovered"]$c$::jsonb, 3, 14),
('5a1 - Context Clue','G5', $p$Driving an automobile at high ______ in the rain and snow is extremely dangerous because the slippery road may lead to a loss of control of the automobile.$p$, $c$["fat","yield","surprise","speeds"]$c$::jsonb, 3, 15),
('5a1 - Context Clue','G5', $p$According to an ancient Bible story, Moses led the people of Israel from Egypt to the land that ______ with milk and honey, which was extremely different from the dry desert.$p$, $c$["discovered","overflowed","bound","classic"]$c$::jsonb, 1, 16),
('5a1 - Context Clue','G5', $p$Some people cross the ______ between Mexico and the United States to fulfill the dream of happiness and wealth.$p$, $c$["system","boundary","discovery","revolution"]$c$::jsonb, 1, 17),
('5a1 - Context Clue','G5', $p$To stay healthy, we should avoid eating too much ______.$p$, $c$["valuable","surprising","yielding","fat"]$c$::jsonb, 3, 18),
('5a1 - Context Clue','G5', $p$The antique was ______ to its original state.$p$, $c$["restored","sold","discovered","system"]$c$::jsonb, 0, 19),
('5a1 - Context Clue','G5', $p$Numbers and mathematical ______ evolved over many centuries.$p$, $c$["discoveries","boundaries","systems","computers"]$c$::jsonb, 2, 20);

-- ---- 5a2  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a2 - Context Clue','G5', $p$Choose the best word for blank (1): A penguin is an unusual bird that stands (1)___ and (2)___ from side to side when it walks. Penguins live in the southern half of the world. Penguins cannot fly, but they are good swimmers. They spend all of their lives in the water. (3)___ penguins lay their eggs and raise their young on land. Penguins usually live in (4)___ places. They have thick (5)___ of fat to keep them warm.$p$, $c$["rarely","furious","upright","mysterious"]$c$::jsonb, 2, 1),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (2): A penguin is an unusual bird that stands (1)___ and (2)___ from side to side when it walks. Penguins live in the southern half of the world. Penguins cannot fly, but they are good swimmers. They spend all of their lives in the water. (3)___ penguins lay their eggs and raise their young on land. Penguins usually live in (4)___ places. They have thick (5)___ of fat to keep them warm.$p$, $c$["sings","flies","crawls","waddles"]$c$::jsonb, 3, 2),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (3): A penguin is an unusual bird that stands (1)___ and (2)___ from side to side when it walks. Penguins live in the southern half of the world. Penguins cannot fly, but they are good swimmers. They spend all of their lives in the water. (3)___ penguins lay their eggs and raise their young on land. Penguins usually live in (4)___ places. They have thick (5)___ of fat to keep them warm.$p$, $c$["Therefore,","Accordingly,","So,","However,"]$c$::jsonb, 3, 3),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (4): A penguin is an unusual bird that stands (1)___ and (2)___ from side to side when it walks. Penguins live in the southern half of the world. Penguins cannot fly, but they are good swimmers. They spend all of their lives in the water. (3)___ penguins lay their eggs and raise their young on land. Penguins usually live in (4)___ places. They have thick (5)___ of fat to keep them warm.$p$, $c$["hot","cold","dry","humid"]$c$::jsonb, 1, 4),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (5): A penguin is an unusual bird that stands (1)___ and (2)___ from side to side when it walks. Penguins live in the southern half of the world. Penguins cannot fly, but they are good swimmers. They spend all of their lives in the water. (3)___ penguins lay their eggs and raise their young on land. Penguins usually live in (4)___ places. They have thick (5)___ of fat to keep them warm.$p$, $c$["containers","layers","nests","furs"]$c$::jsonb, 1, 5),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (6): The two to six volts used in flashlights or car (6)___ won't (7)___ people. One hundred and ten volts will (8)___ a person, but not kill unless the person is wet. Higher power (9)___ are dangerous. 500 volts has killed many people. Anything above a thousand volts is nearly always (10)___.$p$, $c$["brakes","headlights","seats","batteries"]$c$::jsonb, 3, 6),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (7): The two to six volts used in flashlights or car (6)___ won't (7)___ people. One hundred and ten volts will (8)___ a person, but not kill unless the person is wet. Higher power (9)___ are dangerous. 500 volts has killed many people. Anything above a thousand volts is nearly always (10)___.$p$, $c$["harm","tickle","cure","explode"]$c$::jsonb, 0, 7),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (8): The two to six volts used in flashlights or car (6)___ won't (7)___ people. One hundred and ten volts will (8)___ a person, but not kill unless the person is wet. Higher power (9)___ are dangerous. 500 volts has killed many people. Anything above a thousand volts is nearly always (10)___.$p$, $c$["pinch","anger","bruise","shock"]$c$::jsonb, 3, 8),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (9): The two to six volts used in flashlights or car (6)___ won't (7)___ people. One hundred and ten volts will (8)___ a person, but not kill unless the person is wet. Higher power (9)___ are dangerous. 500 volts has killed many people. Anything above a thousand volts is nearly always (10)___.$p$, $c$["gallons","liquid","voltages","dozens"]$c$::jsonb, 2, 9),
('5a2 - Context Clue','G5', $p$Choose the best word for blank (10): The two to six volts used in flashlights or car (6)___ won't (7)___ people. One hundred and ten volts will (8)___ a person, but not kill unless the person is wet. Higher power (9)___ are dangerous. 500 volts has killed many people. Anything above a thousand volts is nearly always (10)___.$p$, $c$["nimble","deafening","advantageous","fatal"]$c$::jsonb, 3, 10),
('5a2 - Context Clue','G5', $p$The tree that had stood firmly ______ broke in half in the gust, but the grass that bent survived.$p$, $c$["coldly","upright","place","above"]$c$::jsonb, 1, 11),
('5a2 - Context Clue','G5', $p$High ______ are used in electric power lines.$p$, $c$["batteries","voltages","shocks","fortunes"]$c$::jsonb, 1, 12),
('5a2 - Context Clue','G5', $p$You were angered by your brother's rude behavior; ______, it is not right to hit him.$p$, $c$["moreover","because","whereabout","however"]$c$::jsonb, 3, 13),
('5a2 - Context Clue','G5', $p$The electric toy will not work without ______.$p$, $c$["shocks","voltages","batteries","claims"]$c$::jsonb, 2, 14),
('5a2 - Context Clue','G5', $p$For keeping bodies warm, experts say that wearing ______ of clothing is better than wearing a single article of thick clothing.$p$, $c$["waddles","levels","layers","adventures"]$c$::jsonb, 2, 15),
('5a2 - Context Clue','G5', $p$People shivered because of the ______ wind hitting their bodies.$p$, $c$["harmful","upright","cold","electricity"]$c$::jsonb, 2, 16),
('5a2 - Context Clue','G5', $p$The tame animal will not ______ you.$p$, $c$["cuddle","electrify","harm","police"]$c$::jsonb, 2, 17),
('5a2 - Context Clue','G5', $p$A lightning bolt may ______ you.$p$, $c$["shock","misunderstand","prepare","advertise"]$c$::jsonb, 0, 18),
('5a2 - Context Clue','G5', $p$A duck ______ across the land, and paddles in the water.$p$, $c$["layers","waddles","slides","swims"]$c$::jsonb, 1, 19),
('5a2 - Context Clue','G5', $p$The careless driver caused a ______ accident.$p$, $c$["battery","voltage","fatal","climate"]$c$::jsonb, 2, 20);

-- ---- 5a3  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a3 - Context Clue','G5', $p$Choose the best word for blank (1): A computer is a machine that helps people solve problems. (1)___ of words, it uses numbers to (2)___ the information it holds. A computer can work out problems much faster than a person can. A person must put (3)___ into a computer, and give the computer (4)___. The instructions tell the computer what to do with the information. The computer can also put information into its (5)___ to be used later on.$p$, $c$["Instead","Composed","Represented","Master"]$c$::jsonb, 0, 1),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (2): A computer is a machine that helps people solve problems. (1)___ of words, it uses numbers to (2)___ the information it holds. A computer can work out problems much faster than a person can. A person must put (3)___ into a computer, and give the computer (4)___. The instructions tell the computer what to do with the information. The computer can also put information into its (5)___ to be used later on.$p$, $c$["rely","carry","work","stop"]$c$::jsonb, 1, 2),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (3): A computer is a machine that helps people solve problems. (1)___ of words, it uses numbers to (2)___ the information it holds. A computer can work out problems much faster than a person can. A person must put (3)___ into a computer, and give the computer (4)___. The instructions tell the computer what to do with the information. The computer can also put information into its (5)___ to be used later on.$p$, $c$["information","machines","summaries","experiments"]$c$::jsonb, 0, 3),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (4): A computer is a machine that helps people solve problems. (1)___ of words, it uses numbers to (2)___ the information it holds. A computer can work out problems much faster than a person can. A person must put (3)___ into a computer, and give the computer (4)___. The instructions tell the computer what to do with the information. The computer can also put information into its (5)___ to be used later on.$p$, $c$["substances","languages","electricity","instructions"]$c$::jsonb, 3, 4),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (5): A computer is a machine that helps people solve problems. (1)___ of words, it uses numbers to (2)___ the information it holds. A computer can work out problems much faster than a person can. A person must put (3)___ into a computer, and give the computer (4)___. The instructions tell the computer what to do with the information. The computer can also put information into its (5)___ to be used later on.$p$, $c$["oven","memory","mind","tunnel"]$c$::jsonb, 1, 5),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (6): In September, 1990, a huge (6)___ wave (7)___ over the city of Galveston, (8)___ all but a few houses. On the following morning, the citizens met and formed (9)___. Plans were made to provide pure water and electricity and to improvise shelter for the (10)___.$p$, $c$["radio","electric","tidal","curly"]$c$::jsonb, 2, 6),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (7): In September, 1990, a huge (6)___ wave (7)___ over the city of Galveston, (8)___ all but a few houses. On the following morning, the citizens met and formed (9)___. Plans were made to provide pure water and electricity and to improvise shelter for the (10)___.$p$, $c$["buried","climbed","swept","stepped"]$c$::jsonb, 2, 7),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (8): In September, 1990, a huge (6)___ wave (7)___ over the city of Galveston, (8)___ all but a few houses. On the following morning, the citizens met and formed (9)___. Plans were made to provide pure water and electricity and to improvise shelter for the (10)___.$p$, $c$["recovering","pressuring","destroying","preventing"]$c$::jsonb, 2, 8),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (9): In September, 1990, a huge (6)___ wave (7)___ over the city of Galveston, (8)___ all but a few houses. On the following morning, the citizens met and formed (9)___. Plans were made to provide pure water and electricity and to improvise shelter for the (10)___.$p$, $c$["congress","committees","tasks","centers"]$c$::jsonb, 1, 9),
('5a3 - Context Clue','G5', $p$Choose the best word for blank (10): In September, 1990, a huge (6)___ wave (7)___ over the city of Galveston, (8)___ all but a few houses. On the following morning, the citizens met and formed (9)___. Plans were made to provide pure water and electricity and to improvise shelter for the (10)___.$p$, $c$["homeless","doctors","orphans","visitors"]$c$::jsonb, 0, 10),
('5a3 - Context Clue','G5', $p$______ waves swept the beach shores after the earthquake.$p$, $c$["Homeless","Committee","Tight","Tidal"]$c$::jsonb, 3, 11),
('5a3 - Context Clue','G5', $p$The father ______ the bike for his son because it was heavy.$p$, $c$["informed","carried","remembered","agonized"]$c$::jsonb, 1, 12),
('5a3 - Context Clue','G5', $p$The janitor ______ up the pieces of shattered glass.$p$, $c$["committed","swept","operated","possessed"]$c$::jsonb, 1, 13),
('5a3 - Context Clue','G5', $p$The teacher's ______ to the class were for the students to take out their homework and compare answers with one another.$p$, $c$["instructions","exclamation","memory","music"]$c$::jsonb, 0, 14),
('5a3 - Context Clue','G5', $p$You can store more information on computers that have more ______.$p$, $c$["memory","instruction","information","advice"]$c$::jsonb, 0, 15),
('5a3 - Context Clue','G5', $p$______ of going to school, Bart stayed home because he was ill.$p$, $c$["In addition","In kindness","Instructions","Instead"]$c$::jsonb, 3, 16),
('5a3 - Context Clue','G5', $p$Books and newspapers contain a lot of ______.$p$, $c$["instruction","information","memory","notice"]$c$::jsonb, 1, 17),
('5a3 - Context Clue','G5', $p$Natural disasters, such as earthquakes and tornadoes, are infamous for ______ billions of dollars of property.$p$, $c$["sweating","taxing","suspending","destroying"]$c$::jsonb, 3, 18),
('5a3 - Context Clue','G5', $p$Relief ______ help organize activities that restore properties.$p$, $c$["commercials","committees","homeless","plantations"]$c$::jsonb, 1, 19),
('5a3 - Context Clue','G5', $p$______ people are those who have nowhere to live.$p$, $c$["Committees","Homeless","Hopeless","Tidals"]$c$::jsonb, 1, 20);

-- ---- 5a4  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a4 - Context Clue','G5', $p$Choose the best word for blank (1): Many people think of Arizona as a desert. Yet, in spite of the (1)___ rainfall and the hot (2)___, the state has a more varied and plentiful plant life than one might (3)___. The saguaro, often forty feet high, is the largest cactus plant in the United States. In fact, more than ninety kinds of (4)___ are found in the desert. The state has a variety of animal life. Larger animals (5)___ deer, antelope, wildcat, coyote, mountain lion, bear, and lynx.$p$, $c$["limited","popular","plentiful","miraculous"]$c$::jsonb, 0, 1),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (2): Many people think of Arizona as a desert. Yet, in spite of the (1)___ rainfall and the hot (2)___, the state has a more varied and plentiful plant life than one might (3)___. The saguaro, often forty feet high, is the largest cactus plant in the United States. In fact, more than ninety kinds of (4)___ are found in the desert. The state has a variety of animal life. Larger animals (5)___ deer, antelope, wildcat, coyote, mountain lion, bear, and lynx.$p$, $c$["houses","sauce","herbs","weather"]$c$::jsonb, 3, 2),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (3): Many people think of Arizona as a desert. Yet, in spite of the (1)___ rainfall and the hot (2)___, the state has a more varied and plentiful plant life than one might (3)___. The saguaro, often forty feet high, is the largest cactus plant in the United States. In fact, more than ninety kinds of (4)___ are found in the desert. The state has a variety of animal life. Larger animals (5)___ deer, antelope, wildcat, coyote, mountain lion, bear, and lynx.$p$, $c$["suspend","suspect","sustain","summarize"]$c$::jsonb, 1, 3),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (4): Many people think of Arizona as a desert. Yet, in spite of the (1)___ rainfall and the hot (2)___, the state has a more varied and plentiful plant life than one might (3)___. The saguaro, often forty feet high, is the largest cactus plant in the United States. In fact, more than ninety kinds of (4)___ are found in the desert. The state has a variety of animal life. Larger animals (5)___ deer, antelope, wildcat, coyote, mountain lion, bear, and lynx.$p$, $c$["roses","cactuses","cabbages","flowers"]$c$::jsonb, 1, 4),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (5): Many people think of Arizona as a desert. Yet, in spite of the (1)___ rainfall and the hot (2)___, the state has a more varied and plentiful plant life than one might (3)___. The saguaro, often forty feet high, is the largest cactus plant in the United States. In fact, more than ninety kinds of (4)___ are found in the desert. The state has a variety of animal life. Larger animals (5)___ deer, antelope, wildcat, coyote, mountain lion, bear, and lynx.$p$, $c$["exclude","exceed","express","include"]$c$::jsonb, 3, 5),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (6): Sir Winston Churchill was a (6)___ man. He was not a very good student, and yet he became the Prime Minister of Great Britain. As a boy, he stuttered when he talked, but as a man, he was one of the best speakers in history. As well as being a good soldier, he also (7)___ well enough to have his artwork displayed in museums. In addition to his other (8)___, Churchill was an (9)___. He wrote mostly history books, and he even won the Nobel Prize in (10)___.$p$, $c$["remarkable","thrifty","outrageous","infamous"]$c$::jsonb, 0, 6),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (7): Sir Winston Churchill was a (6)___ man. He was not a very good student, and yet he became the Prime Minister of Great Britain. As a boy, he stuttered when he talked, but as a man, he was one of the best speakers in history. As well as being a good soldier, he also (7)___ well enough to have his artwork displayed in museums. In addition to his other (8)___, Churchill was an (9)___. He wrote mostly history books, and he even won the Nobel Prize in (10)___.$p$, $c$["sung","fainted","wrote","painted"]$c$::jsonb, 3, 7),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (8): Sir Winston Churchill was a (6)___ man. He was not a very good student, and yet he became the Prime Minister of Great Britain. As a boy, he stuttered when he talked, but as a man, he was one of the best speakers in history. As well as being a good soldier, he also (7)___ well enough to have his artwork displayed in museums. In addition to his other (8)___, Churchill was an (9)___. He wrote mostly history books, and he even won the Nobel Prize in (10)___.$p$, $c$["troubles","worries","talents","hopes"]$c$::jsonb, 2, 8),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (9): Sir Winston Churchill was a (6)___ man. He was not a very good student, and yet he became the Prime Minister of Great Britain. As a boy, he stuttered when he talked, but as a man, he was one of the best speakers in history. As well as being a good soldier, he also (7)___ well enough to have his artwork displayed in museums. In addition to his other (8)___, Churchill was an (9)___. He wrote mostly history books, and he even won the Nobel Prize in (10)___.$p$, $c$["architect","artist","archeologist","author"]$c$::jsonb, 3, 9),
('5a4 - Context Clue','G5', $p$Choose the best word for blank (10): Sir Winston Churchill was a (6)___ man. He was not a very good student, and yet he became the Prime Minister of Great Britain. As a boy, he stuttered when he talked, but as a man, he was one of the best speakers in history. As well as being a good soldier, he also (7)___ well enough to have his artwork displayed in museums. In addition to his other (8)___, Churchill was an (9)___. He wrote mostly history books, and he even won the Nobel Prize in (10)___.$p$, $c$["science","literature","peace","politics"]$c$::jsonb, 1, 10),
('5a4 - Context Clue','G5', $p$Before the year 2000 started, the people in a panic about the Millennium Bug fought over the ______ amount of items in supermarkets.$p$, $c$["suspecting","limited","including","shocking"]$c$::jsonb, 1, 11),
('5a4 - Context Clue','G5', $p$The ______ is nice today - sunny and warm.$p$, $c$["suspect","cactus","sun","weather"]$c$::jsonb, 3, 12),
('5a4 - Context Clue','G5', $p$The detective ______ the mayor's son of having stolen the money from the safe.$p$, $c$["included","limited","suspected","wandered"]$c$::jsonb, 2, 13),
('5a4 - Context Clue','G5', $p$Although its appearance is harsh and dry, a ______ contains large amounts of water.$p$, $c$["weather","flower","cactus","suspect"]$c$::jsonb, 2, 14),
('5a4 - Context Clue','G5', $p$My sister wanted to be ______ in the game of Monopoly, but we did not let her join us.$p$, $c$["limited","suspected","included","committed"]$c$::jsonb, 2, 15),
('5a4 - Context Clue','G5', $p$Leonardo da Vinci created beautiful works of art and invented ______ things, such as a flying machine.$p$, $c$["literature","permanent","remarkable","coral"]$c$::jsonb, 2, 16),
('5a4 - Context Clue','G5', $p$The sunset ______ the sky with orange, red, and purple colors.$p$, $c$["remarked","wrote","read","painted"]$c$::jsonb, 3, 17),
('5a4 - Context Clue','G5', $p$Playing the piano well requires ______ and much effort.$p$, $c$["paint","talent","literature","object"]$c$::jsonb, 1, 18),
('5a4 - Context Clue','G5', $p$Hans Christian Andersen was the ______ of "The Little Mermaid."$p$, $c$["painter","literature","author","singer"]$c$::jsonb, 2, 19),
('5a4 - Context Clue','G5', $p$The Christmas Carol and Oliver Twist are famous works of ______ by Charles Dickens, one of the most productive English authors.$p$, $c$["paintings","talents","accounts","literature"]$c$::jsonb, 3, 20);

-- ---- 5a5  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a5 - Main Idea','G5', $p$Thousands of visitors tour Massachusetts each year. As a matter of fact, tourism is the second largest industry in the state. Massachusetts offers recreational, cultural, and historic attractions. Because of its coastal location, it is suited to all types of water sports. Additionally, musicians from all over the world perform at the Tanglewood Music Shed each summer.  This story mainly tells:$p$, $c$["why musicians go to Massachusetts","what attractions are offered in Massachusetts","that tourism doesn't lead industry in Massachusetts","why people like to travel"]$c$::jsonb, 1, 1),
('5a5 - Main Idea','G5', $p$Today, movies are shot on color film. They used to be shot on black and white film. Black and white movies are called classic because they are from a previous time period. Recently, people decided to add color to the classic films. Controversy arose because many people thought the films should remain as they were. They are reminders of our history.  This story mainly tells:$p$, $c$["why color film is better than black and white","where black and white films are shown","whether or not black and white movies should remain the same","how movies are now shot"]$c$::jsonb, 2, 2),
('5a5 - Main Idea','G5', $p$There are scientists who are trying to understand dolphins better. Dolphins are very smart, and they have their own language. They talk to one another by making noises. Scientists hope to understand the language, so that humans and dolphins will be able to talk to one another in the near future.  This story mainly tells:$p$, $c$["how smart dolphins are","how dolphins play games with people","why scientists are studying the language of dolphins","what kinds of noises dolphins make"]$c$::jsonb, 2, 3),
('5a5 - Main Idea','G5', $p$In August of 1933, the Oregon forests were destroyed. The great Tillamonk fire burned away 270,000 acres, amounting to the loss of almost twelve billion square feet of lumber. This is an outrageous amount when you consider that it is equal to the total amount of timber cut in all the forests of the United States in the year 1932.  This story mainly tells:$p$, $c$["where Tillamonk is located","what happened in 1932","how destructive the Tillamonk fire was","how the forest fire began"]$c$::jsonb, 2, 4),
('5a5 - Main Idea','G5', $p$Do you know how the funny bone got its name? The bone that goes from your shoulder to your elbow has a scientific name. It is called the humerus bone. The word humorous sounds exactly the same, but means funny. Somehow, the two words got mixed up.  This story mainly tells:$p$, $c$["how the funny bone got its name","why it isn't very funny when you bang your elbow against something","who made the mistake of confusing the names","what humorous means"]$c$::jsonb, 0, 5),
('5a5 - Main Idea','G5', $p$There are cameras that people use to see things the human eye cannot. Cameras that can zoom in on objects show us that no two snowflakes are alike. Cameras that take fast pictures show us that raindrops look more like a baseball than a teardrop.  This story mainly tells:$p$, $c$["how cameras work","how cameras can show us many things","why zooming was invented","why it is important to buy a good camera"]$c$::jsonb, 1, 6),
('5a5 - Main Idea','G5', $p$The idea of looking for fingerprints wasn't used by the police until Sir Francis Ealton began collecting them. Because of him the police learned that fingerprints could lead to the capturing of criminals. Sir Ealton lived in England, the first country that used fingerprints in police work.  This story mainly tells:$p$, $c$["how the use of fingerprints came about","how criminals can be caught","how to take a person's fingerprints","what fingers show"]$c$::jsonb, 0, 7),
('5a5 - Main Idea','G5', $p$Daniel Boone led settlers along the Wilderness Road. This is a trail that he had created in 1771, by slashing trees along the way. It went through the Cumberland Gap from Virginia to Kentucky.  This story mainly tells:$p$, $c$["what the Wilderness Road was","why Daniel Boone slashed trees","why it was called the Wilderness Trail","how many people crossed the trail"]$c$::jsonb, 0, 8),
('5a5 - Main Idea','G5', $p$Birthdays are celebrated differently around the world. In Mexico, children are blindfolded, and use a stick to break open a piñata. A piñata is made of paper and is stuffed with candy and small toys. In Thailand, children give gifts to other people in their lives.  This story mainly tells:$p$, $c$["how to make a piñata","how expensive a birthday is in Thailand","about the different ways to celebrate a birthday around the world","why birthdays are celebrated"]$c$::jsonb, 2, 9),
('5a5 - Main Idea','G5', $p$Do you know how the Dead Sea got its name? It is called the Dead Sea because no fish can live in the salty water. The Dead Sea has so much salt that even if you don't know how to swim, you can float. Nothing sinks in such salty water. The Dead Sea also happens to be the lowest place on earth.  This story mainly tells:$p$, $c$["about what fish need to survive","about who lives near the Dead Sea","about the Dead Sea","what happens in salty water"]$c$::jsonb, 2, 10);

-- ---- 5a6  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a6 - Main Idea','G5', $p$Over 14,000 years ago, bison, mammoths, wolves, and many other animals were trapped in a sticky tar pit. In the LaBrea Tar Pits, in Los Angeles, fossil collectors have uncovered a large number of these Ice Age animals. In fact, there are over 1,000 skulls of saber-toothed tigers and over 100,000 bones of many different kinds of birds.  This story mainly tells:$p$, $c$["which animals lived during the Ice Age","why animals got trapped in Los Angeles","how these fossils were found","what has been found in the LaBrea Tar Pits"]$c$::jsonb, 3, 1),
('5a6 - Main Idea','G5', $p$Here is some easy advice on how to avoid attracting mosquitoes and bees on your next picnic. Don't wear any perfume or bright, flowery clothing. Some insects and bees are attracted to perfume and will chase you thinking you are a flower. Other insects think that the bright colors on clothes and the flowery material are real flowers.  This story mainly tells:$p$, $c$["where to go on a picnic","how clothes and perfume attract bees and mosquitoes","what to eat at a picnic","how to fool an insect"]$c$::jsonb, 1, 2),
('5a6 - Main Idea','G5', $p$Many years ago, wolves and mountain lions hunted the wild horses that roamed the plains. Because the horses had a built-in fear of being attacked and killed by fangs or claws, they instinctively lashed out whenever something jumped on their backs. Mustangs are the descendants of these wild ancestors. Today, they also buck wildly whenever saddles or men go on their backs for the first time.  This story mainly tells:$p$, $c$["that mustangs are difficult to train","what makes mustangs buck wildly","that wild horses existed many years ago","that animals attacked wild horses"]$c$::jsonb, 1, 3),
('5a6 - Main Idea','G5', $p$Do you know how yogurt was discovered? Thousands of years ago a man was traveling through the desert. He put sheep's milk in a goatskin bag. The hot sun made the milk thick and sour. He was so hungry he took his chances, ate the yogurt, and liked it.  This story mainly tells:$p$, $c$["how the man was traveling","how to make yogurt","why yogurt tastes sour","how yogurt was discovered"]$c$::jsonb, 3, 4),
('5a6 - Main Idea','G5', $p$In the past, people thought lefties were witches. Lefties are people who write with their left hands. Scientists have concluded that none of this is true. In fact, lefties are possibly more creative than right-handed people.  This story mainly tells:$p$, $c$["what people thought of lefties","that lefties are witches","why lefties are more creative","why it is easier to be right-handed"]$c$::jsonb, 0, 5),
('5a6 - Main Idea','G5', $p$Dragonflies can't really tell who has been good and who has been bad. Long ago, people thought that dragonflies would hover around fish in the water so that the good kids could catch the fish. Meanwhile, if you were a bad kid who was fishing, you needed to watch out because the dragonfly would sting you.  This story mainly tells:$p$, $c$["that dragonflies are picky","what people thought of dragonflies long ago","how dragonflies are friendly to humans","what to do when you go fishing"]$c$::jsonb, 1, 6),
('5a6 - Main Idea','G5', $p$A sea potato isn't really a potato. It is reddish brown, but doesn't taste like a potato. Actually, it is an animal that likes cold water.  This story mainly tells:$p$, $c$["where to find a sea potato","why you should avoid sea potatoes","what a sea potato is","how the sea potato got its name"]$c$::jsonb, 2, 7),
('5a6 - Main Idea','G5', $p$In a zoo, penguins and polar bears are placed next to each other. But, in reality, penguins and polar bears live nowhere near each other. They are at opposite ends of the earth. Penguins live in the Antarctic, or the South Pole, and polar bears live in the Arctic, or the North Pole.  This story mainly tells:$p$, $c$["how polar bears and penguins get along","where polar bears and penguins live","how opposites may meet","that polar bears and penguins are near each other at the zoo"]$c$::jsonb, 1, 8),
('5a6 - Main Idea','G5', $p$There are stars in the sky called "dead stars." Dead stars are so-called because they used to shine, but have since used up all their gases. Now, they don't even twinkle.  This story mainly tells:$p$, $c$["what \"dead stars\" are","how long stars shine before they die","why stars die","what stars are like"]$c$::jsonb, 0, 9),
('5a6 - Main Idea','G5', $p$Long ago, roads had no names or numbers. People would often get lost while traveling. Most road signs only gave the name of the next town. When roads were given numbers and names, people stopped getting lost.  This story mainly tells:$p$, $c$["why roads had no names","when we started naming roads","how roads got their names","why we need signs"]$c$::jsonb, 2, 10);

-- ---- 5a7  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a7 - Main Idea','G5', $p$Do you know how zoos got started? In the Middle Ages, rich people put animals from around the world on display so that they could show off how much money they had. Soon, all people wanted to learn about these animals and didn't think it was fair that only the rich got to see them. The idea of showing animals to all, who wished to see them, started in this way.  This story mainly tells:$p$, $c$["where country zoos got started","what animals the rich people showed","how zoos got started","why only the rich had animals"]$c$::jsonb, 2, 1),
('5a7 - Main Idea','G5', $p$Everyone on earth has a different set of fingerprints. Experts can look at a person's hands and then at a set of fingerprints on a glass, and tell to whom the prints belong. Roses are the same way. The leaves on roses have tiny holes. Each leaf has its own pattern of holes, which is different from any other. Scientists can look at these holes and know what kind of rose it is.  This story mainly tells:$p$, $c$["how roses all look the same","how fingerprints are taken","how roses also have \"fingerprints\"","what the holes on the roses' leaves are called"]$c$::jsonb, 2, 2),
('5a7 - Main Idea','G5', $p$To get ready for winter, people buy sweaters, scarves, and gloves. Similarly, bears eat a lot to get a thick layer of fat. This layer of fat will be the only supply of food for the bear until spring. In winter, bears sleep for most of the day in caves and hollowed out tree trunks. The bears only come out on days that aren't so cold. In spring, when the bear leaves its cave, it is much thinner.  This story mainly tells:$p$, $c$["how a bear can sleep for days at a time","where bears can be found","why a bear gets fat for the winter","why bears are thinner in the springtime"]$c$::jsonb, 2, 3),
('5a7 - Main Idea','G5', $p$Take a pencil and make the smallest dot you can on this page. That dot is still a million times bigger than an atom. Atoms are the tiniest things on earth. You can only see atoms through a special microscope. Atoms are in everything. You are made of atoms.  This story mainly tells:$p$, $c$["how small atoms are","how big your pencil is","what atoms do","where to look for an atom"]$c$::jsonb, 0, 4),
('5a7 - Main Idea','G5', $p$Do your grandparents have white or gray hair? Do you know why? Hair gets its color from something called melanin. Dark hair has lots of melanin and blond hair has very little. When people get older, they lose the melanin and so their hair loses color and turns white or gray.  This story mainly tells:$p$, $c$["how much melanin people with brown hair have","why older people have white or gray hair","how to tell if you are about to get gray hair","at what age hair begins to turn gray"]$c$::jsonb, 1, 5),
('5a7 - Main Idea','G5', $p$When you write on your clothes, the ink doesn't come out in the wash, does it? When you write on your hand, though, the ink comes off when you wash it. This is because you lose a layer of skin every time you wash your skin. Don't worry. Skin is always shedding. If you wash off the layer with ink on it, another layer will grow in its place.  This story mainly tells:$p$, $c$["why it doesn't hurt when you lose a layer of skin","why people have different skin color","why ink comes off your skin","why ink ruins clothes"]$c$::jsonb, 2, 6),
('5a7 - Main Idea','G5', $p$Pluto is not just the name of Mickey Mouse's dog; it is also a planet. Pluto is the ninth planet in our solar system. It is the smallest and the coldest since it is so far away from the sun. Pluto is only eighteen hundred miles around! That means it is smaller than the moon.  This story mainly tells:$p$, $c$["what color Pluto is","who lives on Pluto","how Pluto got its name","about the size and distance of Pluto"]$c$::jsonb, 3, 7),
('5a7 - Main Idea','G5', $p$The myth of the phoenix tells of an enormous bird that made its own nest when it was five hundred years old. This extremely beautiful bird supposedly burned itself to death. From the ashes, a new phoenix was born. This phoenix was said to have collected the remains of his father's ashes and took them to the altar of the sun.  This story mainly tells:$p$, $c$["what was brought to the altar of the sun","how the phoenix built its own nest","why the phoenix died","the myth of the phoenix"]$c$::jsonb, 3, 8),
('5a7 - Main Idea','G5', $p$Snakes don't have a sense of hearing. Instead, they stick their tongues out to pick up vibrations in the air. This helps them locate things. They also use their tongues to detect smells and find food. The snake's tongue is not poisonous and it doesn't use its tongue to sting people.  This story mainly tells:$p$, $c$["where snakes can be found","how snakes use their tongues","why snakes bite and sting","what people think of snakes"]$c$::jsonb, 1, 9),
('5a7 - Main Idea','G5', $p$Avalanches, giant snow-slides, can be extremely dangerous. When the dry, loose snow lifts off the ground and swirls through the air, it is called an "airborne powder" avalanche, which can travel 1,000 miles an hour. "Dry snow" avalanches travel about twenty-five miles per hour, whereas "wet snow" avalanches average about fifteen miles per hour.  This story mainly tells:$p$, $c$["where avalanches occur","what to do if you get caught in an avalanche","how fast avalanches can travel","what happens in an \"airborne powder\" avalanche"]$c$::jsonb, 2, 10);

-- ---- 5a8  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a8 - Main Idea','G5', $p$Airplanes have made traveling so much easier than it used to be. Long ago, people would travel from country to country in ships. It would take weeks and, in some cases, months. Now, planes can take people from one end of the world to the other in eighteen hours. This means you spend less time traveling and more time doing fun things.  This story mainly tells:$p$, $c$["how airplanes made traveling easier","how airplanes are safer than cars","who travels on boats","how long it takes to travel the world"]$c$::jsonb, 0, 1),
('5a8 - Main Idea','G5', $p$There are some people who can't tell the difference between red and green. This is called partial color-blindness. This means people can't see certain colors. Then there are people who can't see any colors at all. These people only see in black, white, and gray. They are color-blind.  This story mainly tells:$p$, $c$["the difference between colors","how to fix color-blindness","why some people are color-blind","about color-blindness"]$c$::jsonb, 3, 2),
('5a8 - Main Idea','G5', $p$The United States Navy has been studying ocean currents for years. To help them determine the course and speed of a current, they insert letters written in various languages into sealed bottles. These bottles are then sent out to sea. The letters ask that the finders of these bottles notify the Navy of the time and place in which the bottle appeared. The information received is a valuable tool in preparing charts of ocean currents.  This story mainly tells:$p$, $c$["what is sealed in the bottles","how the Navy uses bottles in their study of ocean currents","when the bottles are released","what the U.S. Navy wrote in their letters"]$c$::jsonb, 1, 3),
('5a8 - Main Idea','G5', $p$One of the most famous national cemeteries in the United States is Arlington National Cemetery. Located in Arlington, Virginia, across the Potomac River from Washington, D.C., is land that once belonged to Robert E. Lee. President John F. Kennedy and William H. Taft, along with the tomb of the Unknown Soldiers of WWI, WWII, and the Korean War, can be found there.  This story mainly tells:$p$, $c$["how the bodies of unknown soldiers were discovered","where Arlington is located","why famous people are buried in Virginia","why Arlington National Cemetery is famous"]$c$::jsonb, 3, 4),
('5a8 - Main Idea','G5', $p$The famous composer, Wolfgang Mozart, was born in Salzburg, Austria. In his honor, every year since 1922, with the exception of the war years, a tremendous festival has been staged yearly. Mozart's music is the main focus at this festival. Approximately 90,000 spectators attend these summer concerts.  This story mainly tells:$p$, $c$["how often the festival is held","about the Salzburg festival","why the Austrians honor Mozart","how long the festival lasts"]$c$::jsonb, 1, 5),
('5a8 - Main Idea','G5', $p$Do you know why humans blink their eyes? When we blink our eyes, a layer of water refreshes them and clears away all dust. Blinking is an automatic response. It is something that we do to help ourselves without even realizing it.  This story mainly tells:$p$, $c$["the purpose of blinking","how often we blink","what happens if we don't blink","why we blink automatically"]$c$::jsonb, 0, 6),
('5a8 - Main Idea','G5', $p$For two weeks in February, the people of Quebec have a lot of fun. There are street dances, costume balls, sporting events, parades, and even ice-sculptures. Horse-drawn sleighs travel down the narrow, zigzagging streets, illuminated by colored streetlights.  This story mainly tells:$p$, $c$["why sculptures are made of ice","what the winter carnival is like in Quebec","why this Canadian carnival is held","who participates in the sporting events"]$c$::jsonb, 1, 7),
('5a8 - Main Idea','G5', $p$If you ever get tired of mowing the lawn, rent a goat. Goats love to eat grass. The goat gets a meal and you get a beautiful lawn without working for it.  This story mainly tells:$p$, $c$["where to rent a goat","how to cut your grass using a goat","why goats eat grass","how many people use goats as lawnmowers"]$c$::jsonb, 1, 8),
('5a8 - Main Idea','G5', $p$There is a two-pound radio that was invented by the Navy. It is so advanced that it can pinpoint the location of a pilot's plane that has gone down at sea, within one-tenth of a mile. In this way, a rescue craft can be sent down to almost the exact spot of the crash. Previously, the radios developed could only locate the general direction of the plane.  This story mainly tells:$p$, $c$["where to look for plane crashes","how the Navy trains its rescue pilots","how much this new radio weighs","how the new radio can help pilots in trouble"]$c$::jsonb, 3, 9),
('5a8 - Main Idea','G5', $p$Staying at home can be very dangerous. Studies show that more people are injured in homes than in mines, factories, or farms. It was found that home accidents occur because people are careless, and break the most common safety rules.  This story mainly tells:$p$, $c$["why people are careless","what to do to prevent an injury","that more accidents happen at home than anywhere else","how safety rules are broken"]$c$::jsonb, 2, 10);

-- ---- 5a9  Sequence ------------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a9 - Sequence','G5', $p$Choose the best order. A. The game of checkers has a long history. B. Checkerboards that are thousands of years old have been found in Egypt. C. People played it in country stores with their checkerboards balanced on the tops of cracker barrels. D. In America, it was once known as the "cracker-barrel game." E. It is believed that workers building the pyramids took time off to play the game.$p$, $c$["A-C-B-E-D","C-A-B-D-E","A-B-E-D-C","D-C-B-E-A"]$c$::jsonb, 2, 1),
('5a9 - Sequence','G5', $p$Choose the best order. A. One hundred and ten volts will shock a person, but not kill him unless the person is wet. B. Anything above a thousand volts is nearly always fatal. C. Higher power voltages are dangerous. 500 volts have killed many people. D. The two to six volts used in flashlights or car batteries won't harm people.$p$, $c$["D-B-C-A","B-C-A-D","D-A-C-B","B-C-D-A"]$c$::jsonb, 2, 2),
('5a9 - Sequence','G5', $p$Choose the best order. A. The level of the sea has been rising about six inches or so every hundred years. B. Thus, the land area of the world is becoming smaller. C. This will affect parts of such states as Delaware, Florida, New Jersey, Maryland, Virginia, and New York. D. If the level of the sea continues to rise, most of the coastal cities will disappear under water.$p$, $c$["C-B-A-D","A-D-B-C","C-D-B-A","A-B-D-C"]$c$::jsonb, 3, 3),
('5a9 - Sequence','G5', $p$Choose the best order. A. This was a tough gang chosen from the crew. B. Once aboard the ship, the victim was forced to "join" the British Navy. C. Their job was to go ashore and seize and kidnap any healthy-looking man they could find. D. Long ago, the British Navy needed sailors. In order to get enough of them, a navy captain had to use the press-gang.$p$, $c$["D-C-A-B","D-A-C-B","A-C-B-D","C-B-A-D"]$c$::jsonb, 1, 4),
('5a9 - Sequence','G5', $p$Choose the best order. A. The simple truth is that they can. At the General Electric research laboratories, carbon was put under a pressure of 800,000 pounds per square inch. B. They were not very pretty, but were diamonds nonetheless. C. The result was actual diamonds. These diamonds were not very large - only about the size of a grain of salt. D. Wouldn't it be wonderful if people could actually make diamonds?$p$, $c$["A-B-D-C","D-C-B-A","D-A-C-B","A-C-B-D"]$c$::jsonb, 2, 5),
('5a9 - Sequence','G5', $p$Choose the best order. A. Beneath each bust is a tablet bearing the person's name, dates of birth and death, and a quotation from the honored person. B. In this building, there is space for one hundred and fifty bronze busts between large granite columns. C. So far, ninety-two people have been elected to the Hall of Fame. D. The Hall of Fame in New York City honors the memory of great Americans.$p$, $c$["D-B-C-A","B-A-C-D","D-B-A-C","A-C-B-D"]$c$::jsonb, 2, 6);

-- ---- 5a10  Sequence -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a10 - Sequence','G5', $p$Choose the best order. A. On June 11, 1897, Solomon Andree and his companions attempted to fly over the North Pole in a balloon. B. Thirty-three years later, explorers discovered the frozen bodies of the balloonists, undeveloped film, and a journal. C. From this evidence, they learned that the balloon had been forced down. D. After journeying toward civilization for two and a half months, the explorers had died of starvation and cold.$p$, $c$["A-B-C-D","D-B-C-A","B-C-D-A","C-D-A-B"]$c$::jsonb, 0, 1),
('5a10 - Sequence','G5', $p$Choose the best order. A. These gems were identified with particular signs of the zodiac and later with the twelve months of the year. B. It was considered good fortune to wear a different stone for each month throughout the year. C. The custom of birthstones, associating certain gems with birthday months, may be traced back to Biblical times. D. Ancient people thought that some gems had magical powers. E. It wasn't until the 1700's that it became popular to wear only the stone of one's birth month.$p$, $c$["C-E-D-A-B","D-A-C-B-E","C-D-A-B-E","D-B-C-E-A"]$c$::jsonb, 2, 2),
('5a10 - Sequence','G5', $p$Choose the best order. A. One of the most famous of all guides was an Indian girl named Sacagawea, which means "bird woman." B. Sacagawea made friends with the Indians along the way and persuaded them to assist the expedition. C. Strangely enough, no one seems to know where or when the famous Sacagawea died. D. She helped guide the Lewis and Clark expedition from the Mississippi River to the Pacific Ocean and back again.$p$, $c$["A-D-B-C","B-A-D-C","C-A-B-D","D-A-B-C"]$c$::jsonb, 0, 3),
('5a10 - Sequence','G5', $p$Choose the best order. A. These capital letters are the initial letters of the full names. B. Newspaper and magazine reports these days are filled with the names of organizations or projects made up of capital letters. C. Acro is a Greek word, which means "high points" or "high places." Nym means "name." The capital letters are the high points in a name. D. These letter-names are called acronyms for an interesting reason.$p$, $c$["C-D-B-A","B-A-D-C","D-C-A-B","A-B-D-C"]$c$::jsonb, 1, 4),
('5a10 - Sequence','G5', $p$Choose the best order. A. Whether you use one method or the other, the meaning you give to a word must make sense in the passage you are reading. B. The second is through the use of word parts. C. You have learned two ways to figure out new meanings. D. The first is through the use of context clues.$p$, $c$["C-D-B-A","D-B-A-C","C-A-D-B","D-A-B-C"]$c$::jsonb, 0, 5),
('5a10 - Sequence','G5', $p$Choose the best order. A. For protection against fires caused by overloading a circuit, a circuit breaker is used. B. This protects your home from a fire. C. When electron flow is too heavy, a circuit is overloaded. D. When there is no more danger and when the trouble has been fixed, you can switch the circuit breaker on again. E. A circuit breaker has a switch that automatically opens when a circuit is overloaded.$p$, $c$["A-E-D-B-C","E-C-B-D-A","C-B-A-E-D","C-A-E-B-D"]$c$::jsonb, 3, 6);

-- ---- 5a11  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a11 - Inference','G5', $p$Alex and Calvin are going to the batting cage. Alex is really good at hitting the balls. This is the first time Calvin is at a batting range. After Calvin takes his first swing at a ball, Alex says, "Don't worry, it took me a long time to get it right, too." Which is probably true?$p$, $c$["Alex is not good at teaching.","Calvin was so mad that he threw his bat on the ground.","Calvin didn't hit the ball the first time.","Calvin does many things with Alex."]$c$::jsonb, 2, 1),
('5a11 - Inference','G5', $p$Mitch and Austin finally saw a motel that had a vacancy sign in the window. They stopped and got the last two rooms. Mitch was so happy and said, "I am so tired of driving that I don't want to see another highway for a whole year." Which is probably true?$p$, $c$["The men had been traveling for hours.","The highway was too bumpy.","There was no vacancy at another motel.","Driving doesn't please Austin."]$c$::jsonb, 0, 2),
('5a11 - Inference','G5', $p$Denise was baby-sitting her neighbor's six-year-old girl. Denise was putting her to bed when she asked Denise to tell her a story. Denise said, "I'll tell you one my mom used to tell me, and it would put me to sleep." After ten minutes, Denise said, "Wow! It really works." Which is probably true?$p$, $c$["The little girl fell asleep before Denise even told her the story.","The little girl wanted to hear another story.","The story told by Denise made the girl fall asleep.","Denise became drowsy after ten minutes."]$c$::jsonb, 2, 3),
('5a11 - Inference','G5', $p$Erica had just met her new neighbor. Her neighbor had told her what Canada was like and how the people there lived. Erica told her family at dinner what her new friend had said. Which is probably true?$p$, $c$["Erica's family was going to invite the neighbor over for dinner.","Erica was intrigued by Canada.","The neighbor is from Canada.","Erica's new neighbor told her a shocking story."]$c$::jsonb, 2, 4),
('5a11 - Inference','G5', $p$Charles decided to go surfing after watching professional surfers surf for two hours. Charles only lasted one minute after he started surfing. He told his friend, "Don't laugh. It isn't as easy as you think." Which is probably true?$p$, $c$["Charles's friend is a professional surfer.","Charles's friend couldn't surf well, either.","Charles wasn't able to surf as well as the professional surfers.","Charles was compatible with the professional surfer."]$c$::jsonb, 2, 5);

-- ---- 5a12  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('5a12 - Inference','G5', $p$Sally went to bed very upset. Tomorrow was the school's outdoor talent show, but rain was predicted. She memorized her routine thoroughly. Her mother said, "Don't be vexed. Maybe the weatherman is wrong." Which is probably true?$p$, $c$["Sally only likes sunny weather.","Her mom was ridiculing Sally.","Sally had been practicing and wanted to show her talent.","Sally organized the outdoor talent show by herself."]$c$::jsonb, 2, 1),
('5a12 - Inference','G5', $p$Tom scheduled an audition for a role in a movie. His watch said it was two o'clock, and his audition was at three o'clock. Tom decided to stop at the deli and get a sandwich. When he got to the audition, the lady said he was too late. It was four! Which is probably true?$p$, $c$["Tom was neglectful about the audition.","Tom overslept in the morning.","The audition was set up incorrectly.","Tom's watch wasn't working properly."]$c$::jsonb, 3, 2),
('5a12 - Inference','G5', $p$"Wow," thought Ms. Jenkins, "I must be really old. I thought a 'byte' was what you took from food. This computer class isn't for me." Which is probably true?$p$, $c$["Ms. Jenkins was a teacher.","Ms. Jenkins was seventy years old.","Ms. Jenkins had very little knowledge about computers.","Ms. Jenkins could never learn how to use the computer no matter how hard she tried."]$c$::jsonb, 2, 3),
('5a12 - Inference','G5', $p$In the park on Monday, a race will take place. The winner of the race gets a high-speed bicycle. Brett has been preparing for two weeks. He can't wait to ride his new bicycle home. Which is probably true?$p$, $c$["Brett doesn't know about Max, who runs faster than he does.","Brett is confident that he will win.","Brett can run faster than a car.","The bicycle has a black, steel body."]$c$::jsonb, 1, 4),
('5a12 - Inference','G5', $p$"My dad doesn't allow us to use his office computer for playing computer games," said John. "My dad just made up that rule in our house, too. Last week, he made the mistake of letting my younger brother, Daniel, use it," said Chris. Which is probably true?$p$, $c$["John and Chris have old-fashioned fathers.","Daniel ruined his dad's computer.","John's dad's computer is the best there is.","Chris and John are content with the new rule at home."]$c$::jsonb, 1, 5);
