-- ============================================================================
-- Duke College — question bank: The Learning Gate, Reading Skill (LG-R-RS-3a)
-- 12 worksheets / 146 questions. Run AFTER setup.sql (and the 2a bank if used).
-- This file only ADDS questions; it does not delete existing ones.
-- correct_index is 0-based. Answers were generated for you; please spot-check.
-- ============================================================================

-- ---- 3a1  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a1 - Context Clue','G3', $p$Choose the best word for blank (1): Rivers are not all the same color. In some cases, the color of a river is (1)___ by the river (2)___. It may be (3)___ to the color of its (4)___, which a river (5)___. The river color may be caused by what is found in the water.$p$, $c$["caused","marched","decided","divided"]$c$::jsonb, 0, 1),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (2): Rivers are not all the same color. In some cases, the color of a river is (1)___ by the river (2)___. It may be (3)___ to the color of its (4)___, which a river (5)___. The river color may be caused by what is found in the water.$p$, $c$["tail","bottom","length","direction"]$c$::jsonb, 1, 2),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (3): Rivers are not all the same color. In some cases, the color of a river is (1)___ by the river (2)___. It may be (3)___ to the color of its (4)___, which a river (5)___. The river color may be caused by what is found in the water.$p$, $c$["added","alike","mixed","due"]$c$::jsonb, 3, 3),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (4): Rivers are not all the same color. In some cases, the color of a river is (1)___ by the river (2)___. It may be (3)___ to the color of its (4)___, which a river (5)___. The river color may be caused by what is found in the water.$p$, $c$["fish","banks","moments","hour"]$c$::jsonb, 1, 4),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (5): Rivers are not all the same color. In some cases, the color of a river is (1)___ by the river (2)___. It may be (3)___ to the color of its (4)___, which a river (5)___. The river color may be caused by what is found in the water.$p$, $c$["flows","intends","reflects","freezes"]$c$::jsonb, 2, 5),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (6): When you heat water in a pan, the water at the (6)___ of the pan gets warm first. This warm water expands. As it rises, the cooler water (7)___ down and takes its place. When it is heated, it moves up. This (8)___ again and again until all the water in the pan is (9)___. The heat (10)___ from one place to another in the pan.$p$, $c$["top","lid","handle","bottom"]$c$::jsonb, 3, 6),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (7): When you heat water in a pan, the water at the (6)___ of the pan gets warm first. This warm water expands. As it rises, the cooler water (7)___ down and takes its place. When it is heated, it moves up. This (8)___ again and again until all the water in the pan is (9)___. The heat (10)___ from one place to another in the pan.$p$, $c$["rises","sinks","increases","cools"]$c$::jsonb, 1, 7),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (8): When you heat water in a pan, the water at the (6)___ of the pan gets warm first. This warm water expands. As it rises, the cooler water (7)___ down and takes its place. When it is heated, it moves up. This (8)___ again and again until all the water in the pan is (9)___. The heat (10)___ from one place to another in the pan.$p$, $c$["rises","rips","happens","lands"]$c$::jsonb, 2, 8),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (9): When you heat water in a pan, the water at the (6)___ of the pan gets warm first. This warm water expands. As it rises, the cooler water (7)___ down and takes its place. When it is heated, it moves up. This (8)___ again and again until all the water in the pan is (9)___. The heat (10)___ from one place to another in the pan.$p$, $c$["flushed","crushed","heated","angry"]$c$::jsonb, 2, 9),
('3a1 - Context Clue','G3', $p$Choose the best word for blank (10): When you heat water in a pan, the water at the (6)___ of the pan gets warm first. This warm water expands. As it rises, the cooler water (7)___ down and takes its place. When it is heated, it moves up. This (8)___ again and again until all the water in the pan is (9)___. The heat (10)___ from one place to another in the pan.$p$, $c$["swims","crawls","heaps","flows"]$c$::jsonb, 3, 10),
('3a1 - Context Clue','G3', $p$There are many living things on the ______ of the sea.$p$, $c$["bottom","end","heat","flu"]$c$::jsonb, 0, 11),
('3a1 - Context Clue','G3', $p$Wind ______ from the east.$p$, $c$["skips","sinks","flows","happens"]$c$::jsonb, 2, 12),
('3a1 - Context Clue','G3', $p$______ to the snowstorm, schools were closed.$p$, $c$["Since","Due","Cause","In"]$c$::jsonb, 1, 13),
('3a1 - Context Clue','G3', $p$People often have picnics around the ______ of the river because it is pretty.$p$, $c$["shapes","cause","bottom","banks"]$c$::jsonb, 3, 14),
('3a1 - Context Clue','G3', $p$I can see my own face because the mirror ______ it.$p$, $c$["causes","reflects","draws","moves"]$c$::jsonb, 1, 15),
('3a1 - Context Clue','G3', $p$A cold is ______ by germs attacking the body.$p$, $c$["caused","discovered","reflected","killed"]$c$::jsonb, 0, 16),
('3a1 - Context Clue','G3', $p$A chunk of lead ______ in water.$p$, $c$["melts","heats","sinks","happens"]$c$::jsonb, 2, 17),
('3a1 - Context Clue','G3', $p$What would ______ if the dinosaurs came back?$p$, $c$["stop","happen","heat","flow"]$c$::jsonb, 1, 18),
('3a1 - Context Clue','G3', $p$When metal is ______, it grows bigger.$p$, $c$["frozen","flown","happened","heated"]$c$::jsonb, 3, 19),
('3a1 - Context Clue','G3', $p$Scientists recently discovered that there are creatures on the ______ of the Pacific Ocean, which has deadly gases and heat.$p$, $c$["sides","causes","bottom","sands"]$c$::jsonb, 2, 20);

-- ---- 3a2  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a2 - Context Clue','G3', $p$Choose the best word for blank (1): When you water your plants, don't use icy water. Water that is (1)___ very hot nor very cold is best. Try not to wet the leaves. It is best to water (2)___ in the day, (3)___ plants lose their (4)___ more rapidly (5)___ daylight hours.$p$, $c$["certainly","also","neither","always"]$c$::jsonb, 2, 1),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (2): When you water your plants, don't use icy water. Water that is (1)___ very hot nor very cold is best. Try not to wet the leaves. It is best to water (2)___ in the day, (3)___ plants lose their (4)___ more rapidly (5)___ daylight hours.$p$, $c$["way","mostly","early","nicely"]$c$::jsonb, 2, 2),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (3): When you water your plants, don't use icy water. Water that is (1)___ very hot nor very cold is best. Try not to wet the leaves. It is best to water (2)___ in the day, (3)___ plants lose their (4)___ more rapidly (5)___ daylight hours.$p$, $c$["sometimes","since","but","so"]$c$::jsonb, 1, 3),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (4): When you water your plants, don't use icy water. Water that is (1)___ very hot nor very cold is best. Try not to wet the leaves. It is best to water (2)___ in the day, (3)___ plants lose their (4)___ more rapidly (5)___ daylight hours.$p$, $c$["moisture","lives","exercise","damp"]$c$::jsonb, 0, 4),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (5): When you water your plants, don't use icy water. Water that is (1)___ very hot nor very cold is best. Try not to wet the leaves. It is best to water (2)___ in the day, (3)___ plants lose their (4)___ more rapidly (5)___ daylight hours.$p$, $c$["while","during","before","after"]$c$::jsonb, 1, 5),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (6): In the spring, a tree needs (6)___ of water and other (7)___. The tree grows quickly. During this period of (8)___ development, the wood in the trunk grows in a light color. But during the late summer, when the tree's (9)___ is slow, the wood grows dark. Each pair of rings (10)___ one year in the life of the tree.$p$, $c$["many","size","solids","plenty"]$c$::jsonb, 3, 6),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (7): In the spring, a tree needs (6)___ of water and other (7)___. The tree grows quickly. During this period of (8)___ development, the wood in the trunk grows in a light color. But during the late summer, when the tree's (9)___ is slow, the wood grows dark. Each pair of rings (10)___ one year in the life of the tree.$p$, $c$["soils","animals","nutrients","people"]$c$::jsonb, 2, 7),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (8): In the spring, a tree needs (6)___ of water and other (7)___. The tree grows quickly. During this period of (8)___ development, the wood in the trunk grows in a light color. But during the late summer, when the tree's (9)___ is slow, the wood grows dark. Each pair of rings (10)___ one year in the life of the tree.$p$, $c$["pausing","rapid","tiny","mechanical"]$c$::jsonb, 1, 8),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (9): In the spring, a tree needs (6)___ of water and other (7)___. The tree grows quickly. During this period of (8)___ development, the wood in the trunk grows in a light color. But during the late summer, when the tree's (9)___ is slow, the wood grows dark. Each pair of rings (10)___ one year in the life of the tree.$p$, $c$["document","doctor","development","dining"]$c$::jsonb, 2, 9),
('3a2 - Context Clue','G3', $p$Choose the best word for blank (10): In the spring, a tree needs (6)___ of water and other (7)___. The tree grows quickly. During this period of (8)___ development, the wood in the trunk grows in a light color. But during the late summer, when the tree's (9)___ is slow, the wood grows dark. Each pair of rings (10)___ one year in the life of the tree.$p$, $c$["hides","discovers","mows","equals"]$c$::jsonb, 3, 10),
('3a2 - Context Clue','G3', $p$The test was ______ too hard nor easy; it was fair.$p$, $c$["early","neither","during","also"]$c$::jsonb, 1, 11),
('3a2 - Context Clue','G3', $p$In order to increase strength and energy, people must get proper nutrients and plenty of ______.$p$, $c$["developments","exercise","sugar","plants"]$c$::jsonb, 1, 12),
('3a2 - Context Clue','G3', $p$Two plus five ______ seven.$p$, $c$["divides","plenty","equals","memorizes"]$c$::jsonb, 2, 13),
('3a2 - Context Clue','G3', $p$______ is needed for keeping the skin soft.$p$, $c$["Lunch","Moisture","Test","Early"]$c$::jsonb, 1, 14),
('3a2 - Context Clue','G3', $p$No one is allowed to talk ______ the test.$p$, $c$["during","within","neither","since"]$c$::jsonb, 0, 15),
('3a2 - Context Clue','G3', $p$Going to bed ______ is better for children's health.$p$, $c$["forever","early","late","someday"]$c$::jsonb, 1, 16),
('3a2 - Context Clue','G3', $p$______, such as vitamin C, help the cells in our bodies to be healthy.$p$, $c$["Developments","Minerals","Metals","Nutrients"]$c$::jsonb, 3, 17),
('3a2 - Context Clue','G3', $p$When it is time for high tide, the level of ocean water increases ______.$p$, $c$["rapidly","equally","plenty","closely"]$c$::jsonb, 0, 18),
('3a2 - Context Clue','G3', $p$Education is important for the ______ of our minds.$p$, $c$["nutrients","development","automobiles","shadows"]$c$::jsonb, 1, 19),
('3a2 - Context Clue','G3', $p$We didn't want to see that movie today, ______ we had already seen it yesterday.$p$, $c$["always","but","since","only"]$c$::jsonb, 2, 20);

-- ---- 3a3  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a3 - Context Clue','G3', $p$Choose the best word for blank (1): People have used the energy from the wind for centuries. (1)___ were used to catch the wind and move ships. Sailboats are still used today, but (2)___ for recreation. The wind also was used to turn the blades of windmills to make (3)___. Once this energy was used to (4)___ wheat and corn into grain. Now, windmills are used to (5)___ water from under the ground.$p$, $c$["Energies","Feelings","Cabin","Sails"]$c$::jsonb, 3, 1),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (2): People have used the energy from the wind for centuries. (1)___ were used to catch the wind and move ships. Sailboats are still used today, but (2)___ for recreation. The wind also was used to turn the blades of windmills to make (3)___. Once this energy was used to (4)___ wheat and corn into grain. Now, windmills are used to (5)___ water from under the ground.$p$, $c$["foolishly","never","only","equally"]$c$::jsonb, 2, 2),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (3): People have used the energy from the wind for centuries. (1)___ were used to catch the wind and move ships. Sailboats are still used today, but (2)___ for recreation. The wind also was used to turn the blades of windmills to make (3)___. Once this energy was used to (4)___ wheat and corn into grain. Now, windmills are used to (5)___ water from under the ground.$p$, $c$["flower","cake","flour","wheat"]$c$::jsonb, 2, 3),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (4): People have used the energy from the wind for centuries. (1)___ were used to catch the wind and move ships. Sailboats are still used today, but (2)___ for recreation. The wind also was used to turn the blades of windmills to make (3)___. Once this energy was used to (4)___ wheat and corn into grain. Now, windmills are used to (5)___ water from under the ground.$p$, $c$["combine","grind","divide","try"]$c$::jsonb, 1, 4),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (5): People have used the energy from the wind for centuries. (1)___ were used to catch the wind and move ships. Sailboats are still used today, but (2)___ for recreation. The wind also was used to turn the blades of windmills to make (3)___. Once this energy was used to (4)___ wheat and corn into grain. Now, windmills are used to (5)___ water from under the ground.$p$, $c$["push","plant","pour","pull"]$c$::jsonb, 3, 5),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (6): Plumbers put in the (6)___. Other men put (7)___ into the walls and ceiling. (8)___ runs through these wires to make the lights, radio, and the television set (9)___. Still other workers cover the inside walls with a hard white (10)___ called plaster.$p$, $c$["chains","pipes","leads","books"]$c$::jsonb, 1, 6),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (7): Plumbers put in the (6)___. Other men put (7)___ into the walls and ceiling. (8)___ runs through these wires to make the lights, radio, and the television set (9)___. Still other workers cover the inside walls with a hard white (10)___ called plaster.$p$, $c$["pictures","cars","papers","wires"]$c$::jsonb, 3, 7),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (8): Plumbers put in the (6)___. Other men put (7)___ into the walls and ceiling. (8)___ runs through these wires to make the lights, radio, and the television set (9)___. Still other workers cover the inside walls with a hard white (10)___ called plaster.$p$, $c$["Water","Insects","Electricity","Heat"]$c$::jsonb, 2, 8),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (9): Plumbers put in the (6)___. Other men put (7)___ into the walls and ceiling. (8)___ runs through these wires to make the lights, radio, and the television set (9)___. Still other workers cover the inside walls with a hard white (10)___ called plaster.$p$, $c$["save","work","right","paper"]$c$::jsonb, 1, 9),
('3a3 - Context Clue','G3', $p$Choose the best word for blank (10): Plumbers put in the (6)___. Other men put (7)___ into the walls and ceiling. (8)___ runs through these wires to make the lights, radio, and the television set (9)___. Still other workers cover the inside walls with a hard white (10)___ called plaster.$p$, $c$["material","rock","snow","clay"]$c$::jsonb, 0, 10),
('3a3 - Context Clue','G3', $p$Telegraph signals are sent through ______.$p$, $c$["materials","wires","works","rocks"]$c$::jsonb, 1, 11),
('3a3 - Context Clue','G3', $p$Medicine must be taken ______ when a person is sick, not when he or she is well.$p$, $c$["before","never","grind","only"]$c$::jsonb, 3, 12),
('3a3 - Context Clue','G3', $p$There are machines that ______ coffee beans to make ground coffee.$p$, $c$["grind","pull","freeze","melt"]$c$::jsonb, 0, 13),
('3a3 - Context Clue','G3', $p$______ must not be left out when making noodles.$p$, $c$["Flour","Sails","Sinks","Refrigerator"]$c$::jsonb, 0, 14),
('3a3 - Context Clue','G3', $p$People ______ their coats and hats tightly toward themselves on a cold, windy day.$p$, $c$["grind","pull","sail","anger"]$c$::jsonb, 1, 15),
('3a3 - Context Clue','G3', $p$A ______ is a hollow cylinder or tube used as a passage way for water, heat, or gas.$p$, $c$["wire","material","pipe","shell"]$c$::jsonb, 2, 16),
('3a3 - Context Clue','G3', $p$Triangular ______ help sailboats move by catching the wind.$p$, $c$["slices","sails","flours","trees"]$c$::jsonb, 1, 17),
('3a3 - Context Clue','G3', $p$______ is needed to turn on radios, television, and refrigerators.$p$, $c$["Pipe","Wound","Model","Electricity"]$c$::jsonb, 3, 18),
('3a3 - Context Clue','G3', $p$To make a computer ______, we need to use it properly.$p$, $c$["wire","work","mind","follow"]$c$::jsonb, 1, 19),
('3a3 - Context Clue','G3', $p$Pens, pencils, and markers are writing ______.$p$, $c$["works","crayons","drawers","materials"]$c$::jsonb, 3, 20);

-- ---- 3a4  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a4 - Context Clue','G3', $p$Choose the best word for blank (1): Nutrients that build and repair the body are called proteins. All living things are (1)___ of cells. Each day millions of (2)___ in your body die. But each day the body makes (3)___ of new cells. Your body needs protein to do this. (4)___ is especially important to you because you are still growing. Meat, fish, eggs, and milk have protein. So do (5)___ butter and peas.$p$, $c$["made up","marked up","mowed down","mind"]$c$::jsonb, 0, 1),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (2): Nutrients that build and repair the body are called proteins. All living things are (1)___ of cells. Each day millions of (2)___ in your body die. But each day the body makes (3)___ of new cells. Your body needs protein to do this. (4)___ is especially important to you because you are still growing. Meat, fish, eggs, and milk have protein. So do (5)___ butter and peas.$p$, $c$["closets","cells","colors","crayons"]$c$::jsonb, 1, 2),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (3): Nutrients that build and repair the body are called proteins. All living things are (1)___ of cells. Each day millions of (2)___ in your body die. But each day the body makes (3)___ of new cells. Your body needs protein to do this. (4)___ is especially important to you because you are still growing. Meat, fish, eggs, and milk have protein. So do (5)___ butter and peas.$p$, $c$["tens","thousands","millions","ones"]$c$::jsonb, 2, 3),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (4): Nutrients that build and repair the body are called proteins. All living things are (1)___ of cells. Each day millions of (2)___ in your body die. But each day the body makes (3)___ of new cells. Your body needs protein to do this. (4)___ is especially important to you because you are still growing. Meat, fish, eggs, and milk have protein. So do (5)___ butter and peas.$p$, $c$["Iron","Vitamins","Cells","Protein"]$c$::jsonb, 3, 4),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (5): Nutrients that build and repair the body are called proteins. All living things are (1)___ of cells. Each day millions of (2)___ in your body die. But each day the body makes (3)___ of new cells. Your body needs protein to do this. (4)___ is especially important to you because you are still growing. Meat, fish, eggs, and milk have protein. So do (5)___ butter and peas.$p$, $c$["yellow","soft","peanut","walnut"]$c$::jsonb, 2, 5),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (6): In the cold North, the Eskimos build their houses (6)___ stone and earth. In the winter when Eskimos go on (7)___ trips, they make (8)___ kind of house. They make it out of snow. It is called an (9)___. Snow is the only building material they have in the (10)___.$p$, $c$["inside of","out of","under","over"]$c$::jsonb, 1, 6),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (7): In the cold North, the Eskimos build their houses (6)___ stone and earth. In the winter when Eskimos go on (7)___ trips, they make (8)___ kind of house. They make it out of snow. It is called an (9)___. Snow is the only building material they have in the (10)___.$p$, $c$["automobile","hunting","airplane","country"]$c$::jsonb, 1, 7),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (8): In the cold North, the Eskimos build their houses (6)___ stone and earth. In the winter when Eskimos go on (7)___ trips, they make (8)___ kind of house. They make it out of snow. It is called an (9)___. Snow is the only building material they have in the (10)___.$p$, $c$["same","typical","kind","another"]$c$::jsonb, 3, 8),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (9): In the cold North, the Eskimos build their houses (6)___ stone and earth. In the winter when Eskimos go on (7)___ trips, they make (8)___ kind of house. They make it out of snow. It is called an (9)___. Snow is the only building material they have in the (10)___.$p$, $c$["ice house","ice truck","igloo","ice shelter"]$c$::jsonb, 2, 9),
('3a4 - Context Clue','G3', $p$Choose the best word for blank (10): In the cold North, the Eskimos build their houses (6)___ stone and earth. In the winter when Eskimos go on (7)___ trips, they make (8)___ kind of house. They make it out of snow. It is called an (9)___. Snow is the only building material they have in the (10)___.$p$, $c$["winter","summer","fall","spring"]$c$::jsonb, 0, 10),
('3a4 - Context Clue','G3', $p$Paper is ______ of wood pulp.$p$, $c$["millions","made up","proteins","locals"]$c$::jsonb, 1, 11),
('3a4 - Context Clue','G3', $p$Scientists believe that dinosaurs existed on the earth ______ of years ago.$p$, $c$["thousands","proteins","cells","millions"]$c$::jsonb, 3, 12),
('3a4 - Context Clue','G3', $p$Every living thing has ______.$p$, $c$["millions","peanuts","cells","legs"]$c$::jsonb, 2, 13),
('3a4 - Context Clue','G3', $p$People who don't eat meat eat beans and nuts for ______.$p$, $c$["peanuts","presents","protein","plural"]$c$::jsonb, 2, 14),
('3a4 - Context Clue','G3', $p$The ______ butter and jelly sandwich is one of the most popular snacks and lunches in America.$p$, $c$["protein","white","peanut","wine"]$c$::jsonb, 2, 15),
('3a4 - Context Clue','G3', $p$Gingerbread houses are made ______ graham crackers and candies.$p$, $c$["igloo","out of","winter","over of"]$c$::jsonb, 1, 16),
('3a4 - Context Clue','G3', $p$Ancient humans went out ______ for food.$p$, $c$["winter","building","dieting","hunting"]$c$::jsonb, 3, 17),
('3a4 - Context Clue','G3', $p$I can't have ______ piece of cake because my stomach is full.$p$, $c$["hunting","another","rare","kind"]$c$::jsonb, 1, 18),
('3a4 - Context Clue','G3', $p$Eskimos live in ______.$p$, $c$["igloos","winters","teepees","trains"]$c$::jsonb, 0, 19),
('3a4 - Context Clue','G3', $p$______ is the season between autumn and spring.$p$, $c$["Igloo","Hunting","Winter","Summer"]$c$::jsonb, 2, 20);

-- ---- 3a5  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a5 - Main Idea','G3', $p$If you get a new pet fish, you have to make sure that you do not shock it. A sudden change in temperature is bad for the fish. When you bring it home, let your carrying bag float in your fish tank for fifteen minutes. The water in the bag will become the same temperature as the water in your tank. Now, you can slowly let the fish out into the tank water.  This story mainly tells:$p$, $c$["how to shock your fish","why temperature changes","how to care for your new fish"]$c$::jsonb, 2, 1),
('3a5 - Main Idea','G3', $p$Steven made his living by fooling people. He would make believe that he was a pilot, a doctor, a teacher, or even a millionaire. Finally, when Steven was 21 years old, the police caught him and took him to jail. Now, Steven cannot fool anyone ever again.  This story mainly tells:$p$, $c$["how you can fool people","how Steven even fooled the police","how Steven was sent to jail"]$c$::jsonb, 2, 2),
('3a5 - Main Idea','G3', $p$Seashells are like rainbows in the ocean. They can grow up to four feet long. The smallest shells are only a half inch long. Some shells have two sides that open like wings. Others are shaped like curling tubes. Shells come in many different shapes, sizes, and colors.  This story mainly tells:$p$, $c$["which are the prettiest shells","about different shells","what colors seashells come in"]$c$::jsonb, 1, 3),
('3a5 - Main Idea','G3', $p$Glass bottles were first made about 3,000 years ago. The earliest bottles were made by hand. People blew them into different shapes. Long iron tubes were used to blow the glass. Children learned how to blow glass from their parents. Today, in some places, you can still see glass being blown by hand.  This story mainly tells:$p$, $c$["how glass bottles were made","how long it takes to make a glass bottle","where to find hand-made glass bottles"]$c$::jsonb, 0, 4),
('3a5 - Main Idea','G3', $p$At first, Christmas trees were plain. Then, people began to put things like apples and cookies on them. Later, they hung candies, bells, dolls, colored glass balls, and tinsel on their trees. Nowadays, Christmas trees are often not real. They also are not always green. Sometimes they are white, pink, or even silver.  This story mainly tells:$p$, $c$["how pink trees are more beautiful than green trees","how Christmas trees have changed","why people hang lights on trees"]$c$::jsonb, 1, 5),
('3a5 - Main Idea','G3', $p$When Sally turned five, her father came home with a big wrapped box. "This is a present for your birthday, Sally." It was a shiny, red tricycle with a white basket and a horn. Sally rode it every day for weeks and weeks.  This story mainly tells:$p$, $c$["about Sally's birthday present","how old Sally is","how Sally really wished for a bicycle"]$c$::jsonb, 0, 6),
('3a5 - Main Idea','G3', $p$Schools today are different from those of 100 years ago. In the old days, children went to a one-room schoolhouse. Today, schools are large buildings with many rooms. Electric lights are used instead of the old-fashioned candles.  This story mainly tells:$p$, $c$["about what is taught in class","how much children enjoy learning","how schools have changed"]$c$::jsonb, 2, 7),
('3a5 - Main Idea','G3', $p$Jungle life is very hard. The hot sun beats down on you. The damp jungle floor causes all kinds of diseases. Water must be boiled. Poisonous insects and snakes are everywhere.  This story mainly tells:$p$, $c$["how much fun it is to live in the jungle","how hard it is to live in the jungle","what the jungle's weather is like"]$c$::jsonb, 1, 8),
('3a5 - Main Idea','G3', $p$An alligator is sly and tricky. He pretends that he is sleeping near a riverbank. Then, as soon as something comes by him, he jumps into action. He strikes out with his tail, then crushes his next meal with his huge jaw.  This story mainly tells:$p$, $c$["why an alligator sleeps","what alligators eat","how an alligator catches his food"]$c$::jsonb, 2, 9),
('3a5 - Main Idea','G3', $p$People in China have flown kites for many, many years. For the Chinese, the 9th day of every month is Kites' Day. Thousands of kites shaped like dragons, fish, and butterflies float over cities and towns.  This story mainly tells:$p$, $c$["what kites are made of","how the Chinese love kites","how to fly a kite"]$c$::jsonb, 1, 10);

-- ---- 3a6  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a6 - Main Idea','G3', $p$Pecos Bill was a super cowboy. He got his name from the Pecos River in Texas. When he was a little boy, he fell off his family's wagon. He was raised by coyotes. He grew up to be the leader of one of the toughest groups.  This story mainly tells:$p$, $c$["what happened to Pecos' family","what it was like to live in Texas","who Pecos Bill was"]$c$::jsonb, 2, 1),
('3a6 - Main Idea','G3', $p$An octopus isn't fast enough to swim after a fish. It must wait for a fish to swim by it. When the fish finally swims by, the octopus reaches out its long arms and catches the fish. Then it can eat.  This story mainly tells:$p$, $c$["why an octopus is like a fish","how an octopus swims","how an octopus catches its food"]$c$::jsonb, 2, 2),
('3a6 - Main Idea','G3', $p$People say that greedy people have longer arms than other people. People say this because those who are greedy are always reaching and grabbing for something.  This story mainly tells:$p$, $c$["why you should not be greedy","why people want to have longer arms","why some people think that greedy people have longer arms"]$c$::jsonb, 2, 3),
('3a6 - Main Idea','G3', $p$The first bikes were called hobbyhorses. They had four wheels. Later, bikes were made with two wheels. Bike makers learned that if the wheels were larger, the bikes would move faster. So, they made bikes that had huge front wheels. Today, bikes are easier and safer to ride.  This story mainly tells:$p$, $c$["why people ride bikes","how bikes have changed over the years","why bikes were invented"]$c$::jsonb, 1, 4),
('3a6 - Main Idea','G3', $p$Years ago, people only had one name. Each name had a special meaning. Parents chose a name hoping that their children would live up to it. For example, some children were named Joy or Faith. Sometimes, names told where a person lived. For example, if there were two Peters, one might be named Peter of the Forest.  This story mainly tells:$p$, $c$["how names had meanings","why names are important","why people now have two names"]$c$::jsonb, 0, 5),
('3a6 - Main Idea','G3', $p$The Captain came to Father and said, "I'm sorry, but you have to let it go." He measured the fish and threw it back into the water. He said, "It is 2 inches shorter than the allowable size."  This story mainly tells:$p$, $c$["why Father wanted to let the fish go","why the fish was thrown back into the water","why the captain wanted Father to buy the fish"]$c$::jsonb, 1, 6),
('3a6 - Main Idea','G3', $p$The clowns were funny. The acrobats' stunts looked scary. The lion roared and the black bear jumped. Tom couldn't hear what Father was saying because the audience was too loud. Tom wished that Judy could have come with them.  This story mainly tells:$p$, $c$["why Tom hated to go to the circus","why Judy didn't want to go to the circus","what Tom saw at the circus"]$c$::jsonb, 2, 7),
('3a6 - Main Idea','G3', $p$"Help me! Someone, help me!" shouted Judy. Her parakeet flew away from her hands and sat on top of a tree. Mother tried to reach it, but she could not. Then, a fire truck came, and a fire fighter climbed the ladder and picked up the parakeet.  This story mainly tells:$p$, $c$["that Judy called a fire truck","that the parakeet didn't want to stay with Judy","how a fire fighter got the parakeet back for Judy"]$c$::jsonb, 2, 8),
('3a6 - Main Idea','G3', $p$"Help me get out!" cried Judy. Father rushed to the bathroom and tried to pull the door. The doorknob was just spinning around. Mother tried to make Judy calm down. Ted ran to the garage and tried to find pliers and other tools.  This story mainly tells:$p$, $c$["that Judy played around in the bathroom","that Judy got stuck in the bathroom","that Father could not open the door with his tools"]$c$::jsonb, 1, 9),
('3a6 - Main Idea','G3', $p$The radio said it was going to rain all afternoon. Patty wanted to go shopping, but her mother told her that it would be a bad idea. Patty didn't listen and decided to go anyway. On her way back home, it began to pour. By the time she walked in her front door, she was tired, unhappy, and soaked.  This story mainly tells:$p$, $c$["what happened to Patty because she didn't listen to her mother","why Patty had to go to the store","that Patty's mother was upset with Patty for going out"]$c$::jsonb, 0, 10);

-- ---- 3a7  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a7 - Main Idea','G3', $p$During World War II, most men had to go and fight. The women of the United States had to do the work that the men had been doing. One woman started a women's air force. She called it the Women's Air Force Service Pilots (WASPs). In all, over 1000 women became pilots. In two years, these women had flown more than 12,000 planes in the war.  This story mainly tells:$p$, $c$["how a women's air force started","why planes were important in WWII","who started the WASPs"]$c$::jsonb, 0, 1),
('3a7 - Main Idea','G3', $p$Tommy and Nick were outside playing stickball. Both boys were very good at the game, and had been playing all afternoon. At six o'clock, Tommy's mother called him into the house. "I have to go now," said Tommy. "We can play again tomorrow."  This story mainly tells:$p$, $c$["that Tommy's mother didn't want him playing with Nick","how Tommy and Nick spent their afternoon","why Tommy's mother called him"]$c$::jsonb, 1, 2),
('3a7 - Main Idea','G3', $p$This summer, my sister and I went swimming every day. We would have gone today, but the sky is already dark and the sun has been hiding all afternoon. Maybe tomorrow will be a nicer day and we can go.  This story mainly tells:$p$, $c$["where the girls like to swim","what usually happens on summer days","about a cloudy day when they couldn't swim"]$c$::jsonb, 2, 3),
('3a7 - Main Idea','G3', $p$"Don't forget to put on your earmuffs and bring your skates," Mother called out. It had snowed the night before, and the pond was frozen solid. Even though I still needed some help in standing up on the ice, Mother was still going to teach me how to spin.  This story mainly tells:$p$, $c$["how to stand on the ice","about ice skating on one afternoon","about going roller skating"]$c$::jsonb, 1, 4),
('3a7 - Main Idea','G3', $p$What a fire it was! The flames rose high into the sky. The smoke covered the whole city. All the firefighters were out to fight the blaze.  This story mainly tells:$p$, $c$["about a backyard picnic","what firefighters do on their days off","about a terrible fire"]$c$::jsonb, 2, 5),
('3a7 - Main Idea','G3', $p$Put a handful of corn kernels in a pan. Add some butter or oil. Shake it over a hot stove for a few minutes. Wait for it to start popping and then cover it with a lid.  This story mainly tells:$p$, $c$["how to make corn on the cob","how to make popcorn","what to make for dinner"]$c$::jsonb, 1, 6),
('3a7 - Main Idea','G3', $p$The house was a mess. The dishes hadn't been done all day. My little brother had dumped all his toys all over the floor. Old newspapers lay everywhere. Mom would be home in 5 minutes!  This story mainly tells:$p$, $c$["how mad Mom would be","how much of a mess was made in the house","how the house always looked"]$c$::jsonb, 1, 7),
('3a7 - Main Idea','G3', $p$In the winter, many birds fly south. Usually, they fly in large groups. Sometimes there are hundreds of thousands of birds. In the South, the birds find food and warmth for the winter.  This story mainly tells:$p$, $c$["what foods the birds find","how the birds know where to go","why birds fly south for the winter"]$c$::jsonb, 2, 8),
('3a7 - Main Idea','G3', $p$Alligators are reptiles. Mother alligators lay from 20 to 60 eggs at a time. The eggs are about as large as chicken eggs and the baby alligators are about 9 inches long. Alligators breathe with their noses above water. They can see underwater. Their feet are webbed like ducks and they have very strong tails. They can swim faster than 2 men can paddle a canoe!  This story mainly tells:$p$, $c$["how fast alligators run","how many alligators are underwater","facts about alligators"]$c$::jsonb, 2, 9),
('3a7 - Main Idea','G3', $p$The way that animals get food is called a food chain. The food chain is like a giant puzzle. Each plant and animal fits into a certain place. Small animals feed off of water and plants. Medium-sized animals eat the small animals, and the larger animals eat the medium and smaller-sized animals.  This story mainly tells:$p$, $c$["how a food chain works","why animals eat one another","what animals like to eat"]$c$::jsonb, 0, 10);

-- ---- 3a8  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a8 - Main Idea','G3', $p$At first, the water came up slowly. The animals must have thought it was only the spring rains. Soon, all the valleys were under water. The hills looked like islands. All of the animals that were gathered on the island were trapped.  This story mainly tells:$p$, $c$["that the animals did not know how to swim","what to do if it starts to rain","how heavy rains trapped animals on an island"]$c$::jsonb, 2, 1),
('3a8 - Main Idea','G3', $p$In New Mexico there is a place called "Pie Town". A man started making little fruit pies to sell at his gas station. Then other people in town thought it was a good idea and also started selling pies. One day a cowboy passed through town and said, "This sure is a pie town."  This story mainly tells:$p$, $c$["how a town got its name","why the people of Pie Town liked to bake","how the people of Pie Town decided to make some money"]$c$::jsonb, 0, 2),
('3a8 - Main Idea','G3', $p$Tracks can tell a lot about what has just traveled in that area. When it snows, look outside and see if you can tell what or who has just passed. Cat tracks are small and round. Dog tracks are usually a little bigger because dogs cannot hold in their nails. People leave large and deep shoe prints.  This story mainly tells:$p$, $c$["how tracks can show who or what has just gone by","why cat tracks are smaller than dog tracks","why human tracks are larger and deeper than animal tracks"]$c$::jsonb, 0, 3),
('3a8 - Main Idea','G3', $p$Big Red was a homing pigeon that loved to race. He had been trained ever since he was very young. At first, he was only taken a few miles from home. Then, each trip, he was taken farther and farther away before he was let go. He always found his way home quickly.  This story mainly tells:$p$, $c$["how Big Red learned to fly","how Big Red was trained","why Big Red came home"]$c$::jsonb, 1, 4),
('3a8 - Main Idea','G3', $p$Karen and Peggy were alone in the house. Suddenly, they heard strange noises in the backyard. Quietly, they took out a flashlight and went to look. As they slowly opened the door, the neighbor's cat ran by them and hid under the kitchen table.  This story mainly tells:$p$, $c$["why Karen and Peggy were home alone","what cats like to do","about the night Karen and Peggy heard noises"]$c$::jsonb, 2, 5),
('3a8 - Main Idea','G3', $p$Facts are things you know to be true. Facts are things you can taste, touch, feel, smell, or see. Facts are all around you. An example of a fact is that all cats have tails.  This story mainly tells:$p$, $c$["what facts are","what all cats have","about what is true"]$c$::jsonb, 0, 6),
('3a8 - Main Idea','G3', $p$If grapefruits don't look or taste like grapes, why are they called "grapefruits?" When they were first seen, they were growing in a cluster, or group, just as grapes grow. So, the name came from the way they grew and not the way they looked or tasted.  This story mainly tells:$p$, $c$["how grapefruits got their name","how grapefruits grow","why people like grapefruits"]$c$::jsonb, 0, 7),
('3a8 - Main Idea','G3', $p$Some fish can fly in the air for a short distance. Others have lights on their heads, so that they can see in the deep waters. Another fish can blow itself up to 3 or 4 times its size. Some fish are shaped like fans, and some others look like snakes.  This story mainly tells:$p$, $c$["the type of fish to buy for your fish tank","why some fish swim faster than others","how fish are different from one another"]$c$::jsonb, 2, 8),
('3a8 - Main Idea','G3', $p$Sometimes, people cry when they are sad. At other times, people cry tears of joy. But our eyes make tears all the time, whether we are crying or not. Tears are healthy for our eyes. Tears keep our eyes from drying out.  This story mainly tells:$p$, $c$["why people cry","how many times a day people cry","why tears are important"]$c$::jsonb, 2, 9),
('3a8 - Main Idea','G3', $p$Timmy and Sally sat in the back seat of their car. The trip would take a few hours, so their mother asked them to play a game. As they drove down the highway, they had to call out all the different things they saw along the way. By the time they stopped to get gas, Timmy and Sally had called out two hundred and ten things they had seen.  This story mainly tells:$p$, $c$["why Timmy and Sally sat in the back seat","how Timmy and Sally played a game in the car","why they stopped for gas"]$c$::jsonb, 1, 10);

-- ---- 3a9  Sequence ------------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a9 - Sequence','G3', $p$Choose the best order. A. Plants also sleep in the winter, when their activity slows down. B. A plant is said to "sleep" when it slows down or stops in its work of making food for itself. C. Plants stop work at night and sleep when the sun is not shining.$p$, $c$["C-B-A","A-B-C","B-C-A"]$c$::jsonb, 2, 1),
('3a9 - Sequence','G3', $p$Choose the best order. A. To recycle means to use over and over again. B. For example, we now recycle many materials. C. There are ways of conserving the natural resources of the earth's crust.$p$, $c$["A-B-C","C-A-B","C-B-A"]$c$::jsonb, 1, 2),
('3a9 - Sequence','G3', $p$Choose the best order. A. Not all rubber that we use comes from the rubber tree. B. Man-made rubber is called synthetic rubber. C. A large amount is made by man.$p$, $c$["C-B-A","A-C-B","B-A-C"]$c$::jsonb, 1, 3),
('3a9 - Sequence','G3', $p$Choose the best order. A. But when he is working very hard, all six quarts of blood can pass through the heart about three times in just one minute. B. A man has about six quarts of blood in his body. C. The six quarts pass through the heart in about two minutes when he is resting.$p$, $c$["B-C-A","C-B-A","A-B-C"]$c$::jsonb, 0, 4),
('3a9 - Sequence','G3', $p$Choose the best order. A. Sign language is one language that everyone speaks. B. Such motions with the arms and hands are known as sign language. C. For thousands of years, people have used their hands and arms to "talk" to people who didn't speak their own language.$p$, $c$["A-C-B","C-B-A","A-B-C"]$c$::jsonb, 1, 5),
('3a9 - Sequence','G3', $p$Choose the best order. A. A bigger bird such as a robin may have twice that many feathers. B. Not all birds have the same number of feathers. The little hummingbird may have about fifteen hundred during the summer. C. Large birds may have twenty thousand feathers or more.$p$, $c$["B-A-C","C-A-B","A-C-B"]$c$::jsonb, 0, 6),
('3a9 - Sequence','G3', $p$Choose the best order. A. In some parts of the world, people build their houses on poles or stilts. B. The air that passes underneath stilt houses helps to keep them cool. C. These houses are called stilt houses. D. In them, people are safe from animals and enemies.$p$, $c$["C-D-B-A","A-D-C-B","A-C-D-B"]$c$::jsonb, 2, 7),
('3a9 - Sequence','G3', $p$Choose the best order. A. Indian tribes couldn't understand one another. Some Indian languages were very smooth and pleasant. B. The languages were very different. C. At one time, the Indian tribes spoke many languages. D. Other Indian languages were not so easy on the ears.$p$, $c$["C-D-A-B","C-B-A-D","C-B-D-A"]$c$::jsonb, 1, 8);

-- ---- 3a10  Sequence -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a10 - Sequence','G3', $p$Choose the best order. A. Then, they tried to catch it in the cup as it fell. B. A small ball was attached to the handle of the cup by a piece of string. C. Long ago, children had a wooden cup that looked something like an ice-cream cone. D. The children jerked the ball into the air.$p$, $c$["C-D-B-A","D-C-B-A","C-B-D-A"]$c$::jsonb, 2, 1),
('3a10 - Sequence','G3', $p$Choose the best order. A. People who have been caught in an earthquake have often said that the main shock lasts for five minutes. B. Most of the major shocks, however, last from thirty to sixty seconds. C. Others say that it lasts six or seven minutes. Some people have said the shock lasts ten minutes.$p$, $c$["A-B-C","B-C-A","A-C-B"]$c$::jsonb, 2, 2),
('3a10 - Sequence','G3', $p$Choose the best order. A. The mosquito is sucking blood from the body. Once the "meal" is over, off flies the mosquito. B. Nearly all people have been bitten by mosquitoes. C. Few people know that the "bite" is not really just a bite at all.$p$, $c$["B-A-C","A-B-C","B-C-A"]$c$::jsonb, 2, 3),
('3a10 - Sequence','G3', $p$Choose the best order. A. Most people do not travel as often or as far as people in America. B. It is difficult to believe, but Americans, as a whole, travel a million miles every minute of each day! C. One reason is that many Americans have cars, and they also have good roads.$p$, $c$["C-A-B","A-C-B","B-A-C"]$c$::jsonb, 2, 4),
('3a10 - Sequence','G3', $p$Choose the best order. A. In the corner of the envelope, there is a postmark. B. Most often the postmark is a circle with the name of the city from which it is sent, and the day it was sent. C. Cut out all the different postmarks. You can start a postmark collection!$p$, $c$["A-B-C","C-A-B","C-B-A"]$c$::jsonb, 0, 5),
('3a10 - Sequence','G3', $p$Choose the best order. A. Yet, wolves can run longer distances than almost any animal. They are great distance runners. B. Wolves have been known to run ninety miles, dragging steel traps all the way. C. Gray wolves aren't very fast. They can be beaten over short distances.$p$, $c$["C-B-A","C-A-B","A-C-B"]$c$::jsonb, 1, 6),
('3a10 - Sequence','G3', $p$Choose the best order. A. The word "Laika" means barker in Russian. Russia sent the little animal up into space on November 3, 1957. B. The world's first space traveler wasn't a person. It was a dog named Laika. C. Laika zoomed around the earth in a satellite named Sputnik II.$p$, $c$["B-C-A","C-B-A","B-A-C"]$c$::jsonb, 2, 7),
('3a10 - Sequence','G3', $p$Choose the best order. A. Women's clothes, particularly hats, are often decorated with feathers. B. But feathers are also important to humans. C. Of course, we know why feathers are important to birds. D. They help birds fly and keep them warm.$p$, $c$["A-B-D-C","A-C-D-B","C-D-B-A"]$c$::jsonb, 2, 8);

-- ---- 3a11  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a11 - Inference','G3', $p$Bill said, "Hey Mike, watch out, I can hear the bees buzzing in that tree from here." Mike replied, "Don't worry, Bill. Remember last year? I don't want to go to the doctor again." Which is probably true?$p$, $c$["Mike got stung by bees last year.","Bill had the best hearing in the world.","Mike liked the doctor."]$c$::jsonb, 0, 1),
('3a11 - Inference','G3', $p$When Jane was walking home last night, she saw a big puddle in the middle of the sidewalk. She decided to jump over the puddle. She stepped back, ran toward the puddle, and jumped in the air. When Jane arrived home, her mom asked, "What happened to you?" Which is probably true?$p$, $c$["Jane always played in the mud.","Jane fell in the puddle and got her clothes dirty.","Her mom wasn't wearing her glasses."]$c$::jsonb, 1, 2),
('3a11 - Inference','G3', $p$Andrew is a very neat person. He likes to have everything put away. His bed is always made, and his desk is always clean. Andrew cares most about his computer. When Andrew was out one day, his brother, John, used Andrew's computer. When Andrew came back, he was upset to find that nothing was where it was supposed to be. Which is probably true?$p$, $c$["Andrew forgot to get something while he was outside.","Andrew's computer screen was stolen.","John didn't keep Andrew's room clean."]$c$::jsonb, 2, 3),
('3a11 - Inference','G3', $p$Rose said, "I wish that, for once, we could sleep with the windows open and not have to hear all the hammering and the trucks." Her brother sighed, "I know, but don't worry. The mayor said that the highway should be finished in a week." Which is probably true?$p$, $c$["The cars on the highway make too much smoke and noise.","Highway construction is going on near Rose's house.","Rose could not open the window because of the mayor's order."]$c$::jsonb, 1, 4),
('3a11 - Inference','G3', $p$Kim asked her mom for a needle and some thread in order to sew a button back on her sweater. When her mom gave Kim the needle and thread, she asked Kim a question. Kim answered, "No, mom, I'm okay. I can sew it myself." Which is probably true?$p$, $c$["Kim's mother asked if Kim needed something to eat.","Kim's mother asked what color Kim wanted for the thread.","Kim's mother asked Kim if she needed help sewing."]$c$::jsonb, 2, 5);

-- ---- 3a12  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('3a12 - Inference','G3', $p$The morning after Thanksgiving, Joe's dad was making pancakes for the whole family. When Joe came downstairs, his father asked, "Would you like some pancakes?" Joe answered, "No way. After last night, I don't think I could eat for a whole year." Which is probably true?$p$, $c$["Joe would never eat anything ever again after last night.","Joe had pancakes last night.","Joe ate a lot of food last night."]$c$::jsonb, 2, 1),
('3a12 - Inference','G3', $p$When Anna came home, she saw a candle burning in the living room. She got very angry after seeing that no one was home. Anna said to herself, "I must tell Lisa and Cindy that a candle shouldn't be burning when no one is home." Which is probably true?$p$, $c$["Lisa and Cindy left the candle burning.","Lisa and Cindy planned a surprise birthday party for Anna.","Lisa and Cindy are only six years old."]$c$::jsonb, 0, 2),
('3a12 - Inference','G3', $p$Most dogs start to kick and bark when they are about to be given a bath. Some dogs are known to jump out of the water and run all over the place. Which is probably true?$p$, $c$["Some dogs like to be given baths, and some dogs don't.","Every dog is bossy.","Dogs love playing around in the water."]$c$::jsonb, 0, 3),
('3a12 - Inference','G3', $p$Mom was busy cooking a ham, so she asked Carl to help her cook a turkey. He said, "Yes, I would. I can cook the turkey because I've seen you do it many times." When Carl's mom took the turkey out of the oven, she thought, "I should have cooked it myself." Which is probably true?$p$, $c$["Carl wanted to make his mom angry.","Carl ruined the turkey.","Carl's mom should have used the microwave oven."]$c$::jsonb, 1, 4),
('3a12 - Inference','G3', $p$Jenny put her sweater on. She said, "I will check the windows. Would you check the door and make sure that it's closed?" Peter checked the door and said, "Jenny, don't worry. You will be fine soon. I closed the door." Jenny said, "Good. Then, I can take my sweater off later." Which is probably true?$p$, $c$["Jenny was afraid of robbers.","The room was hot and humid.","It was very cold and windy."]$c$::jsonb, 2, 5);
