-- ============================================================================
-- Duke College — question bank: The Learning Gate, Reading Skill (LG-R-RS-2a)
-- ~Grade 2 ESL. 12 worksheets / 130 questions.
--
-- Run this AFTER supabase/setup.sql, in the Supabase SQL editor.
-- It clears any existing questions (including the 4 samples) and loads these.
--
-- correct_index is 0-based (first choice = 0). Answers were generated for you;
-- please spot-check. Two are mild judgment calls — see the comments inline.
-- ============================================================================

delete from public.questions;

-- ---- 2a1  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a1 - Context Clue','G2', $p$Choose the best word for blank (1): In (1)___, trees are (2)___ of caterpillars. Caterpillars live in a large family. It takes many (3)___ to feed all the (4)___. Sometimes they eat all the leaves on a (5)___! They may kill a tree.$p$, $c$["springtime","wintertime","school","day"]$c$::jsonb, 0, 1),
('2a1 - Context Clue','G2', $p$Choose the best word for blank (2): In (1)___, trees are (2)___ of caterpillars. Caterpillars live in a large family. It takes many (3)___ to feed all the (4)___. Sometimes they eat all the leaves on a (5)___! They may kill a tree.$p$, $c$["safe","full","tent","barks"]$c$::jsonb, 1, 2),
('2a1 - Context Clue','G2', $p$Choose the best word for blank (3): In (1)___, trees are (2)___ of caterpillars. Caterpillars live in a large family. It takes many (3)___ to feed all the (4)___. Sometimes they eat all the leaves on a (5)___! They may kill a tree.$p$, $c$["branches","skins","seeds","leaves"]$c$::jsonb, 3, 3),
('2a1 - Context Clue','G2', $p$Choose the best word for blank (4): In (1)___, trees are (2)___ of caterpillars. Caterpillars live in a large family. It takes many (3)___ to feed all the (4)___. Sometimes they eat all the leaves on a (5)___! They may kill a tree.$p$, $c$["earthworms","caterpillars","ladybugs","ants"]$c$::jsonb, 1, 4),
('2a1 - Context Clue','G2', $p$Choose the best word for blank (5): In (1)___, trees are (2)___ of caterpillars. Caterpillars live in a large family. It takes many (3)___ to feed all the (4)___. Sometimes they eat all the leaves on a (5)___! They may kill a tree.$p$, $c$["trunk","soil","branch","flower"]$c$::jsonb, 2, 5),
('2a1 - Context Clue','G2', $p$In ______, birds sing and flowers bloom.$p$, $c$["caterpillars","leaves","branch","springtime"]$c$::jsonb, 3, 6),
('2a1 - Context Clue','G2', $p$Jane's heart was ______ of joy when Jane gave presents to her friends.$p$, $c$["branch","full","springtime","leaves"]$c$::jsonb, 1, 7),
('2a1 - Context Clue','G2', $p$______ change color during the fall season.$p$, $c$["Branches","Barks","Leaves","Caterpillars"]$c$::jsonb, 2, 8),
('2a1 - Context Clue','G2', $p$The strong wind broke off the ______.$p$, $c$["springtime","full","branch","caterpillar"]$c$::jsonb, 2, 9),
('2a1 - Context Clue','G2', $p$When we had a ______, there were thunder, lightning, and heavy rain.$p$, $c$["fall","bomb","wind","storm"]$c$::jsonb, 3, 10),
('2a1 - Context Clue','G2', $p$I wonder why people like to tease. Everyone knows that it is ______. I would never do things on purpose to cause other people pain.$p$, $c$["mean","nice","mine","simple"]$c$::jsonb, 0, 11),
('2a1 - Context Clue','G2', $p$Tree rings tell the story of a tree's life. Narrow tree rings tell the story of dry years. Wide tree rings tell the story of ______ years.$p$, $c$["cold","hot","wet","cool"]$c$::jsonb, 2, 12),
('2a1 - Context Clue','G2', $p$Some grass is short. Grass around your home is usually short, but field grass often grows as ______ as a man.$p$, $c$["thin","tall","thick","strong"]$c$::jsonb, 1, 13),
('2a1 - Context Clue','G2', $p$Ants live and ______ together the way people do. Every ant has its own work to do.$p$, $c$["play","fight","stand","work"]$c$::jsonb, 3, 14),
('2a1 - Context Clue','G2', $p$In some countries, people get salt from the sea. When the sun ______ up the water, only the salt is left.$p$, $c$["fills","dries","uses","takes"]$c$::jsonb, 1, 15),
('2a1 - Context Clue','G2', $p$The beagle is a good hunting dog for catching rabbits. The beagle is a long dog, but its legs are ______. However, its legs are good for running after rabbits.$p$, $c$["short","strong","weak","tall"]$c$::jsonb, 0, 16),
('2a1 - Context Clue','G2', $p$A tortoise is a good little pet loved by kids. It can eat from your hand. It cannot ______ for it has no teeth.$p$, $c$["eat","swallow","bite","toss"]$c$::jsonb, 2, 17),
('2a1 - Context Clue','G2', $p$For many years, fuel was easy to get, but today it is ______ to get.$p$, $c$["tall","hard","soft","safe"]$c$::jsonb, 1, 18),
('2a1 - Context Clue','G2', $p$Some alligators are dangerous. Other alligators do not ______ people.$p$, $c$["save","help","hear","hurt"]$c$::jsonb, 3, 19),
('2a1 - Context Clue','G2', $p$Army ants live in groups. They do not live ______.$p$, $c$["down","warm","alone","clear"]$c$::jsonb, 2, 20);

-- ---- 2a2  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a2 - Context Clue','G2', $p$Choose the best word for blank (1): Some (1)___ that we eat come from (2)___ of the grass family. Wheat and rice are two of them. We use wheat to make (3)___. We use both wheat and rice to make breakfast foods. In some lands, people eat (4)___ rice than any (5)___ food.$p$, $c$["candies","drinks","foods","cakes"]$c$::jsonb, 2, 1),
('2a2 - Context Clue','G2', $p$Choose the best word for blank (2): Some (1)___ that we eat come from (2)___ of the grass family. Wheat and rice are two of them. We use wheat to make (3)___. We use both wheat and rice to make breakfast foods. In some lands, people eat (4)___ rice than any (5)___ food.$p$, $c$["cereal","rakes","plants","fruit"]$c$::jsonb, 2, 2),
('2a2 - Context Clue','G2', $p$Choose the best word for blank (3): Some (1)___ that we eat come from (2)___ of the grass family. Wheat and rice are two of them. We use wheat to make (3)___. We use both wheat and rice to make breakfast foods. In some lands, people eat (4)___ rice than any (5)___ food.$p$, $c$["clown","bread","party","fruitcake"]$c$::jsonb, 1, 3),
('2a2 - Context Clue','G2', $p$Choose the best word for blank (4): Some (1)___ that we eat come from (2)___ of the grass family. Wheat and rice are two of them. We use wheat to make (3)___. We use both wheat and rice to make breakfast foods. In some lands, people eat (4)___ rice than any (5)___ food.$p$, $c$["more","always","never","less"]$c$::jsonb, 0, 4),
('2a2 - Context Clue','G2', $p$Choose the best word for blank (5): Some (1)___ that we eat come from (2)___ of the grass family. Wheat and rice are two of them. We use wheat to make (3)___. We use both wheat and rice to make breakfast foods. In some lands, people eat (4)___ rice than any (5)___ food.$p$, $c$["my","other","eat","drink"]$c$::jsonb, 1, 5),
('2a2 - Context Clue','G2', $p$______ gives us energy.$p$, $c$["Grass","Horse","Passes","Food"]$c$::jsonb, 3, 6),
('2a2 - Context Clue','G2', $p$Some ______, such as poison ivy, are toxic and must never be touched.$p$, $c$["rice","bread","plants","foods"]$c$::jsonb, 2, 7),
('2a2 - Context Clue','G2', $p$______ is made with flour.$p$, $c$["Wheat","Bread","Rice","Plants"]$c$::jsonb, 1, 8),
('2a2 - Context Clue','G2', $p$I like ice cream ______ than broccoli.$p$, $c$["any","bread","more","other"]$c$::jsonb, 2, 9),
('2a2 - Context Clue','G2', $p$Puppies and kittens are raised more than ______ animals.$p$, $c$["bread","more","food","other"]$c$::jsonb, 3, 10),
('2a2 - Context Clue','G2', $p$Tim was sitting on the bench by himself. He refused to join the party. He was ______.$p$, $c$["happy","sad","old","hungry"]$c$::jsonb, 1, 11),
('2a2 - Context Clue','G2', $p$In the past, people bought things with gold coins. Today, most people use paper ______ or metal coins.$p$, $c$["bags","money","dolls","toys"]$c$::jsonb, 1, 12),
('2a2 - Context Clue','G2', $p$The Emperor penguin, the largest kind, is about four feet tall. The Fairy penguin, the smallest kind, ______ less than a foot high.$p$, $c$["weighs","comes","stands","takes"]$c$::jsonb, 2, 13),
('2a2 - Context Clue','G2', $p$Fish lay their eggs in ______ kinds of places. Some lay their eggs on the top of water. Other fish lay their eggs on stones, underwater roots, or in the mud.$p$, $c$["simple","different","clean","special"]$c$::jsonb, 1, 14),
('2a2 - Context Clue','G2', $p$Snakes that eat bugs and mice are a big help around a farm. Farmers ______ those kinds of snakes.$p$, $c$["love","hate","kill","catch"]$c$::jsonb, 0, 15),
('2a2 - Context Clue','G2', $p$It is fun to watch fireflies at night. Their lights are very ______. A group of fireflies could give enough light to show your way in the dark.$p$, $c$["dim","bright","blur","unclear"]$c$::jsonb, 1, 16),
('2a2 - Context Clue','G2', $p$Bees do not live alone. Instead, they live ______ with many other bees.$p$, $c$["open","never","long","together"]$c$::jsonb, 3, 17),
('2a2 - Context Clue','G2', $p$Because of heavy rain, the road was ______.$p$, $c$["flooded","crowded","flat","warm"]$c$::jsonb, 0, 18),
('2a2 - Context Clue','G2', $p$Steel is very strong. That is why it is used to ______ bridges.$p$, $c$["flat","build","break","fight"]$c$::jsonb, 1, 19),
('2a2 - Context Clue','G2', $p$Young dogs and cats must eat often. Puppies and ______ are hungry most of the time.$p$, $c$["flowers","dogs","kittens","animals"]$c$::jsonb, 2, 20);

-- ---- 2a3  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a3 - Context Clue','G2', $p$Choose the best word for blank (1): Houses are (1)___ in the way they are (2)___. Houses found in hot countries are (3)___ lighter. In places where it is very cold, the houses are often strong and warm. In places where it is very (4)___ much of the year, the houses are built to (5)___ the rain.$p$, $c$["same","tall","colorful","different"]$c$::jsonb, 3, 1),
('2a3 - Context Clue','G2', $p$Choose the best word for blank (2): Houses are (1)___ in the way they are (2)___. Houses found in hot countries are (3)___ lighter. In places where it is very cold, the houses are often strong and warm. In places where it is very (4)___ much of the year, the houses are built to (5)___ the rain.$p$, $c$["standing","strong","built","use"]$c$::jsonb, 2, 2),
('2a3 - Context Clue','G2', $p$Choose the best word for blank (3): Houses are (1)___ in the way they are (2)___. Houses found in hot countries are (3)___ lighter. In places where it is very cold, the houses are often strong and warm. In places where it is very (4)___ much of the year, the houses are built to (5)___ the rain.$p$, $c$["surely","ever","usually","even"]$c$::jsonb, 2, 3),
('2a3 - Context Clue','G2', $p$Choose the best word for blank (4): Houses are (1)___ in the way they are (2)___. Houses found in hot countries are (3)___ lighter. In places where it is very cold, the houses are often strong and warm. In places where it is very (4)___ much of the year, the houses are built to (5)___ the rain.$p$, $c$["full","wet","gray","loud"]$c$::jsonb, 1, 4),
('2a3 - Context Clue','G2', $p$Choose the best word for blank (5): Houses are (1)___ in the way they are (2)___. Houses found in hot countries are (3)___ lighter. In places where it is very cold, the houses are often strong and warm. In places where it is very (4)___ much of the year, the houses are built to (5)___ the rain.$p$, $c$["keep in","keep on","keep low","keep out"]$c$::jsonb, 3, 5),
('2a3 - Context Clue','G2', $p$People from ______ countries live in the United States.$p$, $c$["wet","different","loud","long"]$c$::jsonb, 1, 6),
('2a3 - Context Clue','G2', $p$The White House was ______ again and again because of wars in the United States.$p$, $c$["colorful","full","gray","built"]$c$::jsonb, 3, 7),
-- NOTE: spot-check — "always" is also defensible here; passage word is "usually".
('2a3 - Context Clue','G2', $p$Little boys are ______ noisy and playful.$p$, $c$["never","always","usually","only"]$c$::jsonb, 2, 8),
('2a3 - Context Clue','G2', $p$My shoes and pants were ______ after playing in a puddle outside.$p$, $c$["different","wet","built","usual"]$c$::jsonb, 1, 9),
('2a3 - Context Clue','G2', $p$There are things that help us to ______ bugs from our houses.$p$, $c$["keep out","use","hide","different"]$c$::jsonb, 0, 10),
('2a3 - Context Clue','G2', $p$The penguin is an ______ bird. It cannot fly, but it is an excellent swimmer.$p$, $c$["early","unusual","always","orange"]$c$::jsonb, 1, 11),
('2a3 - Context Clue','G2', $p$Some lizards change color to match their surroundings, so their enemies cannot ______ them.$p$, $c$["hear","believe","play","see"]$c$::jsonb, 3, 12),
('2a3 - Context Clue','G2', $p$A compass is an instrument used to tell direction. Without a compass, a traveler could get ______.$p$, $c$["lost","tired","sick","map"]$c$::jsonb, 0, 13),
('2a3 - Context Clue','G2', $p$The largest animal on Earth is the whale. But, the ______ animal in the world is the giraffe. It grows to be three times as tall as humans.$p$, $c$["tallest","smallest","shortest","heaviest"]$c$::jsonb, 0, 14),
('2a3 - Context Clue','G2', $p$The toad and the frog are not as alike as people think. The toad has short, ______, and rough skin, but the frog has long, wet, and smooth skin.$p$, $c$["stiff","dry","hard","bumpy"]$c$::jsonb, 1, 15),
('2a3 - Context Clue','G2', $p$Reindeer in Alaska are like horses; they can pull heavy sleds. Human babies in Alaska drink reindeer milk. So, reindeer are also like ______.$p$, $c$["dogs","chicken","cows","cats"]$c$::jsonb, 2, 16),
('2a3 - Context Clue','G2', $p$Bees work hard to collect nectar for honey by flying from flower to flower. That is why someone working hard is said to be as ______ as a bee.$p$, $c$["lazy","busy","tired","angry"]$c$::jsonb, 1, 17),
('2a3 - Context Clue','G2', $p$A starfish is special in many ways. If an arm is lost, it can grow a new one. If a starfish is cut in two, each piece will grow into a ______ new starfish.$p$, $c$["half","other","dry","whole"]$c$::jsonb, 3, 18),
('2a3 - Context Clue','G2', $p$A wasp uses mud to build its home. It ______ mud into little balls with its legs and mouth. When the mud dries, it is so hard the wind cannot break it.$p$, $c$["digs","rolls","throws","mixes"]$c$::jsonb, 1, 19),
('2a3 - Context Clue','G2', $p$When spring comes, everything in the woods begins to ______. Many animals, which were asleep all winter, begin to move, and plants begin to flower.$p$, $c$["warm up","stop","sleep","wake up"]$c$::jsonb, 3, 20);

-- ---- 2a4  Context Clue --------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a4 - Context Clue','G2', $p$Choose the best word for blank (1): Our sun is a star. It is (1)___ one of the millions of stars in the (2)___. It is not a very big (3)___. Yet, the sun is about one million (4)___ the size of the earth. Imagine it. If the sun were (5)___, it would take a million earths to fill it.$p$, $c$["only","still","even","over"]$c$::jsonb, 0, 1),
('2a4 - Context Clue','G2', $p$Choose the best word for blank (2): Our sun is a star. It is (1)___ one of the millions of stars in the (2)___. It is not a very big (3)___. Yet, the sun is about one million (4)___ the size of the earth. Imagine it. If the sun were (5)___, it would take a million earths to fill it.$p$, $c$["week","universe","earth","middle"]$c$::jsonb, 1, 2),
('2a4 - Context Clue','G2', $p$Choose the best word for blank (3): Our sun is a star. It is (1)___ one of the millions of stars in the (2)___. It is not a very big (3)___. Yet, the sun is about one million (4)___ the size of the earth. Imagine it. If the sun were (5)___, it would take a million earths to fill it.$p$, $c$["earth","rock","star","fire"]$c$::jsonb, 2, 3),
('2a4 - Context Clue','G2', $p$Choose the best word for blank (4): Our sun is a star. It is (1)___ one of the millions of stars in the (2)___. It is not a very big (3)___. Yet, the sun is about one million (4)___ the size of the earth. Imagine it. If the sun were (5)___, it would take a million earths to fill it.$p$, $c$["of","ahead","bits","times"]$c$::jsonb, 3, 4),
('2a4 - Context Clue','G2', $p$Choose the best word for blank (5): Our sun is a star. It is (1)___ one of the millions of stars in the (2)___. It is not a very big (3)___. Yet, the sun is about one million (4)___ the size of the earth. Imagine it. If the sun were (5)___, it would take a million earths to fill it.$p$, $c$["heavy","open","empty","round"]$c$::jsonb, 2, 5),
('2a4 - Context Clue','G2', $p$______ one person in my class got a perfect score on the test.$p$, $c$["When","Only","Until","Some"]$c$::jsonb, 1, 6),
('2a4 - Context Clue','G2', $p$The sun is not the only star in the ______.$p$, $c$["sea","universe","times","night"]$c$::jsonb, 1, 7),
('2a4 - Context Clue','G2', $p$The moon and ______ shine in the sky at night.$p$, $c$["sun","universe","flashlight","stars"]$c$::jsonb, 3, 8),
('2a4 - Context Clue','G2', $p$A mother's hand is five ______ as big as her baby's hand.$p$, $c$["empty","dollars","times","fingers"]$c$::jsonb, 2, 9),
('2a4 - Context Clue','G2', $p$After spilling the milk, I put away the ______ glass.$p$, $c$["empty","only","time","red"]$c$::jsonb, 0, 10),
('2a4 - Context Clue','G2', $p$When Halloween is coming, everyone has a ______ to wear. Judy wants to be a princess.$p$, $c$["jewelry","costume","hat","shoes"]$c$::jsonb, 1, 11),
('2a4 - Context Clue','G2', $p$Elephants drink some water and take a bath in the water using their ______.$p$, $c$["mouse","tail","legs","trunks"]$c$::jsonb, 3, 12),
('2a4 - Context Clue','G2', $p$An igloo is a house made of ice. It is warm inside, and it ______ people from the wind and cold.$p$, $c$["wins","gets","protects","pushes"]$c$::jsonb, 2, 13),
('2a4 - Context Clue','G2', $p$It is dangerous to stay in the sun too long. The hot sun can be ______ to people.$p$, $c$["touching","happy","harmful","dark"]$c$::jsonb, 2, 14),
('2a4 - Context Clue','G2', $p$In the past, glass and tin were thrown away. Now these materials are ______.$p$, $c$["deposited","wasted","recycled","burned"]$c$::jsonb, 2, 15),
('2a4 - Context Clue','G2', $p$Chewing gum is made from a kind of ______ called sap. The sap runs from a cut on a tree into a bag, which a farmer has tied to the tree. After the bag is filled, the sap is cooked and rolled out to make gum.$p$, $c$["bread","juice","rolls","powder"]$c$::jsonb, 1, 16),
('2a4 - Context Clue','G2', $p$Bears are often the favorite animals in a zoo because of their funny tricks and movements. They make people ______.$p$, $c$["cry","work","run","laugh"]$c$::jsonb, 3, 17),
('2a4 - Context Clue','G2', $p$Our big cities are very crowded and the streets are filled with cars. Our air is too dirty because of too many cars. It is not healthy to ______ this air.$p$, $c$["catch","breathe","play","taste"]$c$::jsonb, 1, 18),
('2a4 - Context Clue','G2', $p$Today the Mediterranean Sea is sick. If it is not cleaned soon, it will die. People want to ______ it. They want it to be a clean sea once more.$p$, $c$["save","dump","swim","decorate"]$c$::jsonb, 0, 19),
('2a4 - Context Clue','G2', $p$The orange beetle is also called the burying beetle. The orange beetle digs until it finds dead animals ______ the ground. The baby beetles feed on the dead animals until they grow.$p$, $c$["on","above","under","up"]$c$::jsonb, 2, 20);

-- ---- 2a5  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a5 - Main Idea','G2', $p$"Please read a book before you go to bed," said Mother. Tom picked a book from his bookshelf and went to bed. Two minutes later, Mother went to kiss him goodnight, but she found Tom already asleep.  This story mainly tells:$p$, $c$["that Tom didn't like to read books","that Tom usually goes to bed late","that Tom fell asleep quickly"]$c$::jsonb, 2, 1),
('2a5 - Main Idea','G2', $p$Judy and Tom ran to the trees. There were many people in the orchard. Judy picked only red apples. Tom tried to pick large apples. They had a good time.  This story mainly tells:$p$, $c$["that people don't like apples","that Tom only played in apple trees","that Judy and Tom went apple picking"]$c$::jsonb, 2, 2),
('2a5 - Main Idea','G2', $p$"Oh, what a cute monkey! But its cage is too small," said Judy to her friends. They went to see a rainforest and some animals in a building nearby. "I wish I could take them out of their cages. Animals in cages look so sad to me," said Judy.  This story mainly tells:$p$, $c$["that the animals in the cages were dangerous","that Judy felt pity for the animals in the cages","that Judy played with the animals in the cages"]$c$::jsonb, 1, 3),
('2a5 - Main Idea','G2', $p$A new boy came to Tom's class. He sat next to Tom. "After school, can you come to my house?" asked Tom. "We can do our homework together, and then play in the park."  This story mainly tells:$p$, $c$["that Tom wanted this new boy to come to his house","that this new boy didn't want to go to Tom's house","that Tom didn't want to invite this new boy to his house"]$c$::jsonb, 0, 4),
('2a5 - Main Idea','G2', $p$"Mom, do you know what happened in my class?" asked Judy. During dinner Judy always talks about her school day, her friends, and her teacher. Her mother and father like to listen to Judy.  This story mainly tells:$p$, $c$["that her mother and father don't want to listen to Judy","that Judy likes to talk about her day at dinner","that Judy doesn't talk about her friends"]$c$::jsonb, 1, 5),
('2a5 - Main Idea','G2', $p$"I want to go to the petting zoo again," said Judy, with a smile. "You went there last Saturday," said her mother. Judy likes to pet the little animals in the cages. They ate food out of Judy's hand. Judy wants to see the cute animals again this Saturday.  This story mainly tells:$p$, $c$["that Judy wants to go to the petting zoo again","that Judy wants to have a pet","that Judy prepares food at home for the animals"]$c$::jsonb, 0, 6);

-- ---- 2a6  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a6 - Main Idea','G2', $p$One day Mr. Wilson was playing golf in his back yard. He hit the ball a little too hard. It went over the fence and broke one of Mr. Smith's windows.  This story mainly tells:$p$, $c$["how to play golf","why we have fences","how Mr. Wilson broke Mr. Smith's window"]$c$::jsonb, 2, 1),
('2a6 - Main Idea','G2', $p$Raccoons are great at climbing trees. Sometimes, they make their homes in hollow trees. They eat almost anything that comes along like frogs, small turtles, berries and fruits. If there is water nearby, they will sometimes wash their food in it or even play around in the water.  This story mainly tells:$p$, $c$["why trees are hollow","how raccoons climb trees","about how raccoons behave"]$c$::jsonb, 2, 2),
('2a6 - Main Idea','G2', $p$Many farmers have cows. Cows give us fresh milk. We also get meat from their flesh. Most good leather comes from a cow's skin.  This story mainly tells:$p$, $c$["how to raise a cow","what to feed a cow","how cows are useful animals"]$c$::jsonb, 2, 3),
('2a6 - Main Idea','G2', $p$One day, a fox got his tail caught in a trap. He wanted to keep his tail, but in order to get free, he had to leave his tail behind.  This story mainly tells:$p$, $c$["how the fox got a tail","how the fox lost his tail","why foxes have long tails"]$c$::jsonb, 1, 4),
('2a6 - Main Idea','G2', $p$Dinosaurs lived many years ago. Some were very big. Others were smaller than dogs and cats. Dinosaurs were real animals. There are no dinosaurs alive today. You can see what they looked like if you go to the museum.  This story mainly tells:$p$, $c$["about dinosaurs","why dinosaurs are not alive today","that all dinosaurs were very big"]$c$::jsonb, 0, 5),
('2a6 - Main Idea','G2', $p$Sally and Lucy play together every afternoon. They play hopscotch. They play dress-up. They play with their dolls. They tell each other many stories. They are good friends.  This story mainly tells:$p$, $c$["that Sally and Lucy like to talk","what Sally and Lucy do together","that Sally and Lucy don't play together"]$c$::jsonb, 1, 6);

-- ---- 2a7  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a7 - Main Idea','G2', $p$Long ago, people did not have sugar. To make something sweeter, they used honey. Today, some people still put honey in their tea.  This story mainly tells:$p$, $c$["that honey was once used instead of sugar","where honey comes from","why some people like honey more than sugar"]$c$::jsonb, 0, 1),
('2a7 - Main Idea','G2', $p$For the first year, a baby horse is called a foal. After that, a male horse is called a colt. A female horse is called a filly. Horses are fully grown when they are four years old.  This story mainly tells:$p$, $c$["how male horses behave differently","how horses are named differently as they grow","how female horses behave differently"]$c$::jsonb, 1, 2),
('2a7 - Main Idea','G2', $p$There are many kinds of butterflies. Butterflies are beautiful, large insects. They have four pretty wings. They have six legs. They also have two feelers and a long thin body.  This story mainly tells:$p$, $c$["why butterflies are insects","why butterflies have wings","what butterflies look like"]$c$::jsonb, 2, 3),
('2a7 - Main Idea','G2', $p$There are many kinds of moths. A moth looks a lot like a butterfly. It is also an insect. It also has four wings. It also has two feelers. But its feelers are fuzzy. Its body is long, flat, and fuzzy.  This story mainly tells:$p$, $c$["why moths are fuzzy","what a moth looks like","that a moth has four wings"]$c$::jsonb, 1, 4),
('2a7 - Main Idea','G2', $p$Fish do not have eyelids, so they cannot close their eyes when they sleep. They sleep with their eyes open. They do not see while they are sleeping. They keep moving their fins while they sleep, but stay in one place. They lie on their bellies or on their sides.  This story mainly tells:$p$, $c$["that fish do not sleep","that fish do not see","how fish sleep"]$c$::jsonb, 2, 5),
('2a7 - Main Idea','G2', $p$Outside my window, I can hear the birds chirping. Male birds sing a lot. They sing to female birds. They sing to keep other male birds away. Sometimes, they sing because they are happy. Female birds do not sing much.  This story mainly tells:$p$, $c$["that female birds do not sing as much","why male birds sing","that birds chirp when they are frightened"]$c$::jsonb, 1, 6);

-- ---- 2a8  Main Idea -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
-- NOTE: spot-check — passage mentions fruit being good for you, but the detail focuses on what fruits are.
('2a8 - Main Idea','G2', $p$Do you like eating fruit and vegetables? They are good for you. They come in many colors and flavors. Fruits have seeds. Most fruits grow on trees.  This story mainly tells:$p$, $c$["why a tomato is a fruit","what is good for you","what fruits are"]$c$::jsonb, 2, 1),
('2a8 - Main Idea','G2', $p$Too much light can hurt your eyes. That is why you should never look at the sun. We need light to see, but we need to be careful. When too much light gets into our eyes, we squint. This helps to keep some of the light out.  This story mainly tells:$p$, $c$["that too much light is not good for our eyes","that we squint all the time","that we should not look at the sun"]$c$::jsonb, 0, 2),
('2a8 - Main Idea','G2', $p$Sneezing is good for you. Dust and germs can get into your nose, and they can tickle. When we sneeze, we blow out a lot of air through our noses and mouths. This air blows away the dust and germs.  This story mainly tells:$p$, $c$["sneezing is useful","germs get into our nose","dust tickles"]$c$::jsonb, 0, 3),
('2a8 - Main Idea','G2', $p$Germs are so small that you need a microscope to see them. Germs are tiny living things. Some germs can make you sick. When we sneeze, we spread a lot of germs. We can also spread germs by touching things. That is why we need to wash our hands and keep our bodies clean.  This story mainly tells:$p$, $c$["how germs live","about germs and how they affect us","that we must wash our hands"]$c$::jsonb, 1, 4),
('2a8 - Main Idea','G2', $p$Mother heard noises. "Sally, what are you doing out of bed?" Sally did not answer, but she just kept walking with her eyes open. Mother called her again, but realized that Sally was sleepwalking.  This story mainly tells:$p$, $c$["that Sally did not want to answer","that Sally's mother was dreaming","that Sally was walking in her sleep"]$c$::jsonb, 2, 5),
('2a8 - Main Idea','G2', $p$Many people go to libraries. Libraries are places that have many books. You can find a book on any subject. You can read the book at the library, or you can take the book home for a few days. Many students like to study in libraries.  This story mainly tells:$p$, $c$["why libraries are useful","how many libraries there are","when the first library was opened"]$c$::jsonb, 0, 6);

-- ---- 2a9  Sequence ------------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a9 - Sequence','G2', $p$Choose the best order. A. The snowman's eyes were buttons. His nose was a carrot. His mouth was two sticks. B. Tara and Ted were playing outdoors in the snow. C. They made a little snowman.$p$, $c$["B-A-C","C-A-B","B-C-A"]$c$::jsonb, 2, 1),
('2a9 - Sequence','G2', $p$Choose the best order. A. "How old will Tom be?" asked Penny's big sister, Donna. B. "Seven," said Penny. C. Penny said, "I'm going to Tom's birthday party tomorrow."$p$, $c$["A-B-C","A-C-B","C-A-B"]$c$::jsonb, 2, 2),
('2a9 - Sequence','G2', $p$Choose the best order. A. Frogs and turtles can live in the water. B. These animals that live on land and in the water can walk and swim. C. But they can live on land, too.$p$, $c$["A-B-C","A-C-B","B-A-C"]$c$::jsonb, 1, 3),
('2a9 - Sequence','G2', $p$Choose the best order. A. It makes wind. B. It can also make kites fly. C. Sometimes, air moves very fast. D. The wind can blow things away.$p$, $c$["C-A-D-B","D-B-C-A","C-A-B-D"]$c$::jsonb, 0, 4),
('2a9 - Sequence','G2', $p$Choose the best order. A. Farmers gather the eggs soon after they are laid. B. Some chickens are raised for their eggs. C. Eggs must be kept in a cool place to keep them from spoiling.$p$, $c$["B-C-A","B-A-C","A-B-C"]$c$::jsonb, 1, 5),
('2a9 - Sequence','G2', $p$Choose the best order. A. After twenty days, they will move again. B. Every twenty days, the group moves to a new place to live. C. Army ants never stay in one place for a long time.$p$, $c$["C-B-A","C-A-B","B-A-C"]$c$::jsonb, 0, 6),
('2a9 - Sequence','G2', $p$Choose the best order. A. It is the caterpillar that destroys clothes. B. People say that moths eat clothes. C. This isn't true. Moths can't eat clothes. D. They don't have the right type of mouth.$p$, $c$["B-C-A-D","A-C-B-D","B-C-D-A"]$c$::jsonb, 2, 7),
('2a9 - Sequence','G2', $p$Choose the best order. A. The tree that gives us chewing gum sap grows in hot countries. B. Did you know that chewing gum comes from trees? C. It comes from a kind of juice that we call sap.$p$, $c$["B-A-C","B-C-A","A-C-B"]$c$::jsonb, 1, 8);

-- ---- 2a10  Sequence -----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a10 - Sequence','G2', $p$Choose the best order. A. The mother lays the eggs in the father's pocket. B. The sea horse keeps its babies in a pocket. C. The father cares for them. He keeps them until they hatch.$p$, $c$["C-A-B","B-C-A","B-A-C"]$c$::jsonb, 2, 1),
('2a10 - Sequence','G2', $p$Choose the best order. A. So, Terry's mother helps him find food. Terry sleeps with his mother at night. B. He is fat and yellow. He lives with his mother. C. Terry is a baby chicken.$p$, $c$["A-B-C","A-C-B","C-B-A"]$c$::jsonb, 2, 2),
('2a10 - Sequence','G2', $p$Choose the best order. A. Their feet are not good to walk with. B. Ducks like to be in the water. C. However, ducks' feet are good to swim with. D. They are also not good to run with.$p$, $c$["B-D-C-A","A-B-C-D","B-A-D-C"]$c$::jsonb, 2, 3),
('2a10 - Sequence','G2', $p$Choose the best order. A. Sam and Mary feed the animals on their farm. B. Then, the two children feed the cows. They feed the horses last. C. Sam feeds the pigs first. Mary feeds the chickens.$p$, $c$["A-B-C","A-C-B","C-A-B"]$c$::jsonb, 1, 4),
('2a10 - Sequence','G2', $p$Choose the best order. A. The ball is yellow and very big. B. Five children are playing in the yard. C. They are playing with a big ball.$p$, $c$["B-C-A","B-A-C","C-B-A"]$c$::jsonb, 0, 5),
('2a10 - Sequence','G2', $p$Choose the best order. A. Do you remember the names of the different seasons? B. They are spring, summer, fall, and winter. C. Many places on the earth have different seasons.$p$, $c$["A-C-B","C-A-B","B-A-C"]$c$::jsonb, 1, 6),
('2a10 - Sequence','G2', $p$Choose the best order. A. Sugar comes mainly from two plants. B. Most sugar comes from sugar cane. C. Some comes from sugar beets.$p$, $c$["C-B-A","B-C-A","A-B-C"]$c$::jsonb, 2, 7),
('2a10 - Sequence','G2', $p$Choose the best order. A. There are only two ways to make something move. B. A pull or a push is called force. C. You can pull it or push it.$p$, $c$["A-B-C","B-A-C","A-C-B"]$c$::jsonb, 2, 8);

-- ---- 2a11  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a11 - Inference','G2', $p$Jane said, "Come and play." Bill answered, "Fine, but only if your dog Cookie is not there." Which is probably true?$p$, $c$["Bill is scared of Cookie, Jane's dog.","Bill doesn't like the game they are going to play.","Bill wants to watch TV at his own house."]$c$::jsonb, 0, 1),
('2a11 - Inference','G2', $p$Sam said, "Let's go catch butterflies." Joel answered, "I have never caught a butterfly." Sam said, "It's easy. You take a net and chase them until you have one." Which is probably true?$p$, $c$["Joel doesn't like to catch butterflies.","Sam has caught butterflies before.","Sam loves animals."]$c$::jsonb, 1, 2),
('2a11 - Inference','G2', $p$One night Anne and her friends went to watch the stars at the beach. The next day, Anne said, "I should have worn another sweater last night." Which is probably true?$p$, $c$["Her friend didn't wear an extra sweater either.","Anne will never watch stars again.","Anne was cold last night."]$c$::jsonb, 2, 3),
('2a11 - Inference','G2', $p$Bobby's friend just moved to a new house. Bobby looked at a map, and saw he had three more blocks to go. Bobby was right. Which is probably true?$p$, $c$["Bobby was driving.","Bobby hadn't been to his friend's house yet.","His friend moves all the time."]$c$::jsonb, 1, 4),
('2a11 - Inference','G2', $p$Last year at a Halloween party, everyone was having a good time. Mary went as a ghost. She danced with her friend Bob. Bob asked her, "When is Mary getting here?" Which is probably true?$p$, $c$["Bob was playing a trick on Mary.","Bob has another friend named Mary.","Mary was wearing a mask, and Bob didn't know it was her."]$c$::jsonb, 2, 5);

-- ---- 2a12  Inference ----------------------------------------------------------
insert into public.questions (subject, grade, prompt, choices, correct_index, sort_order) values
('2a12 - Inference','G2', $p$Meg cried for her mom to come because she saw a strange shadow. Then, both Meg and her mom heard, "Meow," from the shadow. Which is probably true?$p$, $c$["The cat wanted to scare Meg.","Meg's mom is not scared of anything.","The shadow was from a cat."]$c$::jsonb, 2, 1),
('2a12 - Inference','G2', $p$There were only two people living in Mike's house, but there were four chairs. Mike wanted more space. He wanted to move one chair to another room. Mike asked Sam, his brother, to help him. Which is probably true?$p$, $c$["The chair is heavy.","Sam is moving to a new house.","Mike wants to have a chair in the bedroom."]$c$::jsonb, 0, 2),
('2a12 - Inference','G2', $p$Mary bought some seeds, some wood, and nails. She built a birdhouse in her backyard. Then, Mary put the birdseed inside the birdhouse. Which is probably true?$p$, $c$["Mary loves birds.","Mary likes to eat the birdseed.","Mary has a big backyard."]$c$::jsonb, 0, 3),
('2a12 - Inference','G2', $p$At lunchtime, everyone in the family had something different. Ally had a sandwich. Mom and Dad had salads. Emma had some soup. Johnny said, "I'm full. Let's play now!" Which is probably true?$p$, $c$["Johnny was a cat.","Johnny had already eaten.","Johnny liked to eat chicken."]$c$::jsonb, 1, 4),
('2a12 - Inference','G2', $p$"What do you want to do? Go to the movies or go to the World Series?" asked Billy's dad. "I want to go to the World Series. That is only once a year," answered Billy. Which is probably true?$p$, $c$["Billy and his dad would fight.","Sammy Sosa didn't play.","Billy and his dad went to the World Series."]$c$::jsonb, 2, 5);
